{
  "hash": "3d3e859d1f7f92b2fb7d83ff4ee2d1f5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"16. Ranking fifteen candidate families\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\n`dist_fit()` answers \"what are the parameters of this family\". `fit_distributions()` answers the\nquestion that comes before it: which family. It fits every candidate in the RMC.BestFit\n`DistributionList` to the same sample by maximum likelihood and reports AIC, BIC and RMSE for each,\nleaving the ranking to you. There are fifteen candidates, and this page is about reading their\ntable honestly on a record short enough that the ranking is not settled.\n\nExample 02 uses `fit_distributions()` in passing, at the end of a page about estimation methods.\nThis one is about the verb itself. It has no upstream counterpart: the USACE-RMC\nNumerics-Python-Examples repository has no distribution-selection notebook.\n\n## What you'll learn\n\n- What the fifteen candidates are, and which of them can fail on a given sample.\n- Why AIC, BIC and RMSE can each name a different winner, and what to do about that.\n- How to read the `converged` column, which is not a warning to ignore.\n- How to get the parameters of the family you picked, which the ranking does not carry.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## The record\n\nTwenty annual peak discharges, the same series the package's own oracle fixture uses, so the\nnumbers below are pinned against the real C# `FittingAnalysis` at the bottom of this page.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeaks <- c(45000, 38000, 52000, 61000, 33000, 49000, 55000, 42000, 67000, 39000,\n           48000, 51000, 36000, 58000, 44000, 53000, 47000, 62000, 41000, 50000)\n\ncat(sprintf(\"n = %d, mean = %.0f cfs, range = %.0f to %.0f cfs\\n\",\n            length(peaks), mean(peaks), min(peaks), max(peaks)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 20, mean = 48550 cfs, range = 33000 to 67000 cfs\n```\n\n\n:::\n:::\n\n\nTwenty years is a short record, and the point of this page is that the ranking says so.\n\n## The ranking\n\nOne call. The result is a list of four parallel vectors, one entry per candidate, which\n`as.data.frame()` turns into a table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nranking <- as.data.frame(fit_distributions(peaks))\nranking$dAIC <- ranking$aic - min(ranking$aic, na.rm = TRUE)\n\nprint(ranking[order(ranking$aic), c(\"distribution\", \"aic\", \"dAIC\", \"bic\", \"rmse\", \"converged\")],\n      row.names = FALSE, digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            distribution     aic     dAIC     bic    rmse converged\n       GeneralizedPareto 423.312 0.000000 426.299 1278.64      TRUE\n       GammaDistribution 424.153 0.841015 426.144 1335.94      TRUE\n               LogNormal 424.228 0.915925 426.219 1302.79      TRUE\n                LnNormal 424.228 0.915925 426.219 1302.40      TRUE\n                  Normal 424.519 1.207353 426.511 1436.10      TRUE\n                  Gumbel 425.013 1.701294 427.005 1205.71      TRUE\n                 Weibull 425.482 2.170389 427.474 1464.27      TRUE\n                Logistic 425.540 2.228368 427.532 1442.13      TRUE\n GeneralizedExtremeValue 425.941 2.628785 428.928 1388.56      TRUE\n          PearsonTypeIII 426.121 2.808665 429.108 1303.29      TRUE\n       LogPearsonTypeIII 426.123 2.811380 429.110 1336.34      TRUE\n       GeneralizedNormal 426.195 2.883110 429.182 1328.01      TRUE\n     GeneralizedLogistic 427.303 3.991243 430.290 1257.30      TRUE\n             Exponential 430.073 6.760722 432.064 4714.46      TRUE\n               KappaFour     NaN      NaN     NaN     NaN     FALSE\n```\n\n\n:::\n:::\n\n\nFifteen rows, one per candidate. `converged` is `FALSE` for KappaFour, whose four-parameter fit did\nnot converge on this sample; its metrics are `NaN` and it cannot be ranked. A failed candidate is\nnot a defect in the sample or in the fit. It is the honest report that this family had nothing to\nsay about this record, and its row is kept rather than dropped so that a candidate cannot disappear\nfrom the list without being noticed.\n\n## Three criteria, three winners\n\nSorting the same table by each of the three metrics gives three different leaders.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleader <- function(metric) {\n  ok <- ranking[!is.na(ranking[[metric]]), ]\n  ok$distribution[which.min(ok[[metric]])]\n}\n\ncat(sprintf(\"lowest AIC:  %s\\n\", leader(\"aic\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlowest AIC:  GeneralizedPareto\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"lowest BIC:  %s\\n\", leader(\"bic\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlowest BIC:  GammaDistribution\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"lowest RMSE: %s\\n\", leader(\"rmse\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlowest RMSE: Gumbel\n```\n\n\n:::\n:::\n\n\nThey disagree because they reward different things. AIC penalizes each parameter by 2, BIC by\n$\\ln n$, which is 3.0 at twenty points, so BIC is stiffer and demotes every three-parameter family\nby about one point relative to AIC. RMSE is not a likelihood criterion at all: it measures the\ndistance between the fitted quantiles and the observations at their Hirsch-Stedinger plotting\npositions, so it rewards a family that tracks the middle of the record even when the likelihood\nprefers another.\n\nThe AIC column has the more useful reading. Twelve of the fourteen rankable candidates fall within\nthree AIC points of the best, and six of them within two, which on twenty observations is not\nevidence of anything. The table's real message is that most of these families describe this record\nabout equally well, and that picking one of them by its rank alone is picking noise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nranked <- ranking[order(ranking$aic), ]\nranked <- ranked[!is.na(ranked$aic), ]\n\nop <- par(mar = c(4.5, 10, 3, 1))\nplot(ranked$dAIC, rev(seq_len(nrow(ranked))), pch = 19, col = \"#5b7a8c\",\n     yaxt = \"n\", ylab = \"\", xlab = \"AIC above the best candidate\",\n     main = \"Fifteen candidates, three points of AIC\")\naxis(2, at = rev(seq_len(nrow(ranked))), labels = ranked$distribution, las = 1, cex.axis = 0.8)\nabline(v = 2, col = \"#b06a3b\", lty = 2)\ntext(2, 1.5, \" 2 points\", col = \"#b06a3b\", adj = 0, cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(op)\n```\n:::\n\n\n## The winner, and why to distrust it\n\n`fit_distributions()` reports metrics, not parameters. Refit the family you picked with\n`dist_fit()` to get them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest <- dist_fit(\"GeneralizedPareto\", peaks, method = \"mle\")\nbest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<corehydro_dist> GeneralizedPareto(ξ = 33000, α = 29295.7, κ = 0.852354)\n```\n\n\n:::\n\n```{.r .cell-code}\nbounds <- c(dist_params(best)[1],\n            dist_params(best)[1] + dist_params(best)[2] / dist_params(best)[3])\ncat(sprintf(\"support: %.0f to %.0f cfs\\n\", bounds[1], bounds[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsupport: 33000 to 67370 cfs\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"observed: %.0f to %.0f cfs\\n\", min(peaks), max(peaks)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nobserved: 33000 to 67000 cfs\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"quantile at p = 0.99999: %.0f cfs\\n\", dist_quantile(best, 0.99999)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nquantile at p = 0.99999: 67368 cfs\n```\n\n\n:::\n:::\n\n\nLook at what the AIC winner actually did. Its location parameter is 33,000, exactly the smallest\nobservation, and with a positive shape the family is bounded above as well, here at 67,370 cfs,\n370 cfs past the largest observation. The fit has pulled its entire support onto the observed range.\nIt follows that this distribution assigns probability zero to any flood above 67,370 cfs: the\nquantile at a one-in-100,000 exceedance is still 67,368.\n\nNothing in the table reports that. AIC rewards the likelihood, and a support squeezed onto the data\nis where the likelihood is largest, so a bounded three-parameter family will often top a short\nrecord. It is a property of twenty observations, not a finding about the river. Read `dAIC` rather\nthan the rank, look at the support of whatever wins, and prefer a family you can defend on physical\ngrounds when the table is this flat.\n\n## The fifteenth candidate\n\n`GeneralizedNormal` is the three-parameter LogNormal, called the generalized normal in Hosking's\nL-moment work: location $\\xi$, scale $\\alpha$, shape $\\kappa$. At $\\kappa = 0$ it is the plain\nNormal; $\\kappa < 0$ bounds it below at $\\xi + \\alpha / \\kappa$ and skews it right, and $\\kappa > 0$\ndoes the mirror image.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngn <- dist_fit(\"GeneralizedNormal\", peaks, method = \"mle\")\ngn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<corehydro_dist> GeneralizedNormal(ξ = 47929.3, α = 8829.03, κ = -0.140333)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"implied lower bound: %.0f cfs\\n\",\n            dist_params(gn)[1] + dist_params(gn)[2] / dist_params(gn)[3]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nimplied lower bound: -14986 cfs\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"100-year peak: %.0f cfs\\n\", dist_quantile(gn, 0.99)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n100-year peak: 72218 cfs\n```\n\n\n:::\n:::\n\n\nIts shape parameter is barely below zero, so the fitted density is nearly Normal and the implied\nlower bound falls at about -15,000 cfs, far outside anything a river can do. That is the sensible\nreading of a small $\\kappa$: the bound is not a claim about discharge, it is the family telling you\nit found no skew worth the third parameter. Which is why the row sits in the middle of the AIC\ntable. It spent a parameter to repeat what the Normal already said.\n\n## The frequency curve\n\nThe three leading families, plotted against the record on its Weibull plotting positions. This is\nthe plot that shows what a three-point AIC spread means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfamilies <- c(\"GeneralizedPareto\", \"GammaDistribution\", \"LogNormal\")\nfits <- lapply(families, dist_fit, data = peaks, method = \"mle\")\npp <- plotting_positions(length(peaks))\ngrid <- seq(0.01, 0.995, length.out = 300)\ncolors <- c(\"#6b7f3f\", \"#b06a3b\", \"#5b7a8c\")\n\nplot(1 / (1 - pp), sort(peaks), log = \"x\", pch = 16, col = \"#3f3f3f\",\n     xlim = c(1, 200), ylim = c(30000, 100000),\n     main = \"Three families, one 20-year record\",\n     xlab = \"Return period (years)\", ylab = \"Annual peak (cfs)\")\nfor (i in seq_along(fits)) {\n  lines(1 / (1 - grid), dist_quantile(fits[[i]], grid), col = colors[i], lwd = 2)\n}\nlegend(\"topleft\", c(families, \"Observed\"), bty = \"n\",\n       lty = c(1, 1, 1, NA), lwd = c(2, 2, 2, NA), pch = c(NA, NA, NA, 16),\n       col = c(colors, \"#3f3f3f\"))\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe three curves track each other over the range the data cover and part company past it, which is\nexactly where a design estimate is read. The AIC winner is the one that flattens: its curve bends\ninto the ceiling described above, while the two families ranked below it keep rising. Ranking\nsettles which family fits the observations. It does not settle the extrapolation, and no table\nbuilt from twenty points can.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextrap <- sapply(fits, dist_quantile, p = 0.99)\nnames(extrap) <- families\nprint(round(extrap))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralizedPareto GammaDistribution         LogNormal \n            66692             71682             73440 \n```\n\n\n:::\n:::\n\n\n## Key takeaways\n\n1. `fit_distributions()` fits fifteen candidates and reports AIC, BIC and RMSE. Ranking is yours,\n   and so is the decision not to trust the ranking.\n2. AIC, BIC and RMSE reward different things and can each name a different winner. On a short\n   record that disagreement is the finding.\n3. `converged = FALSE` means that candidate's MLE failed and its metrics are `NaN`. The row stays\n   in the table so the failure is visible.\n4. The ranking carries no parameters. Refit with `dist_fit()` and look at what the winner did. A\n   bounded family whose support has collapsed onto the observed range has fit the record length,\n   not the river, and the table cannot tell you that.\n\n## Exercise\n\n1. Draw 200 values from `distribution(\"LogNormal\", c(4.7, 0.1))` with `dist_random()` and rank the\n   candidates on them.\n2. Compare the AIC spread with the one above. Does the true family win, and by how much?\n3. Repeat at n = 20 with a different seed a few times, and watch the winner change.\n\n## Reproduction check\n\nThe block below has two halves.\n\nThe first pins the numbers this page prints, at 1e-15 relative tolerance. They are deterministic:\n`fit_distributions()` optimizes through a seeded DifferentialEvolution run, so the same sample gives\nthe same table on every call and in both languages. The Python twin of this page prints the\nidentical digits.\n\nThe second pins the same quantities against the real C# `RMC.BestFit.FittingAnalysis`, whose values\nlive in `fixtures/analyses/fit_distributions_smoke.json` and are read out of the running C# library\nby the repository's dotnet oracle gate. AIC and BIC agree with that library to a few units in the\nlast place, so they are compared at the same 1e-15 relative tolerance every literal on this site\nuses. RMSE gets 1e-8, the tolerance the fixture itself carries for it: the C# goodness-of-fit helper\naccumulates that sum in a different order and the two answers agree to about 3e-12 relative rather\nthan exactly. Each tolerance is the measured disagreement, not a margin chosen to make the check\npass.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear <- \\(x, literal, tol = 1e-15) abs(x / literal - 1) < tol\naic_of <- \\(name) ranking$aic[ranking$distribution == name]\nbic_of <- \\(name) ranking$bic[ranking$distribution == name]\nrmse_of <- \\(name) ranking$rmse[ranking$distribution == name]\n\nstopifnot(\n  # Structure: fifteen candidates, KappaFour the only failure.\n  nrow(ranking) == 15L,\n  sum(!ranking$converged) == 1L,\n  ranking$distribution[!ranking$converged] == \"KappaFour\",\n  \"GeneralizedNormal\" %in% ranking$distribution,\n\n  # This page's own table, at full precision.\n  near(aic_of(\"GeneralizedPareto\"), 423.31191701519708),\n  near(aic_of(\"GammaDistribution\"), 424.15293208959202),\n  near(aic_of(\"Normal\"), 424.51926984004484),\n  near(aic_of(\"GeneralizedNormal\"), 426.19502666475483),\n  near(bic_of(\"GeneralizedPareto\"), 426.29911383585903),\n  near(rmse_of(\"GeneralizedPareto\"), 1278.6425510135564),\n  near(rmse_of(\"Normal\"), 1436.0968615642446)\n)\n\n# The C# oracle: fixtures/analyses/fit_distributions_smoke.json, read from the running\n# RMC.BestFit.FittingAnalysis by tools/verify_oracles.py. Candidate index 4 is GeneralizedNormal,\n# 5 is GeneralizedPareto, 12 is Normal.\nstopifnot(\n  near(aic_of(\"GeneralizedNormal\"), 426.19502666475506),\n  near(aic_of(\"GeneralizedPareto\"), 423.311917015197),\n  near(bic_of(\"GeneralizedPareto\"), 426.299113835859),\n  near(aic_of(\"Normal\"), 424.51926984004484),\n  near(bic_of(\"Normal\"), 426.5107343871528),\n  # RMSE: a different summation order in the C# helper, agreeing to ~3e-12 relative.\n  near(rmse_of(\"GeneralizedPareto\"), 1278.642551017543, tol = 1e-8),\n  near(rmse_of(\"Normal\"), 1436.0968615640775, tol = 1e-8)\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}