{
  "hash": "cf735f3c2f74f4f015178e12db6750e5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"04. Bayesian inference with MCMC\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\nPorted from\n[`04_mcmc_bayesian_inference.ipynb`](https://github.com/USACE-RMC/Numerics-Python-Examples/blob/main/notebooks/04_mcmc_bayesian_inference.ipynb)\nin the USACE-RMC Numerics-Python-Examples repository (0BSD licensed). The upstream\nnotebook drives the C# `Numerics.dll` through pythonnet; this version uses\n`corehydror`, whose compiled core is a validated C++ port of the same library, so the\nseeded MCMC results below reproduce the upstream outputs at every digit the\nupstream displays (see the reproduction check at the end for the honest fine\nprint). The Python version of this example uses the same core and prints the same\nnumbers.\n\n## What you'll learn\n\n- Bayesian estimation of distribution parameters from real flood data with the\n  random walk Metropolis-Hastings (RWMH) sampler.\n- How `mcmc_sample()` packages the upstream recipe (constraint-based uniform\n  priors, MAP initialization, serial chains, seed 12345) into one call.\n- Fitting and comparing several candidate distributions.\n- Posterior predictive checks.\n- Adaptive versus non-adaptive samplers.\n\n## Setup\n\nThe upstream setup loads the CoreCLR runtime, resolves `Numerics.dll`, imports the\nMCMC classes, and wraps every Python likelihood in a .NET delegate. It also warns\nthat the C# sampler's parallel chains contend for Python's GIL, so every upstream\nexample sets `ParallelizeChains = False`. None of that applies here: the ported\nchain driver always runs chains serially (exactly the upstream's\n`ParallelizeChains = False` code path), so seeded results are reproducible by\nconstruction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## Example: flood frequency analysis\n\nProblem: we have annual peak flow data and want to estimate distribution parameters\nwith uncertainty, using Bayesian inference through an MCMC sampler.\n\nData source: Tippecanoe River near Delphi, Indiana (from \"Flood Frequency\nAnalysis\", A.R. Rao and K.H. Hamed, CRC Press, 2000). The record has 48 annual\npeaks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflood = c(6290, 2700, 13100, 16900, 14600, 9600, 7740, 8490, 8130, 12000,\n          17200, 15000, 12400, 6960, 6500, 5840, 10400, 18800, 21400, 22600,\n          14200, 11000, 12800, 15700, 4740, 6950, 11800, 12100, 20600, 14600,\n          14600, 8900, 10600, 14200, 14100, 14100, 12500, 7530, 13400, 17600,\n          13400, 19200, 16900, 15500, 14500, 21900, 10400, 7460)\n\nsummary_df = data.frame(\n  Metric = c(\"Count\", \"Sample mean (cfs)\", \"Sample std (cfs)\", \"Min (cfs)\", \"Max (cfs)\"),\n  Value = round(c(length(flood), mean(flood), sd(flood), min(flood), max(flood)), 2)\n)\ncat(\"Flood dataset summary\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFlood dataset summary\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Metric    Value\n1             Count    48.00\n2 Sample mean (cfs) 12665.21\n3  Sample std (cfs)  4709.74\n4         Min (cfs)  2700.00\n5         Max (cfs) 22600.00\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nhist(flood, breaks = 15, col = \"#6b7f3f\", border = \"white\",\n     xlab = \"Annual peak flow (cfs)\", main = \"Observed flood data\")\nplot(seq_along(flood), sort(flood), type = \"o\", pch = 16, col = \"#5b7a8c\",\n     xlab = \"Rank\", ylab = \"Annual peak flow (cfs)\", main = \"Ranked flood magnitudes\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n### Fit a Normal distribution\n\nThe upstream builds every piece by hand: it asks the distribution for its parameter\nconstraints (`GetParameterConstraints`), turns them into uniform priors (for the\nNormal: mean ~ Uniform(-1000000, 1000000) and standard deviation ~\nUniform(0, 100000)), wraps a Python log-likelihood in a .NET delegate, and runs\n`RWMH` with MAP initialization and the default seed 12345.\n\n`mcmc_sample()` is that exact recipe in one call: the same constraint-based uniform\npriors, the same MAP initialization, the same serial chain driver, and the same C#\ndefaults (four chains, 3500 recorded draws per chain with a thinning interval of\n20, the first 1750 treated as warm-up, plus 10000 dedicated posterior draws that\nfeed the summary statistics).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_norm = mcmc_sample(flood, distribution = \"Normal\", sampler = \"RWMH\", seed = 12345)\n\nposterior_table = function(fit) {\n  data.frame(\n    Parameter = fit$parameters,\n    `Posterior mean` = round(fit$posterior_mean, 2),\n    `Lower 90% CI` = round(fit$posterior_lower_ci, 2),\n    `Upper 90% CI` = round(fit$posterior_upper_ci, 2),\n    check.names = FALSE\n  )\n}\n\ncat(\"Normal distribution results\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNormal distribution results\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(posterior_table(fit_norm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Parameter Posterior mean Lower 90% CI Upper 90% CI\n1         µ       12677.64     11522.23     13847.04\n2         σ        4844.70      4073.12      5735.17\n```\n\n\n:::\n:::\n\n\nThese are the numbers in the upstream results table: posterior mean 12677.64 with\n90 percent credible interval (11522.23, 13847.04) for the mean, and 4844.70 with\n(4073.12, 5735.17) for the standard deviation. Plot the fit at the posterior-mean\nparameters against the data, like the upstream does.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_fit = function(fit, family) {\n  d = distribution(family, fit$posterior_mean)\n  x = seq(min(flood) * 0.85, max(flood) * 1.10, length.out = 400)\n  par(mfrow = c(1, 2))\n  hist(flood, breaks = 15, freq = FALSE, col = \"#6b7f3f\", border = \"white\",\n       xlab = \"Annual peak flow (cfs)\", main = paste(family, \"fit: density\"))\n  lines(x, sapply(x, \\(v) dist_pdf(d, v)), col = \"#b06a3b\", lwd = 2)\n  s = sort(flood)\n  ecdf_y = seq_along(s) / length(s)\n  plot(s, ecdf_y, type = \"s\", col = \"#8c8c7a\", lwd = 2,\n       xlab = \"Annual peak flow (cfs)\", ylab = \"CDF\",\n       main = paste(family, \"fit: CDF\"))\n  lines(s, sapply(s, \\(v) dist_cdf(d, v)), col = \"#b06a3b\", lwd = 2)\n  par(mfrow = c(1, 1))\n}\n\nplot_fit(fit_norm, \"Normal\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n### Fit a Logistic distribution\n\nThe Logistic distribution has heavier tails than the Normal [1]. The same one-liner\nfits it; only the family name changes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_logi = mcmc_sample(flood, distribution = \"Logistic\", sampler = \"RWMH\", seed = 12345)\ncat(\"Logistic distribution results\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic distribution results\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(posterior_table(fit_logi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Parameter Posterior mean Lower 90% CI Upper 90% CI\n1         ξ       12632.66     11438.17     13801.22\n2         α        2825.51      2308.14      3440.53\n```\n\n\n:::\n\n```{.r .cell-code}\nplot_fit(fit_logi, \"Logistic\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Comparing multiple distribution fits\n\nAdd a Gumbel fit and compare the three candidates. The upstream compares the fits\nvisually and tabulates the posterior means; we add a plug-in log-likelihood\n(evaluated at the posterior-mean parameters) and AIC to make the ranking explicit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_gum = mcmc_sample(flood, distribution = \"Gumbel\", sampler = \"RWMH\", seed = 12345)\n\nfits = list(Normal = fit_norm, Logistic = fit_logi, Gumbel = fit_gum)\n\npar(mfrow = c(1, 3))\nx = seq(2000, 25000, length.out = 400)\nfor (name in names(fits)) {\n  d = distribution(name, fits[[name]]$posterior_mean)\n  hist(flood, breaks = 15, freq = FALSE, col = \"#8c8c7a\", border = \"white\",\n       xlab = \"Peak flow (cfs)\", main = name)\n  lines(x, sapply(x, \\(v) dist_pdf(d, v)), col = \"#b06a3b\", lwd = 2)\n}\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\ncomparison = do.call(rbind, lapply(names(fits), \\(name) {\n  fit = fits[[name]]\n  ll = dist_log_likelihood(distribution(name, fit$posterior_mean), flood)\n  data.frame(\n    Distribution = name,\n    `Parameter 1` = sprintf(\"%s = %.0f\", fit$parameters[1], fit$posterior_mean[1]),\n    `Parameter 2` = sprintf(\"%s = %.0f\", fit$parameters[2], fit$posterior_mean[2]),\n    `Log-likelihood` = round(ll, 2),\n    AIC = round(2 * 2 - 2 * ll, 2),\n    check.names = FALSE\n  )\n}))\ncat(\"Model comparison\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel comparison\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Distribution Parameter 1 Parameter 2 Log-likelihood    AIC\n1       Normal   µ = 12678    σ = 4845        -473.63 951.26\n2     Logistic   ξ = 12633    α = 2826        -474.61 953.23\n3       Gumbel   ξ = 10386    α = 4512        -475.53 955.06\n```\n\n\n:::\n:::\n\n\nThe posterior means match the upstream comparison table (Normal 12678 / 4845,\nLogistic 12633 / 2826, Gumbel 10386 / 4512). The Normal edges out the other two on\nlog-likelihood for this record, and `fit$map_fitness` (the log-likelihood at the\nposterior mode, so higher is better) gives the same ordering.\n\n## Posterior predictive checks\n\nA key part of Bayesian modeling is checking whether the fitted model can reproduce\nthe observed data. Posterior predictive checks draw parameter sets from the\nposterior and generate synthetic replicates from the model at those parameters [2].\nThe upstream picks its replicate indices with an unseeded NumPy generator, so its\nexact numbers are not reproducible; here every draw goes through the seeded core\nRNG, and the Python twin produces bit-identical replicates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The last 1000 recorded draws of chain 1 are the posterior sample we draw from.\nchain1 = fit_norm$chains[[1]]\ntail_rows = chain1[(nrow(chain1) - 999):nrow(chain1), ]\n\n# One predictive value per posterior draw (for summary statistics).\npred = vapply(1:1000, \\(i) {\n  dist_random(distribution(\"Normal\", tail_rows[i, ]), 1, seed = 10000 + i - 1)\n}, numeric(1))\n\n# 50 replicated datasets of the same size as the record (for the ECDF overlay).\nreps = lapply(1:50, \\(i) {\n  dist_random(distribution(\"Normal\", tail_rows[(i - 1) * 20 + 1, ]),\n              length(flood), seed = 20000 + i - 1)\n})\n\nplot(NULL, xlim = range(c(flood, unlist(reps))), ylim = c(0, 1),\n     xlab = \"Annual peak flow (cfs)\", ylab = \"CDF\",\n     main = \"Posterior predictive check: ECDF overlay (50 replicates)\")\nfor (r in reps) {\n  s = sort(r)\n  lines(s, seq_along(s) / length(s), type = \"s\",\n        col = adjustcolor(\"#5b7a8c\", alpha.f = 0.25))\n}\ns = sort(flood)\nlines(s, seq_along(s) / length(s), type = \"s\", col = \"black\", lwd = 2)\nlegend(\"bottomright\", legend = \"Observed\", col = \"black\", lwd = 2, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nppc_summary = data.frame(\n  Statistic = c(\"Mean\", \"Std dev\", \"5th percentile\", \"95th percentile\"),\n  Observed = round(c(mean(flood), sd(flood),\n                     quantile(flood, 0.05), quantile(flood, 0.95)), 2),\n  `Posterior predictive` = round(c(mean(pred), sd(pred),\n                                   quantile(pred, 0.05), quantile(pred, 0.95)), 2),\n  check.names = FALSE, row.names = NULL\n)\ncat(\"Posterior predictive summary\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPosterior predictive summary\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(ppc_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Statistic Observed Posterior predictive\n1            Mean 12665.21             12834.75\n2         Std dev  4709.74              4743.75\n3  5th percentile  5997.50              5357.46\n4 95th percentile 21120.00             20272.62\n```\n\n\n:::\n:::\n\n\n`corehydror` also ships a turnkey version. `posterior_predictive_check()` fits the\nmodel by MCMC (DEMCz by default), draws replicate datasets, and returns Bayesian\np-values for five test statistics. Values near 0.5 mean the observed statistic sits\nin the middle of the predictive distribution; values near 0 or 1 flag misfit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppc = posterior_predictive_check(flood, \"Normal\", seed = 12345)\npvals = data.frame(\n  Statistic = c(\"Mean\", \"Std dev\", \"Skewness\", \"Minimum\", \"Maximum\"),\n  `Bayesian p-value` = c(ppc$mean_p_value, ppc$sd_p_value, ppc$skewness_p_value,\n                         ppc$min_p_value, ppc$max_p_value),\n  check.names = FALSE\n)\nprint(pvals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Statistic Bayesian p-value\n1      Mean            0.497\n2   Std dev            0.495\n3  Skewness            0.347\n4   Minimum            0.448\n5   Maximum            0.590\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Misfit flagged:\", if (ppc$has_misfit) \"yes\" else \"no\", \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMisfit flagged: no \n```\n\n\n:::\n:::\n\n\n## Linear regression with uncertainty\n\nThe upstream notebook also builds a Bayesian linear regression from a hand-written\nlikelihood. `mcmc_sample()` fits named distribution families and does not take a\ncustom likelihood, so that section is not expressible here. Two other pages cover\nthe same ground: [example 20](../20-bayesian-regression/r.qmd) does the regression\nitself, and [example 14](../14-custom-posterior/r.qmd) writes a log-likelihood by\nhand and samples it with `mcmc_posterior()`.\n\n## Non-adaptive vs adaptive samplers\n\nAdaptive MCMC learns the proposal covariance from the chain's own history instead\nof relying on manual tuning [3]. The upstream demonstrates the idea with DEMCzs;\nhere we use ARWMH, the adaptive variant of the same random walk sampler, which\nmakes the comparison like for like. (DEMCz, DEMCzs, HMC, NUTS, and SNIS are also\navailable through `sampler =`.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_arwmh = mcmc_sample(flood, distribution = \"Normal\", sampler = \"ARWMH\", seed = 12345)\n\ncompare = data.frame(\n  Statistic = c(\"Posterior mean (location)\", \"Posterior sd (location)\",\n                \"Posterior mean (scale)\", \"Posterior sd (scale)\",\n                \"Mean acceptance rate\"),\n  RWMH = round(c(fit_norm$posterior_mean[1], fit_norm$posterior_sd[1],\n                 fit_norm$posterior_mean[2], fit_norm$posterior_sd[2],\n                 mean(fit_norm$acceptance_rates)), 4),\n  ARWMH = round(c(fit_arwmh$posterior_mean[1], fit_arwmh$posterior_sd[1],\n                  fit_arwmh$posterior_mean[2], fit_arwmh$posterior_sd[2],\n                  mean(fit_arwmh$acceptance_rates)), 4)\n)\ncat(\"Sampler comparison\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSampler comparison\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(compare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Statistic       RWMH      ARWMH\n1 Posterior mean (location) 12677.6413 12672.0105\n2   Posterior sd (location)   711.6112   694.3654\n3    Posterior mean (scale)  4844.6977  4849.0245\n4      Posterior sd (scale)   515.0695   520.7415\n5      Mean acceptance rate     0.4358     0.3667\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(fit_norm$chains[[1]][, 1], type = \"l\", lwd = 0.4, col = \"#6b7f3f\",\n     xlab = \"Recorded draw\", ylab = \"Mean (cfs)\", main = \"RWMH: trace of the mean (chain 1)\")\nabline(v = 1750, col = \"#8c8c7a\", lty = 2)\nplot(fit_arwmh$chains[[1]][, 1], type = \"l\", lwd = 0.4, col = \"#b06a3b\",\n     xlab = \"Recorded draw\", ylab = \"Mean (cfs)\", main = \"ARWMH: trace of the mean (chain 1)\")\nabline(v = 1750, col = \"#8c8c7a\", lty = 2)\npost_rwmh = unlist(lapply(fit_norm$chains, \\(ch) ch[1751:nrow(ch), 1]))\nhist(post_rwmh, breaks = 40, col = \"#6b7f3f\", border = \"white\",\n     xlab = \"Mean (cfs)\", main = \"RWMH: posterior of the mean\")\npost_arwmh = unlist(lapply(fit_arwmh$chains, \\(ch) ch[1751:nrow(ch), 1]))\nhist(post_arwmh, breaks = 40, col = \"#b06a3b\", border = \"white\",\n     xlab = \"Mean (cfs)\", main = \"ARWMH: posterior of the mean\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\nThe dashed line marks the end of warm-up. Both samplers agree on the posterior.\nARWMH settles at a lower acceptance rate (about 0.37 versus 0.44) because the\nadapted proposal takes larger, better-scaled steps; that is the intended behavior,\nnot a defect.\n\n## Summary\n\nIn this example you:\n\n- Applied Bayesian inference to real flood frequency data with `mcmc_sample()`.\n- Fit Normal, Logistic, and Gumbel distributions by MCMC and compared the\n  posterior parameter estimates.\n- Ran posterior predictive checks, both by hand from the chains and with\n  `posterior_predictive_check()`.\n- Compared a non-adaptive sampler (RWMH) with its adaptive variant (ARWMH).\n\n## References\n\n[1] N. L. Johnson, S. Kotz, and N. Balakrishnan, *Continuous Univariate\nDistributions*, vols. 1-2, 2nd ed. Wiley, 1994.\n\n[2] A. Gelman, J. B. Carlin, H. S. Stern, D. B. Dunson, A. Vehtari, and D. B.\nRubin, *Bayesian Data Analysis*, 3rd ed. CRC Press, 2013.\n\n[3] C. J. F. ter Braak and J. A. Vrugt, \"Differential evolution Markov chain with\nsnooker updater and fewer chains,\" *Statistics and Computing*, vol. 18, no. 4,\npp. 435-446, 2008.\n\n## Reproduction check\n\nThis port uses the upstream's exact settings: the same constraint-based uniform\npriors, RWMH with MAP initialization, serial chains, and the default seed 12345.\nThe C# and C++ samplers replay the identical accept-reject stream; all four RWMH\nand ARWMH acceptance rates match a direct run of the C# library bit for bit. The\ndraws themselves are not bit-identical: the MAP starting point comes from a\ndifferential evolution optimization whose optimum differs from the C# result by\nabout 1e-11 relative (accumulated last-digit floating point drift), and that offset\ncarries through every subsequent draw at about 1e-9 relative. Every digit the\nupstream notebook displays therefore reproduces, and the assertions below pin the\nvalues at that precision. The one place the upstream prints six decimals (its\nsampler-comparison table shows 12677.641313 for the posterior mean of the Normal\nmean parameter) this port gives 12677.641312, so we state the difference rather\nthan assert a wrong number.\n\n| Quantity | Upstream C# | This port | Status |\n|----------|------------:|----------:|--------|\n| Normal posterior mean (mean, sd) | 12677.64 / 4844.70 | same at 2 dp | exact at displayed precision |\n| Normal 90% CI (mean) | (11522.23, 13847.04) | same at 2 dp | exact at displayed precision |\n| Normal 90% CI (sd) | (4073.12, 5735.17) | same at 2 dp | exact at displayed precision |\n| Logistic posterior mean (location, scale) | 12632.66 / 2825.51 | same at 2 dp | exact at displayed precision |\n| Logistic 90% CI (location) | (11438.17, 13801.22) | same at 2 dp | exact at displayed precision |\n| Logistic 90% CI (scale) | (2308.14, 3440.53) | same at 2 dp | exact at displayed precision |\n| Comparison table means (3 families) | 12678/4845, 12633/2826, 10386/4512 | same at 0 dp | exact at displayed precision |\n| RWMH / ARWMH acceptance rates | not printed upstream | match the C# library bit for bit | exact |\n| First recorded Normal draw (chain 1) | not printed upstream | 13287.2303500459 | exact (cross-language) |\n| First posterior predictive draw | recast (unseeded upstream) | 14255.412844410343 | exact (cross-language) |\n| Built-in PPC p-values (mean, sd) | recast (unseeded upstream) | 0.497 / 0.495 | exact (cross-language) |\n\nThe chunk below fails the render if any value drifts. The cross-language rows\nassert the exact values the Python notebook asserts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Upstream: 04_mcmc_bayesian_inference.ipynb, cell 7 output (Normal results table, 2 dp)\nstopifnot(\n  round(fit_norm$posterior_mean[1], 2) == 12677.64,\n  round(fit_norm$posterior_lower_ci[1], 2) == 11522.23,\n  round(fit_norm$posterior_upper_ci[1], 2) == 13847.04,\n  round(fit_norm$posterior_mean[2], 2) == 4844.70,\n  round(fit_norm$posterior_lower_ci[2], 2) == 4073.12,\n  round(fit_norm$posterior_upper_ci[2], 2) == 5735.17\n)\n\n# Upstream: cell 9 output (Logistic results table, 2 dp)\nstopifnot(\n  round(fit_logi$posterior_mean[1], 2) == 12632.66,\n  round(fit_logi$posterior_lower_ci[1], 2) == 11438.17,\n  round(fit_logi$posterior_upper_ci[1], 2) == 13801.22,\n  round(fit_logi$posterior_mean[2], 2) == 2825.51,\n  round(fit_logi$posterior_lower_ci[2], 2) == 2308.14,\n  round(fit_logi$posterior_upper_ci[2], 2) == 3440.53\n)\n\n# Upstream: cell 11 output (model comparison table, 0 dp)\nstopifnot(\n  round(fit_norm$posterior_mean[1]) == 12678,\n  round(fit_norm$posterior_mean[2]) == 4845,\n  round(fit_logi$posterior_mean[1]) == 12633,\n  round(fit_logi$posterior_mean[2]) == 2826,\n  round(fit_gum$posterior_mean[1]) == 10386,\n  round(fit_gum$posterior_mean[2]) == 4512\n)\n\n# Seeded cross-language identity: the Python notebook asserts the same values.\n# The values are bit-exact across R, Python, and C#'s accept-reject stream; the\n# comparisons carry a 1e-15 relative tolerance only because R's decimal parser\n# can land one ulp away from the written literal.\nstopifnot(\n  abs(fit_norm$chains[[1]][1, 1] / 13287.2303500459 - 1) < 1e-15,\n  abs(fit_norm$chains[[1]][1, 2] / 4176.928509438068 - 1) < 1e-15,\n  abs(fit_norm$map_fitness / -473.55840961774754 - 1) < 1e-15,\n  abs(fit_norm$acceptance_rates[1] / 0.4352416666666667 - 1) < 1e-15,\n  abs(fit_arwmh$acceptance_rates[1] / 0.35859166666666664 - 1) < 1e-15,\n  abs(pred[1] / 14255.412844410343 - 1) < 1e-15,\n  ppc$mean_p_value == 0.497,\n  ppc$sd_p_value == 0.495,\n  ppc$has_misfit == 0\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}