{
  "hash": "0b049497ae76240cf5f37c18d6ec8150",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"29. Machine learning\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\nThe Numerics `MachineLearning` layer, which had no R or Python binding until this release: three\nunsupervised methods (k-means, Gaussian mixture models, Jenks natural breaks) and five supervised\nones (decision trees, random forests, k-nearest neighbors, Gaussian naive Bayes, and generalized\nlinear models). This page works through all eight on one regional flood-frequency problem -- the\nkind of regionalization and prediction-in-ungauged-basins task these methods actually get used for\nin hydrology.\n\n## What you'll learn\n\n- How to group catchments into homogeneous regions with `ml_kmeans()` and `ml_gaussian_mixture()`,\n  and what the mixture model tells you that k-means cannot.\n- How `ml_jenks_breaks()` cuts a continuous variable into hazard classes, and why it will happily\n  give you a class of one.\n- How to fit a regional flood-frequency regression with `ml_glm()`, and a Poisson count model with\n  the same verb and a different link.\n- How `ml_random_forest()` compares against that regression out of sample -- including a case\n  where the parametric model wins, and why.\n- How `ml_naive_bayes()` and `ml_knn()` classify catchments above and below a flood threshold.\n- Why every fit on this page is reproducible, and what the seeds are actually doing.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## A regional dataset\n\nThirty-six gauged catchments, each with a drainage area (km^2^), mean annual precipitation (mm),\nmean basin slope (m/m), and mean annual flood (m^3^/s). The values are illustrative rather than\nobserved -- they are generated from a power-law regional relation with a deterministic wobble, so\nthe page's numbers are stable and the R and Python versions define byte-identical inputs -- but\nthe shape and the ranges are those of a real regional study.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea <- c(\n  14.1, 11.4, 10.0, 13.1, 13.7, 10.5,\n  10.7, 13.9, 12.9, 9.9, 11.7, 14.2,\n  165.0, 133.6, 116.7, 152.5, 160.1, 122.4,\n  124.4, 161.7, 150.0, 115.8, 136.2, 165.2,\n  1060.6, 858.6, 750.0, 980.0, 1029.4, 786.6,\n  799.9, 1039.2, 964.3, 744.3, 875.9, 1062.0\n)\nprecip <- c(\n  606, 634, 682, 590, 665, 657,\n  593, 686, 626, 613, 690, 600,\n  928, 971, 1044, 904, 1018, 1006,\n  908, 1051, 958, 938, 1057, 919,\n  1373, 1437, 1545, 1337, 1506, 1488,\n  1343, 1554, 1418, 1388, 1564, 1359\n)\nslope <- c(\n  0.0911, 0.0821, 0.0677, 0.0589, 0.0622, 0.0753,\n  0.0881, 0.0910, 0.0818, 0.0675, 0.0588, 0.0624,\n  0.0389, 0.0350, 0.0289, 0.0251, 0.0266, 0.0321,\n  0.0376, 0.0388, 0.0349, 0.0288, 0.0251, 0.0266,\n  0.0134, 0.0120, 0.0099, 0.0086, 0.0091, 0.0110,\n  0.0129, 0.0133, 0.0120, 0.0099, 0.0086, 0.0092\n)\nflood <- c(\n  2.18, 1.90, 1.79, 1.69, 2.13, 1.80,\n  1.73, 2.47, 2.09, 1.50, 1.98, 1.83,\n  15.67, 15.17, 12.87, 13.48, 15.24, 14.37,\n  12.41, 19.79, 14.91, 12.05, 14.15, 14.68,\n  68.03, 66.88, 55.60, 59.71, 65.53, 63.93,\n  53.11, 88.39, 63.52, 54.04, 60.00, 66.11\n)\nlength(area)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36\n```\n\n\n:::\n:::\n\n\nBasin characteristics span orders of magnitude, so every method on this page works in log10 space.\nThat is not a detail: k-means and k-nearest neighbors measure Euclidean distance, so an untransformed\narea column would swamp a slope column outright.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- cbind(log10(area), log10(precip), log10(slope))\ncolnames(X) <- c(\"log_area\", \"log_precip\", \"log_slope\")\nround(head(X, 3), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     log_area log_precip log_slope\n[1,]   1.1492     2.7825   -1.0405\n[2,]   1.0569     2.8021   -1.0857\n[3,]   1.0000     2.8338   -1.1694\n```\n\n\n:::\n:::\n\n\n## Regionalization: k-means\n\nRegionalization is the task of grouping catchments that behave alike, so a flood estimate can be\ntransferred from gauged to ungauged basins within a group. `ml_kmeans()` does it by minimizing\nwithin-cluster distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm <- ml_kmeans(X, k = 3, seed = 20260827)\ntable(km$labels)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 0  1  2 \n12 12 12 \n```\n\n\n:::\n:::\n\n\n`labels` are **0-based** in both R and Python, matching the library's own indexing -- add 1 before\nusing them to subset an R object. Here the three clusters recover the three catchment size classes\nexactly, twelve each:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(km$means, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]   [,2]    [,3]\n[1,] 2.9565 3.1585 -1.9713\n[2,] 1.0817 2.8033 -1.1370\n[3,] 2.1484 2.9884 -1.5069\n```\n\n\n:::\n:::\n\n\nThe centroids are in log10 space, so the third cluster's `log_area` of 2.96 is a catchment of\nabout 900 km^2^. The fit converged in 2 iterations.\n\n## Regionalization: a Gaussian mixture\n\n`ml_gaussian_mixture()` fits the same kind of grouping but carries a full covariance matrix per\ncomponent rather than only a centre, so it can represent clusters that are elongated or correlated\nrather than spherical. That matters here because area, precipitation and slope co-vary strongly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngmm <- ml_gaussian_mixture(X, k = 3, seed = 20260827)\nround(gmm$weights, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.333333 0.333333 0.333333\n```\n\n\n:::\n:::\n\n\nEqual mixing weights, and the same three groups. What the mixture adds is the covariance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(gmm$sigmas[[3]], 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]     [,2]     [,3]\n[1,]  0.00328 -0.00019  0.00020\n[2,] -0.00019  0.00060 -0.00016\n[3,]  0.00020 -0.00016  0.00496\n```\n\n\n:::\n:::\n\n\nThe off-diagonal terms are the useful part -- within the largest catchments, `log_area` and\n`log_slope` move together (steeper basins in this set are smaller), which k-means has no way to\nexpress.\n\n::: {.callout-warning appearance=\"simple\"}\n`log_likelihood` follows the library's own definition, which omits the multivariate-normal\nnormalizing constant. It is short of the true mixture log-likelihood by\n`nrow(X) * ncol(X) / 2 * log(2 * pi)`. That constant cancels when comparing two fits of the same\ndata, which is what the library uses it for, but do not feed this value straight to AIC.\n:::\n\n## Hazard classes: Jenks natural breaks\n\n`ml_jenks_breaks()` cuts a continuous variable into classes that minimize within-class variance --\nthe standard way to build a legend for a hazard map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njn <- ml_jenks_breaks(flood, n_clusters = 4)\nround(jn$breaks, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2.47 19.79 68.03 88.39\n```\n\n\n:::\n\n```{.r .cell-code}\njn$clusters[, c(\"count\", \"min\", \"max\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     count   min   max\n[1,]    12  1.50  2.47\n[2,]    12 12.05 19.79\n[3,]    11 53.11 68.03\n[4,]     1 88.39 88.39\n```\n\n\n:::\n:::\n\n\nNote the fourth class: a single catchment. Jenks minimizes within-class variance and nothing else,\nso a genuine outlier (the 88.4 m^3^/s catchment) gets a class to itself rather than being absorbed.\nThat is correct behaviour and usually a signal to look at that gauge, not to change `n_clusters`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(jn$gvf, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.987557\n```\n\n\n:::\n:::\n\n\nThe goodness-of-variance-fit measure runs from 0 to 1; 0.988 says four classes explain nearly all\nthe variance in the flood column.\n\n## Regional regression: `ml_glm()`\n\nThe classic regional flood-frequency model is a power law in the basin characteristics, which is a\nlinear model in log space. Split the catchments into a training set and a held-out test set of nine:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain <- c(1:9, 13:21, 25:33)\ntest <- setdiff(seq_along(flood), train)\nfit <- ml_glm(X[train, ], log10(flood[train]))\nround(fit$coefficients, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.01087  0.92989 -0.17801  0.20440\n```\n\n\n:::\n:::\n\n\nRead as a power law, the fitted exponents are 0.930 on area, -0.178 on precipitation and 0.204 on\nslope. Their standard errors say how much to trust each:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(fit$standard_errors, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.87750 0.06683 0.34598 0.10998\n```\n\n\n:::\n\n```{.r .cell-code}\nround(fit$p_values, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.99012 0.00000 0.60691 0.06310\n```\n\n\n:::\n:::\n\n\nOnly the area exponent is well determined -- unsurprising, since area spans two orders of magnitude\nhere while precipitation spans less than one.\n\n## A Poisson model with the same verb\n\n`ml_glm()`'s `link` argument selects the response family as well as the transform, so a count\nresponse needs only a different link. Here the count is the number of days per year each catchment\nexceeds its local flood threshold:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexceedances <- c(\n  1, 2, 3, 1, 2, 2, 1, 3, 2, 1, 3, 1,\n  4, 5, 7, 4, 6, 6, 4, 7, 5, 4, 7, 4,\n  9, 11, 14, 8, 12, 12, 8, 14, 10, 9, 14, 9\n)\nXp <- cbind(log10(precip), log10(area))\npois <- ml_glm(Xp, exceedances, link = \"log\")\nround(pois$coefficients, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.01320 -0.12084  0.92862\n```\n\n\n:::\n\n```{.r .cell-code}\nround(pois$aic, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 142.878\n```\n\n\n:::\n:::\n\n\nThe fitted counts track the observed ones closely:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted_counts <- exp(as.vector(cbind(1, Xp) %*% pois$coefficients))\nround(cor(fitted_counts, exceedances), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.911463\n```\n\n\n:::\n:::\n\n\nThe other three links, `\"logit\"`, `\"probit\"` and `\"complementary_log_log\"`, take a 0/1 response and\nfit the corresponding binomial model.\n\n## Random forest, and when it loses\n\n`ml_random_forest()` grows many trees on bootstrap resamples and reports the spread of their\npredictions as an interval, which is what makes it attractive when the functional form is unknown.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf <- ml_random_forest(X[train, ], log10(flood[train]), newdata = X[test, ],\n                       seed = 20260827, number_of_trees = 200)\nround(head(rf, 3), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      lower median  upper   mean\n[1,] 0.2529 0.2553 0.3201 0.2699\n[2,] 0.2279 0.3284 1.1951 0.5425\n[3,] 0.2776 0.3385 1.1951 0.6306\n```\n\n\n:::\n:::\n\n\nCompare both models out of sample:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse <- function(a, b) sqrt(mean((a - b)^2))\nlm_pred <- as.vector(cbind(1, X[test, ]) %*% fit$coefficients)\nc(\n  glm = rmse(lm_pred, log10(flood[test])),\n  random_forest = rmse(rf[, \"median\"], log10(flood[test]))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          glm random_forest \n   0.04068522    0.06857046 \n```\n\n\n:::\n:::\n\n\nThe regression wins, by a factor of about 1.7 in RMSE. That is the right answer, and it is worth\nbeing explicit about why, because the usual demonstration runs the other way:\n\n- The data really is a power law, so a model that assumes one is using information the forest has\n  to rediscover from 27 training points.\n- A tree predicts by averaging the training responses in a leaf, so it **cannot extrapolate**.\n  Every prediction is inside the range of the training data, which is exactly wrong for a regional\n  relation you want to apply to an ungauged basin outside the gauged range.\n\nReach for the forest when you suspect interactions or thresholds you cannot write down, not as a\ndefault. The same trade-off is why a bare `ml_decision_tree()` is rarely the end of an analysis:\nat its defaults a regression tree recurses until every leaf holds one training observation, so it\nmemorizes the training set.\n\n## Classification: above or below a threshold\n\nRecast the problem as a yes-or-no question -- will this catchment's mean annual flood exceed\n20 m^3^/s? -- and two classifiers answer it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbig <- as.numeric(flood > 20)\nnb <- ml_naive_bayes(X[train, ], big[train], newdata = X[test, ])\nknn_pred <- ml_knn(X[train, ], big[train], newdata = X[test, ], k = 3, regression = FALSE)\n\ndata.frame(truth = big[test], naive_bayes = nb$prediction, knn = knn_pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  truth naive_bayes knn\n1     0           0   0\n2     0           0   0\n3     0           0   0\n4     0           0   0\n5     0           0   0\n6     0           0   0\n7     1           1   1\n8     1           1   1\n9     1           1   1\n```\n\n\n:::\n:::\n\n\nBoth classify all nine held-out catchments correctly. Naive Bayes also reports the per-class\nfeature distributions it fitted, which is often more informative than the predictions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(nb$means, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]   [,2]    [,3]\n[1,] 1.6183 2.8965 -1.3003\n[2,] 2.9598 3.1591 -1.9499\n```\n\n\n:::\n\n```{.r .cell-code}\nround(nb$priors, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6667 0.3333\n```\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n`classes` follows the order the labels **first appear** in the training response, not sorted order,\nand every row of `means`, `standard_deviations` and `priors` is indexed to match.\n:::\n\n`ml_knn()` can also report which training catchments a prediction came from, which is exactly the\n\"donor catchment\" idea regional hydrology uses directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneighbours <- ml_knn(X[train, ], big[train], newdata = X[test, , drop = FALSE],\n                     k = 3, what = \"neighbors\")\nhead(neighbours, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3]\n[1,]    2    5    1\n[2,]    4    3    2\n[3,]    3    4    8\n```\n\n\n:::\n:::\n\n\nThese are **0-based** indices into the training rows, like the cluster labels.\n\n## Reproducibility\n\nEvery method on this page that draws a random number takes a `seed`, and a seeded fit is\nreproducible: repeated calls agree bit for bit, and so do the R and Python versions of this page,\nbecause the entire computation happens in the shared compiled core with the same bit-exact\nMersenne Twister.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidentical(\n  ml_random_forest(X[train, ], log10(flood[train]), newdata = X[test, ],\n                   seed = 20260827, number_of_trees = 200),\n  rf\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nLeave `seed` at its default and the generator is seeded from the clock instead, which is the right\nchoice when you want an honest sense of run-to-run variability and the wrong one when you want a\nresult you can publish.\n\n## Reproduction check\n\nEvery value below is deterministic given the fixed inputs and seeds above, checked at 1e-15\nrelative tolerance against this page's own executed values. The k-means and naive-Bayes paths are\nadditionally pinned against the upstream C# oracles in `fixtures/ml/machine_learning.json`, which\nthe dotnet gate replays against the real library; those fixtures use the iris measurements the C#\ntests use, so what is checked here is that this page's own numbers do not drift.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear <- \\(x, literal, tol = 1e-15) abs(x / literal - 1) < tol\n\nstopifnot(\n  # Clustering recovers the three size classes exactly.\n  identical(as.integer(table(km$labels)), c(12L, 12L, 12L)),\n  km$iterations == 2L,\n  near(km$means[1, 1], 2.9565201679743947),\n  near(km$means[1, 3], -1.9713001801472083),\n\n  # The mixture puts equal weight on the three components and its covariances are symmetric.\n  all(abs(gmm$weights - 1 / 3) < 1e-12),\n  near(gmm$log_likelihood, 238.87583471023325),\n  all(abs(gmm$sigmas[[3]] - t(gmm$sigmas[[3]])) < 1e-12),\n\n  # Jenks, including the single-member top class.\n  near(jn$breaks[4], 88.390000000000001),\n  identical(as.integer(jn$clusters[, \"count\"]), c(12L, 12L, 11L, 1L)),\n  near(jn$gvf, 0.98755725105630288),\n\n  # The regional regression.\n  near(fit$coefficients[2], 0.92989165483884118),\n  near(fit$standard_errors[2], 0.066834707598246085),\n  near(fit$sigma, 0.04726688233226619),\n  fit$n == 27L, fit$df == 23L,\n\n  # The Poisson model.\n  near(pois$coefficients[3], 0.92861744959233672),\n  near(pois$aic, 142.87786000842539),\n  near(cor(fitted_counts, exceedances), 0.91146273024268387),\n\n  # The forest is seeded-reproducible, its interval is ordered, and the regression beats it here.\n  all(rf[, \"lower\"] <= rf[, \"median\"]), all(rf[, \"median\"] <= rf[, \"upper\"]),\n  near(rmse(lm_pred, log10(flood[test])), 0.040685221310457167),\n  near(rmse(rf[, \"median\"], log10(flood[test])), 0.068570459600494127),\n  rmse(lm_pred, log10(flood[test])) < rmse(rf[, \"median\"], log10(flood[test])),\n\n  # Both classifiers get all nine held-out catchments right.\n  identical(as.numeric(nb$prediction), big[test]),\n  identical(as.numeric(knn_pred), big[test]),\n  identical(as.numeric(nb$classes), c(0, 1)),\n  all(neighbours >= 0 & neighbours < 27),\n  identical(dim(neighbours), c(9L, 3L))\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}