// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// analysis.cpp
list ch_analysis_univariate_run_(std::string model_json, doubles dataset, std::string sampler, int iterations, int output_length, double credible_level, int seed, doubles exceedance_probabilities, int thinning_interval);
extern "C" SEXP _corehydror_ch_analysis_univariate_run_(SEXP model_json, SEXP dataset, SEXP sampler, SEXP iterations, SEXP output_length, SEXP credible_level, SEXP seed, SEXP exceedance_probabilities, SEXP thinning_interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_analysis_univariate_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(sampler), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<int>>(output_length), cpp11::as_cpp<cpp11::decay_t<double>>(credible_level), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<doubles>>(exceedance_probabilities), cpp11::as_cpp<cpp11::decay_t<int>>(thinning_interval)));
  END_CPP11
}
// analysis.cpp
list ch_analysis_fit_distributions_(doubles dataset);
extern "C" SEXP _corehydror_ch_analysis_fit_distributions_(SEXP dataset) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_analysis_fit_distributions_(cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset)));
  END_CPP11
}
// analysis.cpp
list ch_analysis_b17c_run_(std::string model_json, doubles dataset, std::string uncertainty_method, int output_length, int seed, double confidence_level, doubles exceedance_probabilities);
extern "C" SEXP _corehydror_ch_analysis_b17c_run_(SEXP model_json, SEXP dataset, SEXP uncertainty_method, SEXP output_length, SEXP seed, SEXP confidence_level, SEXP exceedance_probabilities) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_analysis_b17c_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(uncertainty_method), cpp11::as_cpp<cpp11::decay_t<int>>(output_length), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(confidence_level), cpp11::as_cpp<cpp11::decay_t<doubles>>(exceedance_probabilities)));
  END_CPP11
}
// analysis.cpp
list ch_analysis_family_run_(std::string analysis_type, std::string model_json, doubles dataset, std::string sampler, int iterations, int output_length, double credible_level, int seed, doubles exceedance_probabilities, int thinning_interval, int training_time_steps, int forecasting_time_steps);
extern "C" SEXP _corehydror_ch_analysis_family_run_(SEXP analysis_type, SEXP model_json, SEXP dataset, SEXP sampler, SEXP iterations, SEXP output_length, SEXP credible_level, SEXP seed, SEXP exceedance_probabilities, SEXP thinning_interval, SEXP training_time_steps, SEXP forecasting_time_steps) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_analysis_family_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(analysis_type), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(sampler), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<int>>(output_length), cpp11::as_cpp<cpp11::decay_t<double>>(credible_level), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<doubles>>(exceedance_probabilities), cpp11::as_cpp<cpp11::decay_t<int>>(thinning_interval), cpp11::as_cpp<cpp11::decay_t<int>>(training_time_steps), cpp11::as_cpp<cpp11::decay_t<int>>(forecasting_time_steps)));
  END_CPP11
}
// analysis.cpp
list ch_analysis_diagnostics_run_(std::string model_json, doubles dataset, std::string sampler, int iterations, int output_length, int seed, int thinning_interval, int thin_every);
extern "C" SEXP _corehydror_ch_analysis_diagnostics_run_(SEXP model_json, SEXP dataset, SEXP sampler, SEXP iterations, SEXP output_length, SEXP seed, SEXP thinning_interval, SEXP thin_every) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_analysis_diagnostics_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(sampler), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<int>>(output_length), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(thinning_interval), cpp11::as_cpp<cpp11::decay_t<int>>(thin_every)));
  END_CPP11
}
// analysis.cpp
list ch_analysis_extended_run_(std::string target, std::string construct_json, std::string datasets_json);
extern "C" SEXP _corehydror_ch_analysis_extended_run_(SEXP target, SEXP construct_json, SEXP datasets_json) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_analysis_extended_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<std::string>>(construct_json), cpp11::as_cpp<cpp11::decay_t<std::string>>(datasets_json)));
  END_CPP11
}
// bootstrap.cpp
list ch_bootstrap_run_(std::string model, double mu, double sigma, int sample_size, doubles probabilities, doubles dataset, int replicates, int seed, int max_retries, std::string run, std::string ci_method, double alpha);
extern "C" SEXP _corehydror_ch_bootstrap_run_(SEXP model, SEXP mu, SEXP sigma, SEXP sample_size, SEXP probabilities, SEXP dataset, SEXP replicates, SEXP seed, SEXP max_retries, SEXP run, SEXP ci_method, SEXP alpha) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_bootstrap_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model), cpp11::as_cpp<cpp11::decay_t<double>>(mu), cpp11::as_cpp<cpp11::decay_t<double>>(sigma), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<doubles>>(probabilities), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<int>>(replicates), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(max_retries), cpp11::as_cpp<cpp11::decay_t<std::string>>(run), cpp11::as_cpp<cpp11::decay_t<std::string>>(ci_method), cpp11::as_cpp<cpp11::decay_t<double>>(alpha)));
  END_CPP11
}
// copula.cpp
double ch_cop_val_(std::string type, doubles params, std::string method, doubles args, std::string marg_x_target, doubles marg_x_params, std::string marg_y_target, doubles marg_y_params);
extern "C" SEXP _corehydror_ch_cop_val_(SEXP type, SEXP params, SEXP method, SEXP args, SEXP marg_x_target, SEXP marg_x_params, SEXP marg_y_target, SEXP marg_y_params) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_cop_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(type), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(args), cpp11::as_cpp<cpp11::decay_t<std::string>>(marg_x_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(marg_x_params), cpp11::as_cpp<cpp11::decay_t<std::string>>(marg_y_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(marg_y_params)));
  END_CPP11
}
// data.cpp
list ch_data_frame_summary_(std::string data_frame_json, double plotting_parameter);
extern "C" SEXP _corehydror_ch_data_frame_summary_(SEXP data_frame_json, SEXP plotting_parameter) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_data_frame_summary_(cpp11::as_cpp<cpp11::decay_t<std::string>>(data_frame_json), cpp11::as_cpp<cpp11::decay_t<double>>(plotting_parameter)));
  END_CPP11
}
// data.cpp
list ch_model_log_likelihood_(std::string model_json, doubles dataset, doubles params);
extern "C" SEXP _corehydror_ch_model_log_likelihood_(SEXP model_json, SEXP dataset, SEXP params) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_model_log_likelihood_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<doubles>>(params)));
  END_CPP11
}
// data.cpp
list ch_threshold_diagnostics_(doubles data, std::string method, double u_min, double u_max, int n_thresholds, double confidence_level);
extern "C" SEXP _corehydror_ch_threshold_diagnostics_(SEXP data, SEXP method, SEXP u_min, SEXP u_max, SEXP n_thresholds, SEXP confidence_level) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_threshold_diagnostics_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(u_min), cpp11::as_cpp<cpp11::decay_t<double>>(u_max), cpp11::as_cpp<cpp11::decay_t<int>>(n_thresholds), cpp11::as_cpp<cpp11::decay_t<double>>(confidence_level)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_moments_(std::string target, doubles params);
extern "C" SEXP _corehydror_ch_dist_moments_(SEXP target, SEXP params) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_moments_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params)));
  END_CPP11
}
// dist.cpp
double ch_dist_pdf_(std::string target, doubles params, double x);
extern "C" SEXP _corehydror_ch_dist_pdf_(SEXP target, SEXP params, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_pdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double ch_dist_cdf_(std::string target, doubles params, double x);
extern "C" SEXP _corehydror_ch_dist_cdf_(SEXP target, SEXP params, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_cdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double ch_dist_quantile_(std::string target, doubles params, double p);
extern "C" SEXP _corehydror_ch_dist_quantile_(SEXP target, SEXP params, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_quantile_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<double>>(p)));
  END_CPP11
}
// dist.cpp
bool ch_dist_valid_(std::string target, doubles params);
extern "C" SEXP _corehydror_ch_dist_valid_(SEXP target, SEXP params) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_valid_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_fit_(std::string target, doubles data, std::string method);
extern "C" SEXP _corehydror_ch_dist_fit_(SEXP target, SEXP data, SEXP method) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_fit_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(method)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_linear_moments_(std::string target, doubles params);
extern "C" SEXP _corehydror_ch_dist_linear_moments_(SEXP target, SEXP params) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_linear_moments_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params)));
  END_CPP11
}
// dist.cpp
double ch_dist_gamma_partial_kp_(double skewness, double probability);
extern "C" SEXP _corehydror_ch_dist_gamma_partial_kp_(SEXP skewness, SEXP probability) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_gamma_partial_kp_(cpp11::as_cpp<cpp11::decay_t<double>>(skewness), cpp11::as_cpp<cpp11::decay_t<double>>(probability)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_random_(std::string target, doubles params, int sample_size, int seed);
extern "C" SEXP _corehydror_ch_dist_random_(SEXP target, SEXP params, SEXP sample_size, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_random_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_pdf_v_(std::string target, doubles params, doubles xs);
extern "C" SEXP _corehydror_ch_dist_pdf_v_(SEXP target, SEXP params, SEXP xs) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_pdf_v_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<doubles>>(xs)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_cdf_v_(std::string target, doubles params, doubles xs);
extern "C" SEXP _corehydror_ch_dist_cdf_v_(SEXP target, SEXP params, SEXP xs) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_cdf_v_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<doubles>>(xs)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_quantile_v_(std::string target, doubles params, doubles probs);
extern "C" SEXP _corehydror_ch_dist_quantile_v_(SEXP target, SEXP params, SEXP probs) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_quantile_v_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<doubles>>(probs)));
  END_CPP11
}
// dist.cpp
doubles ch_dist_log_pdf_v_(std::string target, doubles params, doubles xs);
extern "C" SEXP _corehydror_ch_dist_log_pdf_v_(SEXP target, SEXP params, SEXP xs) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_log_pdf_v_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<doubles>>(xs)));
  END_CPP11
}
// dist.cpp
double ch_dist_log_likelihood_(std::string target, doubles params, doubles data);
extern "C" SEXP _corehydror_ch_dist_log_likelihood_(SEXP target, SEXP params, SEXP data) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_log_likelihood_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<doubles>>(data)));
  END_CPP11
}
// dist.cpp
list ch_dist_parameter_names_(std::string target);
extern "C" SEXP _corehydror_ch_dist_parameter_names_(SEXP target) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_parameter_names_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target)));
  END_CPP11
}
// dist.cpp
strings ch_dist_names_();
extern "C" SEXP _corehydror_ch_dist_names_() {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_names_());
  END_CPP11
}
// dist.cpp
bool ch_emp_valid_(doubles x_vals, doubles p_vals, std::string p_transform, bool p_descending);
extern "C" SEXP _corehydror_ch_emp_valid_(SEXP x_vals, SEXP p_vals, SEXP p_transform, SEXP p_descending) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_emp_valid_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x_vals), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_vals), cpp11::as_cpp<cpp11::decay_t<std::string>>(p_transform), cpp11::as_cpp<cpp11::decay_t<bool>>(p_descending)));
  END_CPP11
}
// dist.cpp
bool ch_kde_valid_(doubles data, std::string kernel, double bandwidth, bool bounded_by_data);
extern "C" SEXP _corehydror_ch_kde_valid_(SEXP data, SEXP kernel, SEXP bandwidth, SEXP bounded_by_data) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_kde_valid_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(kernel), cpp11::as_cpp<cpp11::decay_t<double>>(bandwidth), cpp11::as_cpp<cpp11::decay_t<bool>>(bounded_by_data)));
  END_CPP11
}
// dist.cpp
double ch_cr_dependency_change_(strings comp_targets, list comp_params_list, bool minimum_of_rv, std::string dependency, std::string dependency2, list correlation, double x, std::string field, int i, int j);
extern "C" SEXP _corehydror_ch_cr_dependency_change_(SEXP comp_targets, SEXP comp_params_list, SEXP minimum_of_rv, SEXP dependency, SEXP dependency2, SEXP correlation, SEXP x, SEXP field, SEXP i, SEXP j) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_cr_dependency_change_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<bool>>(minimum_of_rv), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency2), cpp11::as_cpp<cpp11::decay_t<list>>(correlation), cpp11::as_cpp<cpp11::decay_t<double>>(x), cpp11::as_cpp<cpp11::decay_t<std::string>>(field), cpp11::as_cpp<cpp11::decay_t<int>>(i), cpp11::as_cpp<cpp11::decay_t<int>>(j)));
  END_CPP11
}
// dist_spec.cpp
list ch_dist_spec_run_(std::string spec_json, std::string method, std::string args_json);
extern "C" SEXP _corehydror_ch_dist_spec_run_(SEXP spec_json, SEXP method, SEXP args_json) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dist_spec_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(spec_json), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<std::string>>(args_json)));
  END_CPP11
}
// dist_spec.cpp
list ch_copula_run_(std::string spec_json, std::string method, std::string args_json);
extern "C" SEXP _corehydror_ch_copula_run_(SEXP spec_json, SEXP method, SEXP args_json) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_copula_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(spec_json), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<std::string>>(args_json)));
  END_CPP11
}
// dist_spec.cpp
list ch_mvdist_run_(std::string spec_json, std::string method, std::string args_json);
extern "C" SEXP _corehydror_ch_mvdist_run_(SEXP spec_json, SEXP method, SEXP args_json) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_mvdist_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(spec_json), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<std::string>>(args_json)));
  END_CPP11
}
// estimation.cpp
list ch_estimation_run_(std::string target, std::string model_json, doubles dataset, std::string optimizer, int sample_size, int seed);
extern "C" SEXP _corehydror_ch_estimation_run_(SEXP target, SEXP model_json, SEXP dataset, SEXP optimizer, SEXP sample_size, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_estimation_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// estimation.cpp
double ch_estimation_bic_(std::string target, std::string model_json, doubles dataset, std::string optimizer, int n);
extern "C" SEXP _corehydror_ch_estimation_bic_(SEXP target, SEXP model_json, SEXP dataset, SEXP optimizer, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_estimation_bic_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// estimation.cpp
list ch_estimation_bayes_run_(std::string model_json, doubles dataset, std::string sampler, int seed, int iterations, int warmup_iterations, int number_of_chains, int thinning_interval, int initial_iterations, int output_length);
extern "C" SEXP _corehydror_ch_estimation_bayes_run_(SEXP model_json, SEXP dataset, SEXP sampler, SEXP seed, SEXP iterations, SEXP warmup_iterations, SEXP number_of_chains, SEXP thinning_interval, SEXP initial_iterations, SEXP output_length) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_estimation_bayes_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(sampler), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<int>>(warmup_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(number_of_chains), cpp11::as_cpp<cpp11::decay_t<int>>(thinning_interval), cpp11::as_cpp<cpp11::decay_t<int>>(initial_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(output_length)));
  END_CPP11
}
// estimation.cpp
list ch_model_data_frame_(std::string model_json, doubles dataset);
extern "C" SEXP _corehydror_ch_model_data_frame_(SEXP model_json, SEXP dataset) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_model_data_frame_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset)));
  END_CPP11
}
// estimation.cpp
list ch_model_validate_(std::string model_json, doubles dataset);
extern "C" SEXP _corehydror_ch_model_validate_(SEXP model_json, SEXP dataset) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_model_validate_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset)));
  END_CPP11
}
// estimation.cpp
doubles ch_model_simulate_(std::string model_json, doubles dataset, int sample_size, int seed);
extern "C" SEXP _corehydror_ch_model_simulate_(SEXP model_json, SEXP dataset, SEXP sample_size, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_model_simulate_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// estimation.cpp
list ch_estimation_gmm_run_(std::string model_json, doubles dataset, std::string strategy, std::string optimizer, int max_gmm_iterations, int sample_size, int seed);
extern "C" SEXP _corehydror_ch_estimation_gmm_run_(SEXP model_json, SEXP dataset, SEXP strategy, SEXP optimizer, SEXP max_gmm_iterations, SEXP sample_size, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_estimation_gmm_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(strategy), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer), cpp11::as_cpp<cpp11::decay_t<int>>(max_gmm_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// estimation.cpp
double ch_estimation_gmm_qvar_(std::string model_json, doubles dataset, std::string strategy, std::string optimizer, int max_gmm_iterations, double aep);
extern "C" SEXP _corehydror_ch_estimation_gmm_qvar_(SEXP model_json, SEXP dataset, SEXP strategy, SEXP optimizer, SEXP max_gmm_iterations, SEXP aep) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_estimation_gmm_qvar_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(strategy), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer), cpp11::as_cpp<cpp11::decay_t<int>>(max_gmm_iterations), cpp11::as_cpp<cpp11::decay_t<double>>(aep)));
  END_CPP11
}
// estimation.cpp
list ch_fit_run_(std::string target, std::string construct_json, doubles dataset);
extern "C" SEXP _corehydror_ch_fit_run_(SEXP target, SEXP construct_json, SEXP dataset) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_fit_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<std::string>>(construct_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset)));
  END_CPP11
}
// estimation.cpp
list ch_fit_diagnostics_(std::string target, std::string construct_json, doubles dataset);
extern "C" SEXP _corehydror_ch_fit_diagnostics_(SEXP target, SEXP construct_json, SEXP dataset) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_fit_diagnostics_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<std::string>>(construct_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset)));
  END_CPP11
}
// estimation.cpp
double ch_fit_quantile_variance_(std::string construct_json, doubles dataset, double aep);
extern "C" SEXP _corehydror_ch_fit_quantile_variance_(SEXP construct_json, SEXP dataset, SEXP aep) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_fit_quantile_variance_(cpp11::as_cpp<cpp11::decay_t<std::string>>(construct_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<double>>(aep)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_pdf_(doubles x, double location, double scale, double shape);
extern "C" SEXP _corehydror_ch_gev_pdf_(SEXP x, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_pdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_cdf_(doubles x, double location, double scale, double shape);
extern "C" SEXP _corehydror_ch_gev_cdf_(SEXP x, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_cdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_quantile_(doubles p, double location, double scale, double shape);
extern "C" SEXP _corehydror_ch_gev_quantile_(SEXP p, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_quantile_(cpp11::as_cpp<cpp11::decay_t<doubles>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_moments_(double location, double scale, double shape);
extern "C" SEXP _corehydror_ch_gev_moments_(SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_moments_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
bool ch_gev_valid_(double location, double scale, double shape);
extern "C" SEXP _corehydror_ch_gev_valid_(SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_valid_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_fit_(doubles data, std::string method);
extern "C" SEXP _corehydror_ch_gev_fit_(SEXP data, SEXP method) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_fit_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(method)));
  END_CPP11
}
// gev.cpp
double ch_gev_quantile_variance_(double p, double location, double scale, double shape, int sample_size);
extern "C" SEXP _corehydror_ch_gev_quantile_variance_(SEXP p, SEXP location, SEXP scale, SEXP shape, SEXP sample_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_quantile_variance_(cpp11::as_cpp<cpp11::decay_t<double>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_linear_moments_(double location, double scale, double shape);
extern "C" SEXP _corehydror_ch_gev_linear_moments_(SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_linear_moments_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_quantile_gradient_(double p, double location, double scale, double shape);
extern "C" SEXP _corehydror_ch_gev_quantile_gradient_(SEXP p, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_quantile_gradient_(cpp11::as_cpp<cpp11::decay_t<double>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles ch_gev_parameter_covariance_(double location, double scale, double shape, int sample_size);
extern "C" SEXP _corehydror_ch_gev_parameter_covariance_(SEXP location, SEXP scale, SEXP shape, SEXP sample_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_gev_parameter_covariance_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size)));
  END_CPP11
}
// mcmc.cpp
list ch_mcmc_run_(std::string sampler_type, std::string model_name, std::string family, doubles dataset, list settings);
extern "C" SEXP _corehydror_ch_mcmc_run_(SEXP sampler_type, SEXP model_name, SEXP family, SEXP dataset, SEXP settings) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_mcmc_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(sampler_type), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_name), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<list>>(settings)));
  END_CPP11
}
// mvd.cpp
double ch_dirichlet_val_(std::string method, doubles alpha, doubles args);
extern "C" SEXP _corehydror_ch_dirichlet_val_(SEXP method, SEXP alpha, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_dirichlet_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(alpha), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// mvd.cpp
double ch_bve_cdf_(std::string method, doubles x1, doubles x2, doubles p_flat, int nrow, strings transforms, doubles args);
extern "C" SEXP _corehydror_ch_bve_cdf_(SEXP method, SEXP x1, SEXP x2, SEXP p_flat, SEXP nrow, SEXP transforms, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_bve_cdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(x1), cpp11::as_cpp<cpp11::decay_t<doubles>>(x2), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_flat), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<strings>>(transforms), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// mvd.cpp
double ch_bve_cdf_after_set_parameters_(doubles x1, doubles x2, doubles p_flat, int nrow, strings transforms, doubles x1_new, doubles x2_new, doubles p_new_flat, int nrow_new, double x1_eval, double x2_eval);
extern "C" SEXP _corehydror_ch_bve_cdf_after_set_parameters_(SEXP x1, SEXP x2, SEXP p_flat, SEXP nrow, SEXP transforms, SEXP x1_new, SEXP x2_new, SEXP p_new_flat, SEXP nrow_new, SEXP x1_eval, SEXP x2_eval) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_bve_cdf_after_set_parameters_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x1), cpp11::as_cpp<cpp11::decay_t<doubles>>(x2), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_flat), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<strings>>(transforms), cpp11::as_cpp<cpp11::decay_t<doubles>>(x1_new), cpp11::as_cpp<cpp11::decay_t<doubles>>(x2_new), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_new_flat), cpp11::as_cpp<cpp11::decay_t<int>>(nrow_new), cpp11::as_cpp<cpp11::decay_t<double>>(x1_eval), cpp11::as_cpp<cpp11::decay_t<double>>(x2_eval)));
  END_CPP11
}
// mvd.cpp
double ch_mvn_val_(std::string method, doubles mean, doubles cov_flat, doubles args);
extern "C" SEXP _corehydror_ch_mvn_val_(SEXP method, SEXP mean, SEXP cov_flat, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_mvn_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(mean), cpp11::as_cpp<cpp11::decay_t<doubles>>(cov_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// mvd.cpp
doubles ch_mvn_cdf_seq_(doubles mean, doubles cov_flat, int seed, doubles xs_flat, int k);
extern "C" SEXP _corehydror_ch_mvn_cdf_seq_(SEXP mean, SEXP cov_flat, SEXP seed, SEXP xs_flat, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_mvn_cdf_seq_(cpp11::as_cpp<cpp11::decay_t<doubles>>(mean), cpp11::as_cpp<cpp11::decay_t<doubles>>(cov_flat), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<doubles>>(xs_flat), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// mvd.cpp
doubles ch_mvn_mvndst_seq_(int n_dim, int seed, doubles lower_flat, doubles upper_flat, integers infin_flat, doubles correl_flat, integers maxpts_v, doubles abseps_v, doubles releps_v, int k);
extern "C" SEXP _corehydror_ch_mvn_mvndst_seq_(SEXP n_dim, SEXP seed, SEXP lower_flat, SEXP upper_flat, SEXP infin_flat, SEXP correl_flat, SEXP maxpts_v, SEXP abseps_v, SEXP releps_v, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_mvn_mvndst_seq_(cpp11::as_cpp<cpp11::decay_t<int>>(n_dim), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<doubles>>(lower_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(upper_flat), cpp11::as_cpp<cpp11::decay_t<integers>>(infin_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(correl_flat), cpp11::as_cpp<cpp11::decay_t<integers>>(maxpts_v), cpp11::as_cpp<cpp11::decay_t<doubles>>(abseps_v), cpp11::as_cpp<cpp11::decay_t<doubles>>(releps_v), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// mvd.cpp
double ch_mvt_val_(std::string method, double df, doubles location, doubles scale_flat, doubles args);
extern "C" SEXP _corehydror_ch_mvt_val_(SEXP method, SEXP df, SEXP location, SEXP scale_flat, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_mvt_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(df), cpp11::as_cpp<cpp11::decay_t<doubles>>(location), cpp11::as_cpp<cpp11::decay_t<doubles>>(scale_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// stats.cpp
int ch_mgbt_test_(doubles x);
extern "C" SEXP _corehydror_ch_mgbt_test_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_mgbt_test_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x)));
  END_CPP11
}
// stats.cpp
double ch_box_cox_lambda_(doubles values);
extern "C" SEXP _corehydror_ch_box_cox_lambda_(SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_box_cox_lambda_(cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// stats.cpp
doubles ch_box_cox_(doubles values, double lambda);
extern "C" SEXP _corehydror_ch_box_cox_(SEXP values, SEXP lambda) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_box_cox_(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<double>>(lambda)));
  END_CPP11
}
// stats.cpp
doubles ch_box_cox_inverse_(doubles values, double lambda);
extern "C" SEXP _corehydror_ch_box_cox_inverse_(SEXP values, SEXP lambda) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_box_cox_inverse_(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<double>>(lambda)));
  END_CPP11
}
// stats.cpp
double ch_yeo_johnson_lambda_(doubles values);
extern "C" SEXP _corehydror_ch_yeo_johnson_lambda_(SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_yeo_johnson_lambda_(cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// stats.cpp
doubles ch_yeo_johnson_(doubles values, double lambda);
extern "C" SEXP _corehydror_ch_yeo_johnson_(SEXP values, SEXP lambda) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_yeo_johnson_(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<double>>(lambda)));
  END_CPP11
}
// stats.cpp
doubles ch_yeo_johnson_inverse_(doubles values, double lambda);
extern "C" SEXP _corehydror_ch_yeo_johnson_inverse_(SEXP values, SEXP lambda) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_yeo_johnson_inverse_(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<double>>(lambda)));
  END_CPP11
}
// stats.cpp
doubles ch_plotting_positions_(int n, std::string method);
extern "C" SEXP _corehydror_ch_plotting_positions_(SEXP n, SEXP method) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_plotting_positions_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<std::string>>(method)));
  END_CPP11
}
// stats.cpp
doubles ch_plotting_positions_alpha_(int n, double alpha);
extern "C" SEXP _corehydror_ch_plotting_positions_alpha_(SEXP n, SEXP alpha) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_plotting_positions_alpha_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<double>>(alpha)));
  END_CPP11
}
// stats.cpp
doubles ch_latin_hypercube_(int sample_size, int dimension, int seed, bool median);
extern "C" SEXP _corehydror_ch_latin_hypercube_(SEXP sample_size, SEXP dimension, SEXP seed, SEXP median) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_latin_hypercube_(cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<int>>(dimension), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<bool>>(median)));
  END_CPP11
}
// toolbox.cpp
list ch_toolbox_run_(std::string group, std::string method, list data, std::string options_json);
extern "C" SEXP _corehydror_ch_toolbox_run_(SEXP group, SEXP method, SEXP data, SEXP options_json) {
  BEGIN_CPP11
    return cpp11::as_sexp(ch_toolbox_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(group), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<list>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(options_json)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_corehydror_ch_analysis_b17c_run_",            (DL_FUNC) &_corehydror_ch_analysis_b17c_run_,             7},
    {"_corehydror_ch_analysis_diagnostics_run_",     (DL_FUNC) &_corehydror_ch_analysis_diagnostics_run_,      8},
    {"_corehydror_ch_analysis_extended_run_",        (DL_FUNC) &_corehydror_ch_analysis_extended_run_,         3},
    {"_corehydror_ch_analysis_family_run_",          (DL_FUNC) &_corehydror_ch_analysis_family_run_,          12},
    {"_corehydror_ch_analysis_fit_distributions_",   (DL_FUNC) &_corehydror_ch_analysis_fit_distributions_,    1},
    {"_corehydror_ch_analysis_univariate_run_",      (DL_FUNC) &_corehydror_ch_analysis_univariate_run_,       9},
    {"_corehydror_ch_bootstrap_run_",                (DL_FUNC) &_corehydror_ch_bootstrap_run_,                12},
    {"_corehydror_ch_box_cox_",                      (DL_FUNC) &_corehydror_ch_box_cox_,                       2},
    {"_corehydror_ch_box_cox_inverse_",              (DL_FUNC) &_corehydror_ch_box_cox_inverse_,               2},
    {"_corehydror_ch_box_cox_lambda_",               (DL_FUNC) &_corehydror_ch_box_cox_lambda_,                1},
    {"_corehydror_ch_bve_cdf_",                      (DL_FUNC) &_corehydror_ch_bve_cdf_,                       7},
    {"_corehydror_ch_bve_cdf_after_set_parameters_", (DL_FUNC) &_corehydror_ch_bve_cdf_after_set_parameters_, 11},
    {"_corehydror_ch_cop_val_",                      (DL_FUNC) &_corehydror_ch_cop_val_,                       8},
    {"_corehydror_ch_copula_run_",                   (DL_FUNC) &_corehydror_ch_copula_run_,                    3},
    {"_corehydror_ch_cr_dependency_change_",         (DL_FUNC) &_corehydror_ch_cr_dependency_change_,         10},
    {"_corehydror_ch_data_frame_summary_",           (DL_FUNC) &_corehydror_ch_data_frame_summary_,            2},
    {"_corehydror_ch_dirichlet_val_",                (DL_FUNC) &_corehydror_ch_dirichlet_val_,                 3},
    {"_corehydror_ch_dist_cdf_",                     (DL_FUNC) &_corehydror_ch_dist_cdf_,                      3},
    {"_corehydror_ch_dist_cdf_v_",                   (DL_FUNC) &_corehydror_ch_dist_cdf_v_,                    3},
    {"_corehydror_ch_dist_fit_",                     (DL_FUNC) &_corehydror_ch_dist_fit_,                      3},
    {"_corehydror_ch_dist_gamma_partial_kp_",        (DL_FUNC) &_corehydror_ch_dist_gamma_partial_kp_,         2},
    {"_corehydror_ch_dist_linear_moments_",          (DL_FUNC) &_corehydror_ch_dist_linear_moments_,           2},
    {"_corehydror_ch_dist_log_likelihood_",          (DL_FUNC) &_corehydror_ch_dist_log_likelihood_,           3},
    {"_corehydror_ch_dist_log_pdf_v_",               (DL_FUNC) &_corehydror_ch_dist_log_pdf_v_,                3},
    {"_corehydror_ch_dist_moments_",                 (DL_FUNC) &_corehydror_ch_dist_moments_,                  2},
    {"_corehydror_ch_dist_names_",                   (DL_FUNC) &_corehydror_ch_dist_names_,                    0},
    {"_corehydror_ch_dist_parameter_names_",         (DL_FUNC) &_corehydror_ch_dist_parameter_names_,          1},
    {"_corehydror_ch_dist_pdf_",                     (DL_FUNC) &_corehydror_ch_dist_pdf_,                      3},
    {"_corehydror_ch_dist_pdf_v_",                   (DL_FUNC) &_corehydror_ch_dist_pdf_v_,                    3},
    {"_corehydror_ch_dist_quantile_",                (DL_FUNC) &_corehydror_ch_dist_quantile_,                 3},
    {"_corehydror_ch_dist_quantile_v_",              (DL_FUNC) &_corehydror_ch_dist_quantile_v_,               3},
    {"_corehydror_ch_dist_random_",                  (DL_FUNC) &_corehydror_ch_dist_random_,                   4},
    {"_corehydror_ch_dist_spec_run_",                (DL_FUNC) &_corehydror_ch_dist_spec_run_,                 3},
    {"_corehydror_ch_dist_valid_",                   (DL_FUNC) &_corehydror_ch_dist_valid_,                    2},
    {"_corehydror_ch_emp_valid_",                    (DL_FUNC) &_corehydror_ch_emp_valid_,                     4},
    {"_corehydror_ch_estimation_bayes_run_",         (DL_FUNC) &_corehydror_ch_estimation_bayes_run_,         10},
    {"_corehydror_ch_estimation_bic_",               (DL_FUNC) &_corehydror_ch_estimation_bic_,                5},
    {"_corehydror_ch_estimation_gmm_qvar_",          (DL_FUNC) &_corehydror_ch_estimation_gmm_qvar_,           6},
    {"_corehydror_ch_estimation_gmm_run_",           (DL_FUNC) &_corehydror_ch_estimation_gmm_run_,            7},
    {"_corehydror_ch_estimation_run_",               (DL_FUNC) &_corehydror_ch_estimation_run_,                6},
    {"_corehydror_ch_fit_diagnostics_",              (DL_FUNC) &_corehydror_ch_fit_diagnostics_,               3},
    {"_corehydror_ch_fit_quantile_variance_",        (DL_FUNC) &_corehydror_ch_fit_quantile_variance_,         3},
    {"_corehydror_ch_fit_run_",                      (DL_FUNC) &_corehydror_ch_fit_run_,                       3},
    {"_corehydror_ch_gev_cdf_",                      (DL_FUNC) &_corehydror_ch_gev_cdf_,                       4},
    {"_corehydror_ch_gev_fit_",                      (DL_FUNC) &_corehydror_ch_gev_fit_,                       2},
    {"_corehydror_ch_gev_linear_moments_",           (DL_FUNC) &_corehydror_ch_gev_linear_moments_,            3},
    {"_corehydror_ch_gev_moments_",                  (DL_FUNC) &_corehydror_ch_gev_moments_,                   3},
    {"_corehydror_ch_gev_parameter_covariance_",     (DL_FUNC) &_corehydror_ch_gev_parameter_covariance_,      4},
    {"_corehydror_ch_gev_pdf_",                      (DL_FUNC) &_corehydror_ch_gev_pdf_,                       4},
    {"_corehydror_ch_gev_quantile_",                 (DL_FUNC) &_corehydror_ch_gev_quantile_,                  4},
    {"_corehydror_ch_gev_quantile_gradient_",        (DL_FUNC) &_corehydror_ch_gev_quantile_gradient_,         4},
    {"_corehydror_ch_gev_quantile_variance_",        (DL_FUNC) &_corehydror_ch_gev_quantile_variance_,         5},
    {"_corehydror_ch_gev_valid_",                    (DL_FUNC) &_corehydror_ch_gev_valid_,                     3},
    {"_corehydror_ch_kde_valid_",                    (DL_FUNC) &_corehydror_ch_kde_valid_,                     4},
    {"_corehydror_ch_latin_hypercube_",              (DL_FUNC) &_corehydror_ch_latin_hypercube_,               4},
    {"_corehydror_ch_mcmc_run_",                     (DL_FUNC) &_corehydror_ch_mcmc_run_,                      5},
    {"_corehydror_ch_mgbt_test_",                    (DL_FUNC) &_corehydror_ch_mgbt_test_,                     1},
    {"_corehydror_ch_model_data_frame_",             (DL_FUNC) &_corehydror_ch_model_data_frame_,              2},
    {"_corehydror_ch_model_log_likelihood_",         (DL_FUNC) &_corehydror_ch_model_log_likelihood_,          3},
    {"_corehydror_ch_model_simulate_",               (DL_FUNC) &_corehydror_ch_model_simulate_,                4},
    {"_corehydror_ch_model_validate_",               (DL_FUNC) &_corehydror_ch_model_validate_,                2},
    {"_corehydror_ch_mvdist_run_",                   (DL_FUNC) &_corehydror_ch_mvdist_run_,                    3},
    {"_corehydror_ch_mvn_cdf_seq_",                  (DL_FUNC) &_corehydror_ch_mvn_cdf_seq_,                   5},
    {"_corehydror_ch_mvn_mvndst_seq_",               (DL_FUNC) &_corehydror_ch_mvn_mvndst_seq_,               10},
    {"_corehydror_ch_mvn_val_",                      (DL_FUNC) &_corehydror_ch_mvn_val_,                       4},
    {"_corehydror_ch_mvt_val_",                      (DL_FUNC) &_corehydror_ch_mvt_val_,                       5},
    {"_corehydror_ch_plotting_positions_",           (DL_FUNC) &_corehydror_ch_plotting_positions_,            2},
    {"_corehydror_ch_plotting_positions_alpha_",     (DL_FUNC) &_corehydror_ch_plotting_positions_alpha_,      2},
    {"_corehydror_ch_threshold_diagnostics_",        (DL_FUNC) &_corehydror_ch_threshold_diagnostics_,         6},
    {"_corehydror_ch_toolbox_run_",                  (DL_FUNC) &_corehydror_ch_toolbox_run_,                   4},
    {"_corehydror_ch_yeo_johnson_",                  (DL_FUNC) &_corehydror_ch_yeo_johnson_,                   2},
    {"_corehydror_ch_yeo_johnson_inverse_",          (DL_FUNC) &_corehydror_ch_yeo_johnson_inverse_,           2},
    {"_corehydror_ch_yeo_johnson_lambda_",           (DL_FUNC) &_corehydror_ch_yeo_johnson_lambda_,            1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_corehydror(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
