{
  "hash": "9ad1a0b2bc93d6601e1ee75401570354",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"25. Estimation methods\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\n`bulletin17c_analysis()` and `univariate_analysis()` are convenience wrappers: pick a model,\npick a method, get a frequency curve. Underneath them sits a smaller estimation layer that fits\na model directly and hands back the fit itself: `fit_mle()`, `fit_map()`, `fit_bayesian()`, and\n`fit_gmm()`. This example fits the same model three different ways over the same censored record\nas [example 23](../23-censored-flood-frequency/r.qmd), and compares what each estimator returns.\n\n## What you'll learn\n\n- Fit one model three ways, by maximum likelihood, maximum a posteriori, and a Bayesian MCMC\n  chain, and see how an informative prior moves the maximum a posteriori estimate.\n- Compare AIC, BIC, and DIC across estimators, and why a method-of-moments fit like `fit_gmm()`\n  reports none of the three.\n- Set profile-likelihood confidence intervals against posterior credible intervals.\n- Read a Bayesian fit's R-hat and effective sample size.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## The censored record\n\nThe same gauge record and historical information as example 23: forty-eight years of annual\npeaks, two pre-gauge floods known only within a range, and a fifty-year perception threshold\nthat makes those two floods usable at all. See that example for the full derivation; here the\nframe is assembled directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_flows <- c(\n  6290, 2700, 13100, 16900, 14600, 9600, 7740, 8490, 8130, 12000,\n  17200, 15000, 12400, 6960, 6500, 5840, 10400, 18800, 21400, 22600,\n  14200, 11000, 12800, 15700, 4740, 6950, 11800, 12100, 20600, 14600,\n  14600, 8900, 10600, 14200, 14100, 14100, 12500, 7530, 13400, 17600,\n  13400, 19200, 16900, 15500, 14500, 21900, 10400, 7460\n)\nn <- length(peak_flows)\n\nhistorical <- data.frame(\n  index = c(n, n + 1),\n  lower = c(30000, 26000),\n  value = c(34000, 29000),\n  upper = c(38000, 32000)\n)\nperception <- data.frame(\n  start_index = n, end_index = n + 49, value = 25000, number_above = 2\n)\nflood_data <- analysis_data(exact = peak_flows, interval = historical, threshold = perception)\n```\n:::\n\n\n## An informative prior on skew\n\n`model_univariate()` defaults to flat priors within each parameter's bounds, and the mode of a\nflat-times-likelihood posterior is just the likelihood's own mode. A `fit_map()` fit with no\nexplicit prior would then land exactly on `fit_mle()`'s estimate, leaving nothing to compare.\nLog-Pearson III's skew is exactly where a Bulletin 17C analysis leans on outside\ninformation (a regional skew estimate, in practice), so this model gives it a weakly informative\nprior instead of a flat one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskew_prior <- distribution(\"Normal\", c(-0.3, 0.5))\nm <- model_univariate(\n  \"LogPearsonTypeIII\", flood_data,\n  parameters = model_parameter(\"skew\", prior = skew_prior)\n)\n```\n:::\n\n\n## Three fits of the same model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf_mle <- fit_mle(m)\nf_map <- fit_map(m)\nf_bayes <- fit_bayesian(\n  m,\n  sampler = \"DEMCzs\", iterations = 400, output_length = 2000,\n  seed = 20250811, thinning_interval = 1\n)\n\nparams <- rbind(MLE = coef(f_mle), MAP = coef(f_map), Bayesian = coef(f_bayes))\nround(params, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Mean (of log) (µ) Std Dev (of log) (σ) Skew (of log) (γ)\nMLE                 4.0843               0.1991           -0.4657\nMAP                 4.0852               0.1962           -0.4189\nBayesian            4.0770               0.2063           -0.4263\n```\n\n\n:::\n:::\n\n\nEvery `corehydro_fit`, regardless of method, carries a `converged` flag and a `status` string.\nHere both are structurally `TRUE`/`\"Success\"`: the estimator throws on a genuine failure to\nestimate rather than handing back a failed fit, so these two fields record that the run\ncompleted, not that it necessarily found a good optimum.\n\nThe skew estimate moves from -0.4657 at MLE toward the prior's mean of -0.3 once a prior is in\nplay: -0.4189 at MAP, and -0.4263 for the Bayesian fit's own point estimate (a mode-like point\ntracked by the sampler, not the posterior mean reported below in `$summary`). Both parameter\npriors and censored data pull in the same direction here, pulling the log-Pearson III skew\naway from the strongly negative value example 23 found for the systematic-only record.\n\n## Goodness of fit: AIC, BIC, DIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngof <- data.frame(\n  method = c(\"MLE\", \"MAP\", \"Bayesian\"),\n  aic = c(f_mle$aic, f_map$aic, f_bayes$aic),\n  bic = c(f_mle$bic, f_map$bic, f_bayes$bic),\n  dic = c(NA, NA, f_bayes$dic)\n)\ngof\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    method      aic      bic      dic\n1      MLE 990.1401 995.9356       NA\n2      MAP 992.3973 998.1928       NA\n3 Bayesian 992.6791 998.4746 989.7603\n```\n\n\n:::\n:::\n\n\nAIC and BIC are defined at a single point estimate, so all three fits report them; DIC is built\nfrom the posterior draws themselves and only `fit_bayesian()` has those, hence the two `NA`s.\nMAP's AIC is worse than MLE's: the prior trades off some data likelihood at its point estimate in\nexchange for consistency with the outside skew information, and AIC has no way to credit that\ntrade. It only sees the likelihood. DIC, which does account for the posterior's effective\ncomplexity, is close to but not equal to the Bayesian fit's own AIC/BIC.\n\nNot shown in this table: a `fit_gmm()` fit's `aic`/`bic`/log-likelihood are reported as `NA` too,\nfor a different reason. GMM is method-of-moments; it never had a likelihood surface to compute\nthem from in the first place, so they are not \"missing\" the way a `NULL` DIC on an MLE fit is.\nThey are structurally absent. See the GMM section below.\n\n## Profile intervals versus credible intervals\n\n`confint()` dispatches on the fit's own method: MLE and MAP get profile-likelihood confidence\nintervals, and a Bayesian fit gets its posterior credible interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci <- rbind(\n  `MLE (profile)` = confint(f_mle)[\"Skew (of log) (γ)\", ],\n  `MAP (profile)` = confint(f_map)[\"Skew (of log) (γ)\", ],\n  `Bayesian (credible)` = confint(f_bayes)[\"Skew (of log) (γ)\", ]\n)\nround(ci, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      lower  upper\nMLE (profile)       -0.8216 0.0835\nMAP (profile)       -0.7725 0.0531\nBayesian (credible) -0.8679 0.0730\n```\n\n\n:::\n:::\n\n\nThe Bayesian credible interval turns out to be the widest of the three, about 4% wider than the\nMLE profile interval, and MAP's is the narrowest, pulled in by the same prior that shifted its\npoint estimate. All three straddle zero: even with the historical record and, for MAP, an\ninformative prior, this fit cannot rule out a skew near zero. That ordering is not a sign the\nBayesian fit is less certain than the others. A profile interval comes from the curvature of the\nlikelihood or posterior around a single point estimate, while a credible interval is read\ndirectly off the spread of the sampled posterior draws, and the two need not land on the same\nwidth. They also answer different questions to begin with: a probability statement about the\nparameter given the data and prior, versus a repeated-sampling statement about the estimator.\nClose numeric agreement between them, in either direction, was never guaranteed.\n\n## R-hat and effective sample size\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(f_bayes$summary[, c(\"rhat\", \"ess\")], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      rhat     ess\nMean (of log) (µ)    1.011 126.176\nStd Dev (of log) (σ) 1.127 142.537\nSkew (of log) (γ)    1.083 120.766\n```\n\n\n:::\n:::\n\n\nR-hat compares between-chain and within-chain variance across the four parallel chains\n`fit_bayesian()` ran; values near 1 indicate the chains agree on where the posterior mass is.\nEffective sample size (ESS) is smaller than the raw `output_length = 2000` retained draws because\nconsecutive MCMC draws are autocorrelated. An ESS in the low hundreds means each parameter's\nposterior is effectively summarized by that many independent draws, not 2000.\n\n## A different estimator entirely: GMM\n\n`fit_gmm()` only fits a `model_bulletin17c()` model, since `IGMMModel` has exactly one\nimplementation, so it is not a fourth entry in the table above. It is, however, the estimator\n`bulletin17c_analysis()` itself builds on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf_gmm <- fit_gmm(model_bulletin17c(flood_data))\ngmm_coef <- setNames(coef(f_gmm), c(\"mean (log10)\", \"sd (log10)\", \"skew\"))\nround(gmm_coef, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean (log10)   sd (log10)         skew \n      4.0862       0.2032      -0.6863 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\n  \"j-statistic %.4f, p-value %s (always NA: Bulletin 17C is always just-identified)\\n\",\n  f_gmm$j_stat, format(f_gmm$j_stat_pval)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nj-statistic 3.6036, p-value NA (always NA: Bulletin 17C is always just-identified)\n```\n\n\n:::\n:::\n\n\nThe J-statistic is GMM's own goodness-of-fit diagnostic, an overidentification test. It is the\nmethod-of-moments analogue of a likelihood-based AIC/BIC/DIC, not a value on the same scale as\nany of them, and Bulletin 17C's moment conditions exactly match its parameter count, so there is\nno over-identified case here for the p-value to describe.\n\n`quantile_variance()` gives the delta-method variance of a fitted quantile off a GMM fit's\nsandwich covariance, useful directly without going through `bulletin17c_analysis()`'s full\nuncertainty-quantification machinery:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile_variance(f_gmm, 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004328764\n```\n\n\n:::\n:::\n\n\n## Diagnostics off the MAP fit\n\n`fit_diagnostics()` computes Cook's distance and leverage at a point-estimate fit's optimum\n(MAP or GMM), or PSIS-LOO Pareto-k and prior influence off a Bayesian fit's posterior.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiag <- fit_diagnostics(f_map)\nround(head(data.frame(cooks_distance = diag$cooks_distance, leverage = diag$leverage), 5), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  cooks_distance leverage\n1         0.0169   0.0331\n2         0.2842   0.4024\n3         0.0028   0.0066\n4         0.0060   0.0142\n5         0.0036   0.0084\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\n  \"largest Cook's distance: observation %d, a %s cfs peak\\n\",\n  which.max(diag$cooks_distance),\n  format(peak_flows[which.max(diag$cooks_distance)], big.mark = \",\")\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlargest Cook's distance: observation 2, a 2,700 cfs peak\n```\n\n\n:::\n:::\n\n\nThe single largest Cook's distance in the record belongs to the second systematic year, 2,700\ncfs, an unusually small peak that pulls a log-space fit the way example 23's Multiple\nGrubbs-Beck low-outlier screen exists to guard against.\n\n## Reproduction check\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The pipeline is deterministic (MLE/MAP by a deterministic optimizer; the Bayesian fit is\n# seeded), so these literals are what this port computes and what the Python notebook asserts --\n# which is what proves the cross-language identity. The comparisons carry a 1e-15 relative\n# tolerance only because R's decimal parser can land one ulp away from the written literal; the\n# fixture suite is what enforces bit-exactness.\nnear <- \\(x, literal) abs(x / literal - 1) < 1e-15\nstopifnot(\n  # MLE, MAP, and Bayesian fits of the same model.\n  near(f_mle$parameters[1], 4.0843461309395188),\n  near(f_mle$parameters[2], 0.19914759083044403),\n  near(f_mle$parameters[3], -0.46572405672529588),\n  near(f_mle$aic, 990.14007771522097),\n  near(f_mle$bic, 995.93555461339395),\n\n  near(f_map$parameters[1], 4.0852361248526048),\n  near(f_map$parameters[2], 0.19616835592097398),\n  near(f_map$parameters[3], -0.41891886262810352),\n  near(f_map$aic, 992.39731155402353),\n  near(f_map$bic, 998.19278845219651),\n\n  near(f_bayes$parameters[1], 4.076977143876432),\n  near(f_bayes$parameters[2], 0.20630009688354539),\n  near(f_bayes$parameters[3], -0.42634285952387641),\n  near(f_bayes$aic, 992.67913589176896),\n  near(f_bayes$bic, 998.47461278994194),\n  near(f_bayes$dic, 989.76032492563218),\n\n  # Profile versus credible intervals on skew.\n  near(ci[\"MLE (profile)\", \"lower\"], -0.82156954677035599),\n  near(ci[\"MLE (profile)\", \"upper\"], 0.083539324732687284),\n  near(ci[\"MAP (profile)\", \"lower\"], -0.77253827944035625),\n  near(ci[\"MAP (profile)\", \"upper\"], 0.053143017857846427),\n  near(ci[\"Bayesian (credible)\", \"lower\"], -0.86792864849208073),\n  near(ci[\"Bayesian (credible)\", \"upper\"], 0.073036977766799502),\n\n  # R-hat and ESS.\n  near(f_bayes$summary[\"Mean (of log) (µ)\", \"rhat\"], 1.0112377055613953),\n  near(f_bayes$summary[\"Std Dev (of log) (σ)\", \"rhat\"], 1.1271063062090425),\n  near(f_bayes$summary[\"Skew (of log) (γ)\", \"rhat\"], 1.0830639682776986),\n  near(f_bayes$summary[\"Mean (of log) (µ)\", \"ess\"], 126.17628141940655),\n  near(f_bayes$summary[\"Std Dev (of log) (σ)\", \"ess\"], 142.53659604889492),\n  near(f_bayes$summary[\"Skew (of log) (γ)\", \"ess\"], 120.76568406444153),\n\n  # GMM: the same censored record, a different estimator.\n  near(f_gmm$parameters[1], 4.0862266825545781),\n  near(f_gmm$parameters[2], 0.2031671188484615),\n  near(f_gmm$parameters[3], -0.68625874896060901),\n  near(f_gmm$j_stat, 3.6036312001472797),\n  is.na(f_gmm$j_stat_pval),\n  near(quantile_variance(f_gmm, 0.01), 0.0043287640050973901),\n\n  # Diagnostics off the MAP fit.\n  near(diag$cooks_distance[2], 0.28415694269045783),\n  near(diag$leverage[2], 0.40243088779094255)\n)\n\n# Internal consistency: the informative prior moves MAP away from MLE and toward the prior mean,\n# every confidence/credible interval brackets its own point estimate, and GMM's log-likelihood\n# based fields are structurally NA while its J-statistic is not.\nstopifnot(\n  abs(f_map$parameters[3] - (-0.3)) < abs(f_mle$parameters[3] - (-0.3)),\n  ci[\"MLE (profile)\", \"lower\"] < f_mle$parameters[3] && f_mle$parameters[3] < ci[\"MLE (profile)\", \"upper\"],\n  ci[\"MAP (profile)\", \"lower\"] < f_map$parameters[3] && f_map$parameters[3] < ci[\"MAP (profile)\", \"upper\"],\n  is.na(f_gmm$aic), is.na(f_gmm$bic), is.na(logLik(f_gmm)),\n  !is.na(f_gmm$j_stat)\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}