{
  "hash": "6b89a28d285b0cd6bd890daf0bea64a4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"19. Global, constrained, and network optimization\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\nExample 13 pointed `optim_minimize()` at a custom likelihood with the six optimizers this package\nshipped at the time. That list is now fourteen, and it covers three kinds of problem the earlier\nsix could not: a rough surface with many local minima, a problem with constraints on top of the\nobjective, and a problem whose derivative you can write down. This page works through all three,\nthen leaves the optimizers entirely for the shortest-path solver that shares their upstream\nnamespace.\n\n## What you'll learn\n\n- Four seeded global optimizers on the same hard surface, and how differently they spend their\n  function evaluations.\n- Why two of them miss the answer at their default settings, and what to change.\n- Constrained minimization with `optim_constraint()` and `method = \"augmented_lagrange\"`, and what\n  the Lagrange multiplier it reports actually tells you.\n- That the choice of inner optimizer decides which local solution a constrained problem converges\n  to.\n- How supplying an analytic gradient to `\"adam\"` cuts its objective calls by a factor of eight.\n- `shortest_path()`, the Dijkstra routing table, over a ten-node network.\n- Which of these reproduce bit-for-bit across R, Python, and the original C# library, and which\n  were measured not to.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## Four global optimizers on one hard surface\n\nThe Eggholder function is the standard torture test for a global optimizer: a lattice of deep\nbasins over $[-512, 512]^2$ with a global minimum of $-959.6407$ in the corner at\n$(512, 404.2319)$, and dozens of local minima almost as deep. Its value at a point tells a local\nmethod nothing about where to go next.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neggholder <- function(p) {\n  x <- p[1]\n  y <- p[2]\n  -(y + 47) * sin(sqrt(abs(x / 2 + (y + 47)))) - x * sin(sqrt(abs(x - (y + 47))))\n}\n```\n:::\n\n\nAll four stochastic global methods take the same arguments -- bounds and a seed -- so swapping\none for another is a one-word change:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmethods <- c(\"de\", \"particle_swarm\", \"sce\", \"simulated_annealing\")\nruns <- lapply(methods, function(m) {\n  optim_minimize(eggholder, lower = c(-512, -512), upper = c(512, 512), method = m, seed = 12345)\n})\nnames(runs) <- methods\n\ndata.frame(\n  method = methods,\n  value = vapply(runs, `[[`, numeric(1), \"value\"),\n  x = vapply(runs, function(r) r$parameters[1], numeric(1)),\n  y = vapply(runs, function(r) r$parameters[2], numeric(1)),\n  evaluations = vapply(runs, `[[`, numeric(1), \"function_evaluations\"),\n  row.names = NULL\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               method     value        x         y evaluations\n1                  de -959.6407 512.0000 404.23175        1000\n2      particle_swarm -959.6407 512.0000 404.23181       72420\n3                 sce -935.3380 439.4810 453.97744        4663\n4 simulated_annealing -293.2958 180.8227  71.65686      800001\n```\n\n\n:::\n:::\n\n\nTwo of the four land on the global minimum and two do not. Differential evolution gets there in\n1,000 objective calls; particle swarm agrees with it to ten significant digits but spends 72,420\ncalls doing so. Shuffled complex evolution stops in a neighbouring basin at $-935.34$, and\nsimulated annealing ends up at $-293.30$, nowhere near.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- seq(-512, 512, length.out = 220)\nsurface <- outer(grid, grid, function(x, y) {\n  -(y + 47) * sin(sqrt(abs(x / 2 + (y + 47)))) - x * sin(sqrt(abs(x - (y + 47))))\n})\nramp <- colorRampPalette(c(\"#40525c\", \"#6f7f6a\", \"#a89a6b\", \"#d8c9a3\", \"#f4efe4\"))\n\nop <- par(mar = c(4.5, 4.5, 3, 1))\nimage(grid, grid, surface, col = ramp(60), xlab = \"x\", ylab = \"y\", asp = 1,\n      xlim = c(-545, 545), ylim = c(-545, 545),\n      main = \"Eggholder surface and where each method stopped\")\nmarks <- c(de = \"#b06a3b\", particle_swarm = \"#7d3f4f\", sce = \"#2f4858\",\n           simulated_annealing = \"#111111\")\n# de and particle_swarm converge to the same corner, so de is drawn last as a wider open ring\n# around the others rather than a filled disc that would hide them.\nfor (m in c(\"sce\", \"simulated_annealing\", \"particle_swarm\")) {\n  points(runs[[m]]$parameters[1], runs[[m]]$parameters[2], pch = 21, cex = 1.6, lwd = 2,\n         col = marks[[m]], bg = \"white\")\n}\npoints(runs$de$parameters[1], runs$de$parameters[2], pch = 21, cex = 3, lwd = 2.5,\n       col = marks[[\"de\"]], bg = NA)\nlegend(\"bottomleft\", methods, pch = 21, pt.cex = 1.3, pt.lwd = 2, col = marks, pt.bg = \"white\",\n       bg = \"white\", box.col = \"grey60\", cex = 0.85)\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-4-1.png){width=576}\n:::\n\n```{.r .cell-code}\npar(op)\n```\n:::\n\n\nDifferential evolution and particle swarm are the two nested circles in the top right corner. The\nother two stopped in basins that look, from inside them, exactly as good.\n\n## The defaults are settings, not verdicts\n\nNeither failure above is a verdict on the method. Shuffled complex evolution runs five complexes by\ndefault; the upstream C# test for this exact function runs thirty, with ten evolution steps each,\nand that run finds the corner:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsce_tuned <- optim_minimize(eggholder, lower = c(-512, -512), upper = c(512, 512), method = \"sce\",\n                            seed = 12345, control = list(complexes = 30, cce_iterations = 10))\nc(default = runs$sce$value, tuned = sce_tuned$value, truth = -959.6407)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  default     tuned     truth \n-935.3380 -959.6407 -959.6407 \n```\n\n\n:::\n:::\n\n\nThirty complexes cost 77,685 objective calls against the default's 4,663, which is the trade: SCE\nsearches by keeping several populations apart long enough to explore separately, and five of them\nare not enough separation for a surface this rough.\n\nSimulated annealing is the more honest failure. Upstream's own test on this function asserts\nnothing at all, under the comment that \"simulated annealing fails to converge for this test\nfunction ... this test is still included as an example\". The port reproduces that failure exactly,\nwhich is the point: a method with a fixed cooling schedule and 10,000 iterations of it will spend\nits whole budget without ever getting cold enough near the right basin.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsa <- runs$simulated_annealing\ncat(sprintf(\"value %.4f after %d iterations and %d objective calls (%s)\\n\",\n            sa$value, sa$iterations, sa$function_evaluations, sa$status))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvalue -293.2958 after 10000 iterations and 800001 objective calls (MaximumIterationsReached)\n```\n\n\n:::\n:::\n\n\nEight hundred thousand objective calls, and the search ends 666 units of objective short of where\ndifferential evolution finished in a thousand. Cost buys nothing if the schedule is wrong for the\nsurface.\n\n## A constrained problem\n\nEverything above minimizes over a box. `method = \"augmented_lagrange\"` is the one method that takes\nconstraints on top of the box: it builds an augmented Lagrangian from the objective and the\nconstraint violations, and hands that to an inner optimizer, tightening the penalty until the\nconstraints hold.\n\nHaimes problem 5.2 is the textbook case. Minimize\n\n$$f(x, y) = (x - 2)^2 + (y - 4)^2 + 5$$\n\nsubject to $g(x, y) = (x - 6)^2 + (y - 10)^2 + 6 \\le 13.31$. The unconstrained minimum sits at\n$(2, 4)$, comfortably outside the feasible disk, so the constraint is binding and the answer must\nlie on its boundary:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary <- function(p) (p[1] - 2)^2 + (p[2] - 4)^2 + 5\nsecondary <- function(p) (p[1] - 6)^2 + (p[2] - 10)^2 + 6\n\nfeasible <- optim_constraint(secondary, value = 13.31, type = \"le\")\nfeasible\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<corehydro_constraint> f(x) <= 13.31 (tolerance 1e-08)\n```\n\n\n:::\n\n```{.r .cell-code}\nhaimes <- optim_minimize(primary, initial = c(5, 5), lower = c(0, 0), upper = c(10, 10),\n                         method = \"augmented_lagrange\", constraints = list(feasible))\nc(x = haimes$parameters[1], y = haimes$parameters[2], value = haimes$value,\n  constraint = secondary(haimes$parameters))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         x          y      value constraint \n  4.501394   7.749627  25.316672  13.310000 \n```\n\n\n:::\n:::\n\n\nThe solution sits on the constraint boundary, $g = 13.31$ to eight digits, at the point the C#\ntest asserts, $(4.5, 7.75)$ with an objective of $25.31$. A constrained method that stopped\nanywhere inside the disk would be reporting a solution the constraint had not actually shaped.\n\nThe multiplier is what a penalty method gives you that a box does not:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhaimes$multipliers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$equality\nnumeric(0)\n\n$less_than\n[1] 1.666595\n\n$greater_than\nnumeric(0)\n```\n\n\n:::\n:::\n\n\n`less_than` holds one entry per `\"le\"` constraint, in the order they were passed. Its value,\n$1.667$, is the shadow price of the constraint: to first order, relaxing the bound by one unit\nimproves the objective by that much. Moving the bound from 13.31 to 14.31 puts the claim to the\ntest:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelaxed <- optim_minimize(primary, initial = c(5, 5), lower = c(0, 0), upper = c(10, 10),\n                          method = \"augmented_lagrange\",\n                          constraints = list(optim_constraint(secondary, value = 14.31,\n                                                              type = \"le\")))\nc(tight = haimes$value, relaxed = relaxed$value, saving = haimes$value - relaxed$value,\n  multiplier = haimes$multipliers$less_than[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     tight    relaxed     saving multiplier \n 25.316672  23.735008   1.581665   1.666595 \n```\n\n\n:::\n:::\n\n\nThe bound bought 1.58 against a predicted 1.67. The multiplier is a derivative and a whole unit is\na long step on a curved boundary, so the two agreeing to 5% is the prediction working, not failing.\nShrink the step and the gap shrinks with it.\n\n## The inner optimizer picks the solution\n\nThe augmented Lagrangian is only as good as the optimizer minimizing it. By default that is BFGS\nover the same bounds; `inner` swaps it for any other method, and on this problem the swap changes\nthe answer:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npowell_inner <- optim_minimize(primary, initial = c(5, 5), lower = c(0, 0), upper = c(10, 10),\n                               method = \"augmented_lagrange\", constraints = list(feasible),\n                               inner = list(method = \"powell\"))\ndata.frame(\n  inner = c(\"bfgs (default)\", \"powell\"),\n  x = c(haimes$parameters[1], powell_inner$parameters[1]),\n  y = c(haimes$parameters[2], powell_inner$parameters[2]),\n  value = c(haimes$value, powell_inner$value),\n  multiplier = c(haimes$multipliers$less_than[1], powell_inner$multipliers$less_than[1])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           inner        x        y    value multiplier\n1 bfgs (default) 4.501394 7.749627 25.31667   1.666595\n2         powell 5.479381 7.346897 28.30781   3.511786\n```\n\n\n:::\n:::\n\n\nBoth points are feasible and both are local solutions; Powell's is worse by three units of\nobjective. This is not a defect in either optimizer, and it is not a port artifact -- the real C#\nlibrary splits the same way on the same problem, which is why the fixture for the Powell run pins\nits own numbers rather than the C# test's. It is the ordinary hazard of a non-convex constrained\nproblem: the constraint boundary has more than one point where the objective's gradient lines up\nwith it, and which one you get is decided by the inner search, not by the constraint.\n\n## An analytic gradient\n\n`\"adam\"` and `\"gradient_descent\"` are the two methods that follow a gradient. Given none, both\ncompute one by finite differences: one extra objective call per parameter per step. Given an\nanalytic gradient, they call it once per step instead.\n\nThe objective here is a separable quadratic with a known minimum at $(0.125, 0.2, 0.35)$ -- three\ncalibration parameters, each with its own target and its own sensitivity:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfxyz <- function(p) (4 * p[1] - 0.5)^2 + (3 * p[2] - 0.6)^2 + (2 * p[3] - 0.7)^2\nfxyz_gradient <- function(p) {\n  c(8 * (4 * p[1] - 0.5), 6 * (3 * p[2] - 0.6), 4 * (2 * p[3] - 0.7))\n}\n\nnumeric_run <- optim_minimize(fxyz, initial = c(0.2, 0.5, 0.5), lower = c(0, 0, 0),\n                              upper = c(1, 1, 1), method = \"adam\")\nanalytic_run <- optim_minimize(fxyz, initial = c(0.2, 0.5, 0.5), lower = c(0, 0, 0),\n                               upper = c(1, 1, 1), method = \"adam\", gradient = fxyz_gradient)\n\ndata.frame(\n  gradient = c(\"finite difference\", \"analytic\"),\n  iterations = c(numeric_run$iterations, analytic_run$iterations),\n  objective_calls = c(numeric_run$function_evaluations, analytic_run$function_evaluations),\n  value = c(numeric_run$value, analytic_run$value)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           gradient iterations objective_calls        value\n1 finite difference       1516           12137 1.093709e-15\n2          analytic       1516            1518 1.093709e-15\n```\n\n\n:::\n:::\n\n\nIdentical path, identical answer, 12,137 objective calls against 1,518. The two runs take the same\n1,516 steps because ADAM's own arithmetic is unchanged; what changes is that the finite-difference\nrun pays eight calls a step to learn the gradient it was handed for free. On a three-parameter\nquadratic that is a curiosity. On a likelihood over a long record it is the difference between a\nfit that finishes and one you abandon.\n\nThe gradient is checked on the way in: return the wrong number of partials and the call fails\nrather than optimizing something else.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptim_minimize(fxyz, initial = c(0.2, 0.5, 0.5), lower = c(0, 0, 0), upper = c(1, 1, 1),\n               method = \"adam\", gradient = function(p) c(1, 2))\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! the gradient must return one value per parameter; got a value of length 2 for 3 parameters\n```\n\n\n:::\n:::\n\n\n## Shortest paths through a network\n\n`shortest_path()` is not an optimizer -- its input is a graph, not a function -- but it comes from\nthe same upstream namespace and answers the same kind of question. Given a directed, weighted\ngraph and one or more destinations, it runs Dijkstra's algorithm backwards from the destinations\nand returns a routing table: for every node, which neighbour to step to, along which edge, and what\nthe remaining trip costs.\n\nThe graph is upstream's own routing test, two ranks of five nodes with a few rungs between them.\nNode indices are 0-based in both packages, matching the C# table they share:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges <- data.frame(\n  from = c(0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9, 9),\n  to   = c(5, 1, 0, 2, 6, 7, 1, 3, 7, 2, 8, 4, 3, 9, 0, 6, 5, 1, 7, 6, 1, 2, 8, 7, 3, 9, 8, 4),\n  cost = c(1, 30, 30, 1, 15, 2, 1, 5, 5, 5, 2, 1, 1, 30, 1, 3, 3, 15, 1, 1, 2, 5, 1, 1, 2, 2, 2, 30),\n  reach = c(0, 1, 1, 2, 3, 4, 2, 5, 6, 5, 7, 8, 8, 9, 0, 10, 10, 3, 11, 11, 4, 6, 12, 12, 7, 13, 13, 9)\n)\n\nroutes <- shortest_path(edges$from, edges$to, edges$cost, destinations = 9,\n                        edge_index = edges$reach)\nroutes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   next_node edge_index cost\n1          5          0    8\n2          7          4    5\n3          1          2    6\n4          8          7    4\n5          3          8    5\n6          6         10    7\n7          7         11    4\n8          8         12    3\n9          9         13    2\n10         9         -1    0\n```\n\n\n:::\n:::\n\n\nRead the table one row at a time. From node 0 the cheapest way to node 9 costs 8 and starts by\nstepping to node 5 -- even though node 0 has a direct edge to node 1, which is one step closer to\nthe destination in hops. That edge costs 30 on its own, and the whole route through node 5\n(0, 5, 6, 7, 8, 9) costs 8 in total. Hop count is not distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npos_x <- c(0:4, 0:4)\npos_y <- c(rep(1, 5), rep(0, 5))\n\nop <- par(mar = c(1, 1, 3, 1))\nplot(pos_x, pos_y, type = \"n\", axes = FALSE, xlab = \"\", ylab = \"\",\n     xlim = c(-0.3, 4.3), ylim = c(-0.35, 1.35),\n     main = \"Cheapest route to node 9 from every node\")\nfor (i in seq_len(nrow(edges))) {\n  segments(pos_x[edges$from[i] + 1], pos_y[edges$from[i] + 1],\n           pos_x[edges$to[i] + 1], pos_y[edges$to[i] + 1], col = \"grey80\")\n}\nfor (n in 0:9) {\n  nxt <- routes$next_node[n + 1]\n  if (nxt != n) {\n    x0 <- pos_x[n + 1]; y0 <- pos_y[n + 1]\n    x1 <- pos_x[nxt + 1]; y1 <- pos_y[nxt + 1]\n    shrink <- 0.78  # stop short of the target circle so the arrowhead stays visible\n    arrows(x0, y0, x0 + shrink * (x1 - x0), y0 + shrink * (y1 - y0), length = 0.11,\n           lwd = 2.5, col = \"#b06a3b\")\n  }\n}\npoints(pos_x, pos_y, pch = 21, cex = 3.4, bg = \"white\", col = \"#2f4858\", lwd = 2)\ntext(pos_x, pos_y, labels = 0:9, cex = 0.8)\ntext(pos_x, pos_y + ifelse(pos_y > 0.5, 0.22, -0.22), labels = sprintf(\"%g\", routes$cost),\n     cex = 0.8, col = \"#6f7f6a\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(op)\n```\n:::\n\n\nEvery arrow is one row of the table, and following them from any node walks the cheapest route to\nnode 9. The number beside each node is its cost to get there. Pass several `destinations` and each\nnode keeps whichever one it reaches most cheaply, which is how you route a whole basin to the\nnearest of several outlets in one call.\n\n## What reproduces across languages, and what does not\n\nMost of this site can promise that a seeded run gives bit-identical numbers in R and Python,\nbecause the work happens in the shared C++ core. The optimizer surface needs that promise stated\nmore carefully, in three tiers, and every tier below was measured rather than assumed.\n\n**Deterministic, and bit-for-bit against C#.** `\"adam\"` and `\"gradient_descent\"` have no random\nnumber generator at all, and reproduce the real C# library exactly -- including the evaluation\ncounts above, 12,137 and 1,518 -- with or without fused-multiply-add contraction in the compiler.\n`shortest_path()` is the same: integer-and-single-precision arithmetic, reproducing C#'s routing\ntable bit-for-bit including its single-precision partial sums. `\"augmented_lagrange\"` has no\ngenerator either, and reproduces C# to about $2 \\times 10^{-9}$ on the constructs above, becoming\nbit-identical when the core is compiled with `-ffp-contract=off` -- the whole residual is\ncontraction inside the inner BFGS.\n\n**Seeded, and completely reproducing.** `\"simulated_annealing\"` and `\"multi_start\"` reproduce\nacross all four of C++, R, Python, and C#: iteration count, evaluation count, converged value, and\nevery parameter.\n`fixtures/toolbox/toolbox_cross_language.json` pins both at zero tolerance for exactly that reason.\n\n**Seeded, and reproducing across the two packages but not necessarily against C#.**\n`\"particle_swarm\"` and `\"sce\"` branch on comparisons between accumulated sums, and clang and gcc\ncontract `a * b + c` into a fused multiply-add by default where .NET never does. One contracted\nexpression can flip an accept-or-reject and every draw after it is spent differently. Measured:\nparticle swarm on the Booth function takes 3,073 iterations and 92,220 evaluations both in the real\nC# library and in an uncontracted C++ build, against 3,855 and 115,680 in a contracted one. So the\nsame fixture pins, for particle swarm on Eggholder, only what survives both paths -- the iteration\ncount, the evaluation count, the converged value, and the parameter that lands exactly on the\nbound -- and for SCE only the counts and the status. Nothing was skipped and no tolerance was\nloosened to get there; the unreproducible quantities are simply not asserted, and each run's\naccuracy is pinned separately against the upstream test's own literals.\n\nUnderneath all three tiers sits the limit example 13 established, which has not changed: a seeded\nrun's parameters come from the shared C++ generator and reproduce, while the reported objective\n*value* comes from re-evaluating your own R or Python code, and the two languages do not guarantee\nidentical rounding for the same formula. On this page they happen to agree to the last bit on every\nconstruct, which is common and is not a guarantee.\n\n## Key takeaways\n\n1. The four seeded global methods differ by more than an order of magnitude in what they spend and\n   by hundreds of units of objective in what they find. Try more than one before believing any of\n   them.\n2. `control` is where a global method's search strategy lives. Shuffled complex evolution finds the\n   Eggholder minimum at thirty complexes and misses it at five; the code is identical.\n3. `optim_constraint()` plus `method = \"augmented_lagrange\"` puts constraints on top of the box, and\n   reports the multiplier that prices each one.\n4. `inner` decides which local solution a constrained non-convex problem converges to. Change it\n   and check whether the answer moved.\n5. An analytic gradient turns a per-parameter finite-difference bill into one call a step -- an\n   eightfold cut on three parameters, more on more.\n6. `shortest_path()` answers routing questions for a whole network at once, and the cheapest route\n   is rarely the one with the fewest hops.\n\n## Reproduction check\n\nFour groups, kept separate. Values pinned against the upstream C# MSTest literals carry that test's\nown tolerance. Values read off the real C# library by the dotnet oracle gate carry the tolerance\nthe matching fixture uses. This page's own deterministic numbers are checked at 1e-15 relative\ntolerance, since R's decimal parser can land one ulp off a written literal. The particle swarm and\nsimulated annealing runs are pinned exactly, but only on the quantities\n`fixtures/toolbox/toolbox_cross_language.json` itself pins -- particle swarm's second parameter is\ndeliberately absent here for the reason given above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear <- \\(x, literal, tol = 1e-15) abs(x / literal - 1) < tol\n\nstopifnot(\n  # Upstream MSTest literals, at the C# test's own tolerance.\n  abs(sce_tuned$value - -959.6407) < 1e-4,                      # SCE Test_Eggholder\n  abs(sce_tuned$parameters[1] - 512) < 1e-3,\n  abs(sce_tuned$parameters[2] - 404.2319) < 1e-3,\n  abs(runs$de$value - -959.6407) < 1e-4,                        # the textbook optimum\n  abs(haimes$parameters[1] - 4.5) < 1e-2,                       # AL Test_Haimes_5_2\n  abs(haimes$parameters[2] - 7.75) < 1e-2,\n  abs(haimes$value - 25.31) < 1e-2,\n  abs(haimes$multipliers$less_than[1] - 1.67) < 1e-2,\n  abs(numeric_run$value - 0) < 1e-4,                            # ADAM Test_FXYZ\n  abs(analytic_run$parameters[1] - 0.125) < 1e-4,\n  abs(analytic_run$parameters[3] - 0.35) < 1e-4,\n\n  # Read off the REAL C# library by the dotnet oracle gate.\n  abs(powell_inner$parameters[1] - 5.4793811558833845) < 1e-6,\n  abs(powell_inner$value - 28.30781213770569) < 1e-6,\n  abs(powell_inner$multipliers$less_than[1] - 3.511785881316314) < 1e-6,\n  numeric_run$function_evaluations == 12137L,\n  analytic_run$function_evaluations == 1518L,\n  analytic_run$iterations == 1516L,\n\n  # Seeded, and measured to reproduce exactly in C++, R, Python and C#.\n  runs$particle_swarm$iterations == 2413L,\n  runs$particle_swarm$function_evaluations == 72420L,\n  identical(runs$particle_swarm$value, -959.640662720851),\n  identical(runs$particle_swarm$parameters[1], 512),\n  identical(runs$simulated_annealing$value, -293.29583227407102),\n  runs$simulated_annealing$iterations == 10000L,\n\n  # The Dijkstra routing table, asserted by exact equality as the C# test asserts it.\n  identical(routes$cost, c(8, 5, 6, 4, 5, 7, 4, 3, 2, 0)),\n  identical(routes$next_node, c(5L, 7L, 1L, 8L, 3L, 6L, 7L, 8L, 9L, 9L)),\n\n  # This page's own deterministic numbers.\n  near(haimes$value, 25.316672218251753),\n  near(secondary(haimes$parameters), 13.31, tol = 1e-9),\n  near(numeric_run$value, 1.0937092922988765e-15)\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}