{
  "hash": "7bb5f43d60cd3e628bf548e313c1ff15",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"26. Copulas and joint frequency\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\nA reservoir cares about two things at once. The peak inflow sizes the spillway; the runoff volume\nsizes the storage. Fitting each record separately says how often each is exceeded and says\nnothing about how often they arrive together. A copula answers that second question: it holds the\ntwo marginal distributions fixed and models only the dependence between them.\n\n`corehydror` exposes the seven bivariate copulas of the Numerics library through `copula()` and\n`copula_fit()`, and the multivariate distributions through `mvdist_normal()` and its siblings.\nThis example fits a copula to a paired peak-and-volume record, prices a coincident design event,\nand checks the answer against the model-based `bivariate_analysis()` path.\n\n## What you'll learn\n\n- Fit a copula's dependence parameter three ways: maximum pseudo-likelihood, Kendall's tau\n  inversion, and inference from margins.\n- Read tail dependence, and watch two copulas that fit the body of a sample almost equally well\n  disagree about its joint tail.\n- Compute the and-joint exceedance probability of a coincident peak-and-volume event, and set it\n  against the answer independence would give.\n- Recover the same probability from a bivariate normal, and cross-check the whole thing against\n  `bivariate_analysis()`.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## Peak and volume pairs\n\nForty-eight water years. The peaks are the annual peak-flow record used in\n[example 21](../21-flood-frequency/r.qmd) and [example 23](../23-censored-flood-frequency/r.qmd);\nthe volumes are a companion record written for this example, so the page is self-contained and\nboth languages read exactly the same numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak <- c(\n  6290, 2700, 13100, 16900, 14600, 9600, 7740, 8490, 8130, 12000,\n  17200, 15000, 12400, 6960, 6500, 5840, 10400, 18800, 21400, 22600,\n  14200, 11000, 12800, 15700, 4740, 6950, 11800, 12100, 20600, 14600,\n  14600, 8900, 10600, 14200, 14100, 14100, 12500, 7530, 13400, 17600,\n  13400, 19200, 16900, 15500, 14500, 21900, 10400, 7460\n)\nvolume <- c(\n  7.21, 3.21, 11.88, 10.70, 9.07, 5.31, 7.04, 5.33, 6.18, 9.54,\n  9.68, 7.66, 8.99, 5.95, 5.37, 6.45, 7.00, 13.71, 12.75, 18.27,\n  11.54, 8.19, 11.15, 10.35, 3.00, 5.67, 6.71, 8.47, 12.02, 12.23,\n  10.71, 9.58, 9.82, 8.90, 8.80, 8.55, 8.48, 3.50, 6.60, 16.79,\n  7.39, 12.95, 11.09, 7.31, 11.50, 16.79, 8.05, 8.56\n)\ncat(sprintf(\n  \"%d water years; peak %s to %s cfs, volume %.2f to %.2f thousand acre-feet\\n\",\n  length(peak), format(min(peak), big.mark = \",\"), format(max(peak), big.mark = \",\"),\n  min(volume), max(volume)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n48 water years; peak 2,700 to 22,600 cfs, volume 3.00 to 18.27 thousand acre-feet\n```\n\n\n:::\n:::\n\n\nThe design event this page prices is a 20,000 cfs peak arriving with a 12 thousand acre-foot\nvolume.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq_peak <- 20000\nq_vol <- 12\n\nplot(peak, volume,\n  log = \"xy\", pch = 16, col = \"#6b7f3f\",\n  xlab = \"Annual peak flow (cfs)\", ylab = \"Runoff volume (thousand acre-feet)\",\n  main = \"Paired peak and volume, 48 water years\"\n)\nabline(v = q_peak, h = q_vol, lty = 2, col = \"#8c5a3b\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-3-1.png){fig-alt='Scatter of annual peak flow against runoff volume on logarithmic axes, with the two design thresholds drawn as dashed lines.' width=672}\n:::\n:::\n\n\n## Dependence without marginals\n\n`copula_fit(family, x, y, method = \"mpl\")` maximizes the pseudo-likelihood. That likelihood is\ndefined on the plotting positions `rank / (n + 1)` rather than on the data scale, so it never\ntouches the marginal distributions. Pass the raw paired observations: the ranking happens inside\nthe shared C++ core, which is why R and Python fit the same number from the same input.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfamilies <- c(\"Clayton\", \"Frank\", \"Gumbel\", \"Joe\", \"Normal\")\nmpl <- lapply(families, \\(f) copula_fit(f, peak, volume, method = \"mpl\"))\nnames(mpl) <- families\n\nranking <- data.frame(\n  n_parameters = sapply(mpl, \\(cop) length(copula_params(cop))),\n  theta = sapply(mpl, \\(cop) cop$theta),\n  pseudo_loglik = sapply(mpl, \\(cop) copula_log_likelihood(cop, peak, volume, method = \"pseudo\"))\n)\nround(ranking[order(-ranking$pseudo_loglik), ], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        n_parameters  theta pseudo_loglik\nNormal             1 0.8652       30.3702\nGumbel             1 2.8147       30.0438\nJoe                1 3.5522       26.7852\nFrank              1 8.6716       25.7708\nClayton            1 2.3063       22.7077\n```\n\n\n:::\n:::\n\n\nAll five carry one dependence parameter and all five are evaluated on the same pseudo\nobservations, so their pseudo log-likelihoods rank them directly. The ranking barely separates\nthe top two: the Normal copula leads, the Gumbel follows, and both stand well clear of the other\nthree. Both are carried forward below, because they turn out to disagree about exactly the part\nof the sample the design question asks about.\n\n`method = \"tau\"` inverts Kendall's tau into the dependence parameter with no likelihood\noptimization at all. Upstream implements that inversion for Clayton, Gumbel, and AliMikhailHaq\nonly, closed form for the first two and a root solve for the third, so asking any other family\nfor it is an error rather than a silent fallback.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(\n  Clayton = copula_fit(\"Clayton\", peak, volume, method = \"tau\")$theta,\n  Gumbel = copula_fit(\"Gumbel\", peak, volume, method = \"tau\")$theta\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClayton  Gumbel \n 3.4473  2.7237 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(tryCatch(copula_fit(\"Frank\", peak, volume, method = \"tau\"),\n             error = conditionMessage), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmethod 'tau' is not available for 'Frank'; upstream implements SetThetaFromTau for Clayton, Gumbel and AliMikhailHaq only \n```\n\n\n:::\n:::\n\n\n## Inference from margins\n\nInference from margins fits each marginal by maximum likelihood first, then estimates the copula\nwith those marginals held fixed. Naming a family in `margin_x` or `margin_y` is what asks for\nthat first step; under `\"ifm\"` an already-parameterized `distribution()` object is attached as\ngiven and skips the fit, while `method = \"mle\"` re-estimates both marginals jointly with the\ndependence parameter. A named marginal is rejected under `\"mpl\"` and `\"tau\"`, since neither\nmethod looks at marginals and the name would come back unfitted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngumbel <- copula_fit(\"Gumbel\", peak, volume, method = \"ifm\",\n                     margin_x = \"LogNormal\", margin_y = \"LogNormal\")\nnormal <- copula_fit(\"Normal\", peak, volume, method = \"ifm\",\n                     margin_x = \"LogNormal\", margin_y = \"LogNormal\")\n\nmargins <- rbind(peak = dist_params(gumbel$margin_x), volume = dist_params(gumbel$margin_y))\nround(margins, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            µ      σ\npeak   4.0674 0.1868\nvolume 0.9278 0.1684\n```\n\n\n:::\n:::\n\n\n`LogNormal` in this library is base 10: the two parameters are the mean and standard deviation of\nthe base-10 logarithm of the variable, the same log space a Bulletin 17C fit reports.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncmp <- data.frame(\n  theta_mpl = c(Gumbel = mpl$Gumbel$theta, Normal = mpl$Normal$theta),\n  theta_ifm = c(gumbel$theta, normal$theta),\n  ifm_loglik = c(copula_log_likelihood(gumbel, peak, volume, method = \"ifm\"),\n                 copula_log_likelihood(normal, peak, volume, method = \"ifm\"))\n)\nround(cmp, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       theta_mpl theta_ifm ifm_loglik\nGumbel    2.8147    2.7123    29.9005\nNormal    0.8652    0.8427    29.7183\n```\n\n\n:::\n:::\n\n\nThe two estimates of the same parameter differ because they are fitted against different things.\nThe pseudo-likelihood sees only ranks, so no marginal can influence it. Inference from margins\nsees the fitted marginal CDFs, and any misfit there passes straight into the copula. Both are\nlegitimate; neither is a refinement of the other.\n\n## Tail dependence\n\nThe tail dependence coefficients are the limiting probability that one variable is extreme given\nthat the other is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(t(sapply(list(Gumbel = gumbel, Normal = normal), copula_tail_dependence)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       lower  upper\nGumbel     0 0.7088\nNormal     0 0.0000\n```\n\n\n:::\n:::\n\n\nNeither has lower tail dependence. In the upper tail they could not be further apart. The Gumbel\ncopula's coefficient is `2 - 2^(1/theta)`, positive for every `theta` above its lower bound of 1,\nwhile the Normal copula returns zero for every correlation. Two copulas that scored within a\nfraction of a log-likelihood unit of each other on the body of the sample make opposite\nstructural claims about its corner.\n\n## Pricing a coincident event\n\n`copula_exceedance()` returns the and-joint exceedance probability `P(U > u, V > v)`, which the\ncore computes as `1 - u - v + C(u, v)`, or the union probability `1 - C(u, v)` with\n`type = \"or\"`. Both take non-exceedance probabilities, so run the design thresholds through the\nfitted marginal CDFs first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nu <- dist_cdf(gumbel$margin_x, q_peak)\nv <- dist_cdf(gumbel$margin_y, q_vol)\n\njoint <- data.frame(\n  p_and = c(\n    `Gumbel copula` = copula_exceedance(gumbel, u, v, \"and\"),\n    `Normal copula` = copula_exceedance(normal, u, v, \"and\"),\n    Independence = (1 - u) * (1 - v)\n  )\n)\njoint$return_period <- 1 / joint$p_and\njoint$vs_independence <- joint$p_and / joint[\"Independence\", \"p_and\"]\nround(joint, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               p_and return_period vs_independence\nGumbel copula 0.0943       10.6022          4.8510\nNormal copula 0.0853       11.7188          4.3888\nIndependence  0.0194       51.4310          1.0000\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\n  \"peak alone: p = %.4f (1 in %.1f);  volume alone: p = %.4f (1 in %.1f)\\n\",\n  1 - u, 1 / (1 - u), 1 - v, 1 / (1 - v)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npeak alone: p = 0.1055 (1 in 9.5);  volume alone: p = 0.1842 (1 in 5.4)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"either one exceeded, Gumbel copula: p = %.4f\\n\",\n            copula_exceedance(gumbel, u, v, \"or\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neither one exceeded, Gumbel copula: p = 0.1954\n```\n\n\n:::\n:::\n\n\nTreating the peak and the volume as independent multiplies their two exceedance probabilities and\nreturns 0.0194. The fitted copulas put the same event at 0.0943 under the Gumbel and 0.0853 under\nthe Normal, and the `vs_independence` column prices the mistake: independence understates how\noften the two arrive together by a factor of 4.85 or 4.39, depending on the copula. Independence\nis not the conservative assumption here.\n\nThe tail dependence coefficients above are limits, so their effect shows up when both variables\nare pushed out together. Walk the two thresholds along the diagonal, holding each marginal at the\nsame annual exceedance probability, and the two copulas separate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naep <- c(0.2, 0.1, 0.02, 0.01, 0.002)\ncorner <- data.frame(\n  marginal_aep = aep,\n  gumbel = sapply(1 - aep, \\(a) copula_exceedance(gumbel, a, a, \"and\")),\n  normal = sapply(1 - aep, \\(a) copula_exceedance(normal, a, a, \"and\")),\n  independence = aep^2\n)\ncorner$gumbel_over_normal <- corner$gumbel / corner$normal\nround(corner, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  marginal_aep   gumbel   normal independence gumbel_over_normal\n1        0.200 0.149673 0.137121        4e-02           1.091534\n2        0.100 0.072808 0.061086        1e-02           1.191897\n3        0.020 0.014252 0.009630        4e-04           1.479991\n4        0.010 0.007107 0.004381        1e-04           1.622369\n5        0.002 0.001418 0.000712        4e-06           1.992958\n```\n\n\n:::\n:::\n\n\nThe Gumbel-to-Normal ratio grows from 1.0915 at a 0.2 marginal exceedance probability to 1.9930\nat 0.002: upper tail dependence hardly matters in the body of the distribution and nearly doubles\nthe joint probability in its corner. Independence falls away far faster than either.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid_aep <- 10^seq(log10(0.5), log10(0.001), length.out = 60)\ng_curve <- sapply(1 - grid_aep, \\(a) copula_exceedance(gumbel, a, a, \"and\"))\nn_curve <- sapply(1 - grid_aep, \\(a) copula_exceedance(normal, a, a, \"and\"))\n\nplot(grid_aep, g_curve,\n  type = \"l\", log = \"xy\", lwd = 2, col = \"#8c5a3b\",\n  ylim = range(g_curve, n_curve, grid_aep^2),\n  xlab = \"Marginal annual exceedance probability (each variable)\",\n  ylab = \"P(both exceeded)\",\n  main = \"Joint exceedance along the diagonal\"\n)\nlines(grid_aep, n_curve, lwd = 2, lty = 2, col = \"#6b7f3f\")\nlines(grid_aep, grid_aep^2, lwd = 2, lty = 3, col = \"#4d6b8a\")\nlegend(\"bottomright\",\n  legend = c(\"Gumbel copula\", \"Normal copula\", \"Independence\"),\n  col = c(\"#8c5a3b\", \"#6b7f3f\", \"#4d6b8a\"), lwd = 2, lty = c(1, 2, 3), bty = \"n\"\n)\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-11-1.png){fig-alt='And-joint exceedance probability against common marginal annual exceedance probability on logarithmic axes: the Gumbel copula solid, the Normal copula dashed, and independence dotted.' width=672}\n:::\n:::\n\n\n## The Normal copula is the bivariate lognormal\n\nA Normal copula with lognormal marginals is a bivariate normal in log space, so the same joint\nprobability is available from `mvdist_normal()` as a rectangle probability. `mvdist_interval()`\nreturns `P(lower <= X <= upper)` through the ported Genz algorithm, and the two routes have to\nagree.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npx <- unname(dist_params(normal$margin_x))\npy <- unname(dist_params(normal$margin_y))\nrho <- normal$theta\ncovar <- matrix(c(px[2]^2, rho * px[2] * py[2],\n                  rho * px[2] * py[2], py[2]^2), nrow = 2)\n\nmvn <- mvdist_normal(mean = c(px[1], py[1]), covariance = covar, seed = 20250812)\nrect <- mvdist_interval(mvn, c(log10(q_peak), log10(q_vol)), c(1e6, 1e6))\np_norm_copula <- copula_exceedance(normal, u, v, \"and\")\n\ncat(sprintf(\"Normal copula   %.15f\\nMVN rectangle   %.15f\\nrelative difference %.1e\\n\",\n            p_norm_copula, rect, rect / p_norm_copula - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNormal copula   0.085332736299363\nMVN rectangle   0.085332736299362\nrelative difference -1.1e-14\n```\n\n\n:::\n:::\n\n\n`mvdist_normal()` takes a `seed` because the Genz integrator draws from its own Mersenne\nTwister. Leave it out and the instance is clock-seeded, so any value that depends on those draws\nstops being reproducible run to run, let alone across languages. `mvdist_cdf()` avoids the\nintegrator entirely at dimension one and two, where the ported code uses closed forms.\n\nThe same object answers the conditional question directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncond <- mvdist_conditional(mvn, given = 1, values = log10(q_peak))\ncond_mean <- mvdist_mean(cond)\ncond_sd <- sqrt(mvdist_covariance(cond)[1, 1])\np_cond <- 1 - dist_cdf(distribution(\"Normal\", c(cond_mean, cond_sd)), log10(q_vol))\n\ncat(sprintf(\n  \"log10 volume given a 20,000 cfs peak: mean %.4f, sd %.4f\\nP(volume > 12 kaf | peak = 20,000 cfs) = %.4f\\n\",\n  cond_mean, cond_sd, p_cond\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog10 volume given a 20,000 cfs peak: mean 1.1052, sd 0.0906\nP(volume > 12 kaf | peak = 20,000 cfs) = 0.6129\n```\n\n\n:::\n:::\n\n\n`mvdist_marginal()`, `mvdist_conditional()`, and `mvdist_interval()` are `MultivariateNormal`\nmethods only; `MultivariateStudentT` has no upstream counterpart for any of the three.\n\n## Cross-check against the model path\n\n`bivariate_analysis()` reaches the same copula from the other direction. It wraps the two fixed\nmarginals and the copula in a model, estimates the dependence parameter with a Bayesian MCMC, and\nreturns a credible band alongside the point curve.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid_x <- c(15000, 20000, 25000)\ngrid_y <- c(9, 12, 15)\n\nba <- bivariate_analysis(\n  \"LogNormal\", peak, px, \"LogNormal\", volume, py,\n  xy_x = grid_x, xy_y = grid_y, copula = \"Normal\",\n  estimation_method = \"InferenceFromMargins\", sampler = \"DEMCz\",\n  iterations = 1000, output_length = 4000, seed = 20250812,\n  number_of_chains = 4, thinning_interval = 1\n)\n\nmap_copula <- copula(\"Normal\", ba$parameters[1])\ngu <- dist_cdf(normal$margin_x, grid_x)\ngv <- dist_cdf(normal$margin_y, grid_y)\nat_map <- mapply(\\(a, b) copula_exceedance(map_copula, a, b, \"and\"), gu, gv)\n\ncross <- data.frame(\n  peak = grid_x, volume = grid_y,\n  analysis_curve = ba$mode_curve,\n  analysis_lower = ba$lower_ci, analysis_upper = ba$upper_ci,\n  copula_at_map = at_map\n)\nround(cross, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   peak volume analysis_curve analysis_lower analysis_upper copula_at_map\n1 15000      9        0.24999        0.23741        0.26039       0.25272\n2 20000     12        0.08362        0.07596        0.09025       0.08533\n3 25000     15        0.02658        0.02305        0.02977       0.02739\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"theta: %.6f from copula_fit(ifm), %.6f reported by the analysis\\n\",\n            normal$theta, ba$parameters[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntheta: 0.842690 from copula_fit(ifm), 0.842682 reported by the analysis\n```\n\n\n:::\n:::\n\n\nThe two paths agree on the dependence parameter to four decimal places, and the copula verb's\nprobability sits inside the analysis's own credible band at all three ordinates. They are not\nidentical, and the reason is worth knowing: `bivariate_analysis()` reports the posterior maximum\nin `parameters`, but builds its curve at whatever point estimator the underlying Bayesian\nanalysis carries, which defaults to the posterior mean. Evaluating `copula_exceedance()` at the\nreported maximum therefore answers a slightly different question than the curve does.\n\n## Reproduction check\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Every fit on this page is deterministic (the copula estimators are optimizers over a fixed\n# sample; the Bayesian cross-check is seeded), so these literals are what this port computes and\n# what the Python notebook asserts -- which is what proves the cross-language identity. The\n# comparisons carry a 1e-15 relative tolerance only because R's decimal parser can land one ulp\n# away from the written literal; the fixture suite is what enforces bit-exactness.\nnear <- \\(x, literal) abs(x / literal - 1) < 1e-15\nstopifnot(\n  # Maximum pseudo-likelihood across five families.\n  near(mpl$Clayton$theta, 2.3063313619874619),\n  near(mpl$Frank$theta, 8.6716321936696286),\n  near(mpl$Gumbel$theta, 2.8147142423362927),\n  near(mpl$Joe$theta, 3.5522244465492729),\n  near(mpl$Normal$theta, 0.8652104567754928),\n  near(ranking[\"Normal\", \"pseudo_loglik\"], 30.370210262642061),\n  near(ranking[\"Gumbel\", \"pseudo_loglik\"], 30.043841011715617),\n\n  # Kendall's tau inversion.\n  near(copula_fit(\"Clayton\", peak, volume, method = \"tau\")$theta, 3.4473182880894253),\n  near(copula_fit(\"Gumbel\", peak, volume, method = \"tau\")$theta, 2.7236591440447127),\n\n  # Inference from margins: the marginals and the two copulas.\n  near(margins[\"peak\", 1], 4.0674283057469083),\n  near(margins[\"peak\", 2], 0.18679432530177564),\n  near(margins[\"volume\", 1], 0.92776174913312093),\n  near(margins[\"volume\", 2], 0.16835824505465125),\n  near(gumbel$theta, 2.7122936851673694),\n  near(normal$theta, 0.84268973641367872),\n  near(cmp[\"Gumbel\", \"ifm_loglik\"], 29.900498224775983),\n  near(cmp[\"Normal\", \"ifm_loglik\"], 29.718349666163725),\n\n  # Tail dependence.\n  copula_tail_dependence(gumbel)[[\"lower\"]] == 0,\n  near(copula_tail_dependence(gumbel)[[\"upper\"]], 0.70881865711981251),\n  copula_tail_dependence(normal)[[\"lower\"]] == 0,\n  copula_tail_dependence(normal)[[\"upper\"]] == 0,\n\n  # The coincident design event.\n  near(u, 0.89445655684934455),\n  near(v, 0.81577716213041274),\n  near(joint[\"Gumbel copula\", \"p_and\"], 0.09432008642998968),\n  near(joint[\"Normal copula\", \"p_and\"], 0.085332736299363332),\n  near(joint[\"Independence\", \"p_and\"], 0.019443512615741197),\n  near(copula_exceedance(gumbel, u, v, \"or\"), 0.19544619459025303),\n\n  # The joint corner: both marginals held at the same exceedance probability.\n  near(corner$gumbel[2], 0.072808127874079531),\n  near(corner$normal[2], 0.061085897213300933),\n  near(corner$gumbel[5], 0.001418389605702286),\n  near(corner$normal[5], 0.00071170053465230421),\n  near(corner$gumbel_over_normal[1], 1.0915335165887639),\n  near(corner$gumbel_over_normal[5], 1.9929584658738935),\n\n  # The bivariate-normal route to the same probability.\n  near(rect, 0.08533273629936243),\n  near(cond_mean, 1.1051865785007626),\n  near(cond_sd, 0.090643992854258601),\n  near(p_cond, 0.61290374236081369),\n\n  # The seeded bivariate_analysis() cross-check.\n  near(ba$parameters[1], 0.84268212806480935),\n  near(ba$mode_curve[2], 0.083618465581119183),\n  near(ba$lower_ci[2], 0.075962830775020973),\n  near(ba$upper_ci[2], 0.090246696612235722),\n  near(at_map[2], 0.085331748836733334)\n)\n\n# Internal consistency: the and-joint identity the core computes, the ordering of the three\n# joint-probability answers, and the copula verb landing inside the analysis's credible band.\nstopifnot(\n  abs(copula_exceedance(normal, u, v, \"and\") - (1 - u - v + copula_cdf(normal, u, v))) < 1e-15,\n  abs(rect / p_norm_copula - 1) < 1e-12,\n  joint[\"Gumbel copula\", \"p_and\"] > joint[\"Normal copula\", \"p_and\"],\n  joint[\"Normal copula\", \"p_and\"] > joint[\"Independence\", \"p_and\"],\n  all(diff(corner$gumbel_over_normal) > 0),\n  all(corner$gumbel > corner$normal), all(corner$normal > corner$independence),\n  all(cross$copula_at_map > cross$analysis_lower),\n  all(cross$copula_at_map < cross$analysis_upper),\n  all(diff(ba$mode_curve) < 0)\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}