{
  "hash": "55707cb504b24fa419abd4ae6e71e343",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"12. Model evaluation\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\n[Example 21](../21-flood-frequency/r.qmd) fits LogNormal, GEV, and Weibull to a 48-year peak-flow\nrecord and ranks them by log-likelihood and AIC, setting the upstream script's\nKolmogorov-Smirnov ranking aside. This example picks it back up, revisiting the same record with\nthe whole goodness-of-fit toolbox -- `goodness_of_fit()`, `gof_test()`, `gof_rmse()`,\n`aic()`/`aic_weights()` -- and confirms the KS statistic agrees with the AIC ranking. It has no upstream counterpart: the USACE-RMC Numerics-Python-Examples\nrepository has no dedicated model-comparison notebook.\n\n## What you'll learn\n\n- Fit several candidate distributions to one flood series and score each with a goodness-of-fit\n  test statistic (`gof_test`), not just log-likelihood.\n- Rank candidates with `aic()`/`aic_weights()`, and read an Akaike weight as \"the probability\n  this model is the best of the set, given the set.\"\n- Score a fitted quantile curve against the data with `goodness_of_fit()`'s general continuous\n  metrics (NSE, KGE, R-squared, ...), the same metrics used to evaluate any modeled-versus-observed\n  series, not just a distribution fit.\n- `classification_metrics()` for a binary comparison, illustrated (a little artificially) on an\n  above/below-median split.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## The data\n\nThe same 48 years of annual peak flows (cfs) as example 21.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_flows <- c(\n  6290, 2700, 13100, 16900, 14600, 9600, 7740, 8490, 8130, 12000,\n  17200, 15000, 12400, 6960, 6500, 5840, 10400, 18800, 21400, 22600,\n  14200, 11000, 12800, 15700, 4740, 6950, 11800, 12100, 20600, 14600,\n  14600, 8900, 10600, 14200, 14100, 14100, 12500, 7530, 13400, 17600,\n  13400, 19200, 16900, 15500, 14500, 21900, 10400, 7460\n)\nn <- length(peak_flows)\ncat(sprintf(\"n = %d peak flows, %s to %s cfs\\n\",\n            n, format(min(peak_flows), big.mark = \",\"), format(max(peak_flows), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 48 peak flows, 2,700 to 22,600 cfs\n```\n\n\n:::\n:::\n\n\n## Fit four candidates\n\nLogNormal and Weibull by maximum likelihood, GEV by L-moments (as in example 21), plus Gumbel by\nmaximum likelihood as a fourth candidate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nln  <- dist_fit(\"LogNormal\", peak_flows, method = \"mle\")\ngev <- dist_fit(\"GeneralizedExtremeValue\", peak_flows, method = \"lmom\")\nwb  <- dist_fit(\"Weibull\", peak_flows, method = \"mle\")\ngum <- dist_fit(\"Gumbel\", peak_flows, method = \"mle\")\n\nmodels <- list(LogNormal = ln, GEV = gev, Weibull = wb, Gumbel = gum)\n```\n:::\n\n\n## Rank with goodness-of-fit test statistics\n\n`gof_test()` mirrors the C# `GoodnessOfFit` class's Kolmogorov-Smirnov D and Anderson-Darling\nA-squared statistics for a fitted distribution against its data -- smaller is a better fit for\nboth. `gof_rmse()` compares the fitted quantiles at Weibull plotting positions to the sorted\ndata. `aic()` needs only the parameter count and the log-likelihood `dist_log_likelihood()`\nalready provides; `aic_weights()` turns a vector of AIC values into weights that sum to one, each\nreading as \"the (relative) probability this is the best model of the set.\"\n\n`aic()`/`gof_test()`/`gof_rmse()` take one model at a time, so `mapply`/`sapply` build the table\none candidate at a time -- there is no vectorized \"rank these four\" verb, deliberately: the\ntoolbox mirrors the C# statics one call at a time, and ranking is a few lines of R on top.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- sapply(models, function(d) length(dist_params(d)))\nlog_lik <- sapply(models, function(d) dist_log_likelihood(d, peak_flows))\nAICs <- mapply(aic, k, log_lik)\nks <- sapply(models, function(d) gof_test(peak_flows, d, test = \"ks\"))\nad <- sapply(models, function(d) gof_test(peak_flows, d, test = \"ad\"))\nrmse_v <- sapply(models, function(d) gof_rmse(peak_flows, d))\nweights <- aic_weights(AICs)\n\nranking <- data.frame(\n  Model = names(models), k = k, LogLik = log_lik, AIC = AICs,\n  KS = ks, AD = ad, RMSE = rmse_v, AkaikeWeight = weights,\n  row.names = NULL\n)\nranking <- ranking[order(ranking$AIC), ]\nprint(ranking, digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Model k   LogLik     AIC        KS       AD    RMSE AkaikeWeight\n3   Weibull 2 -473.046 950.092 0.0663874 0.251832 547.453    0.7070116\n2       GEV 3 -473.223 952.445 0.0696935 0.250618 481.527    0.2179407\n4    Gumbel 2 -475.457 954.915 0.1131102 0.586797 719.701    0.0634083\n1 LogNormal 2 -477.152 958.305 0.1345110 0.841572 874.869    0.0116395\n```\n\n\n:::\n:::\n\n\nWeibull wins on AIC, KS, and RMSE, carrying 71% of the Akaike weight -- confirming, with an\nactual goodness-of-fit test statistic this time, exactly what example 21 found by log-likelihood\nalone: \"Weibull edges out GEV, and LogNormal trails.\" Anderson-Darling is the one holdout: it\nweights tail deviations more heavily than KS, and by that measure GEV's A-squared (0.2506) edges\nWeibull's (0.2518) -- the two are close enough, and the metrics disagree closely enough, that this\nis a real illustration of why a ranking should look at more than one statistic rather than an\nexample built to make every metric agree.\n\n## Score the winning quantile curve\n\n`goodness_of_fit()` is the general-purpose continuous-metrics verb: any modeled-versus-observed\npair, not just a fitted distribution. Comparing the Weibull quantile curve at the data's own\nplotting positions to the sorted observations treats the frequency curve itself as \"the model\"\nand scores it with NSE, KGE, R-squared and friends -- the standard hydrologic model-evaluation\nmetrics, repurposed here for a frequency curve.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp <- plotting_positions(n)\nsorted_flows <- sort(peak_flows)\nmodeled <- dist_quantile(wb, pp)\n\nfit_scores <- goodness_of_fit(sorted_flows, modeled)\nprint(round(fit_scores, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       rmse         mse         mae        mape       smape         nse \n   553.4850 306345.6538    446.4293      4.5060      4.3044      0.9859 \n    log_nse         kge     kge_mod       pbias         rsr     pearson \n     0.9751      0.9355      0.9365     -0.1088      0.1188      0.9947 \n  r_squared           d       d_mod       d_ref          ve \n     0.9894      0.9962      0.9392      0.9407      0.9648 \n```\n\n\n:::\n:::\n\n\nNSE above 0.98 and KGE above 0.93 both say the same thing the AIC ranking already said: the\nWeibull quantile curve tracks the sorted record closely apart from the usual upper-tail spread.\n\n## A binary comparison: `classification_metrics()`\n\n`classification_metrics()` compares two already-binary label vectors -- it has no threshold\nargument, in R or in C#, so the labels are built by hand first. This is a contrived use for a\nfrequency curve (nothing about flood-frequency analysis is naturally binary), but it is the only\npublic verb that exposes the C# `GoodnessOfFit` classification statics, so it is worth seeing\nonce: label each year \"above the median flow\" or not, in both the observed record and the fitted\nquantile curve at the same rank, and score the agreement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmed <- median(peak_flows)\nobs_label <- as.numeric(sorted_flows > med)\nmod_label <- as.numeric(modeled > med)\ncls <- classification_metrics(obs_label, mod_label)\nprint(round(cls, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         accuracy         precision            recall                f1 \n          95.8333            1.0000            0.9167            0.9565 \n      specificity balanced_accuracy \n           1.0000            0.9583 \n```\n\n\n:::\n:::\n\n\n## Plot: fitted curves against plotting positions\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolors <- c(LogNormal = \"#6b7f3f\", GEV = \"#b06a3b\", Weibull = \"#5b7a8c\", Gumbel = \"#8c8c7a\")\nx_grid <- seq(min(peak_flows) * 0.8, max(peak_flows) * 1.1, length.out = 500)\n\nplot(sorted_flows, pp,\n  pch = 19, col = \"black\", log = \"x\",\n  xlab = \"Peak flow (cfs)\", ylab = \"Non-exceedance probability\",\n  main = \"Fitted frequency curves vs plotting positions (Weibull plotting positions)\"\n)\nfor (name in names(models)) {\n  lines(x_grid, dist_cdf(models[[name]], x_grid), col = colors[[name]], lwd = 2)\n}\nlegend(\"bottomright\",\n  legend = c(\"Data (plotting positions)\", sprintf(\"%s (AIC %.1f)\", ranking$Model, ranking$AIC)),\n  pch = c(19, NA, NA, NA, NA), lty = c(NA, 1, 1, 1, 1), lwd = c(NA, 2, 2, 2, 2),\n  col = c(\"black\", colors[ranking$Model]), bty = \"n\"\n)\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(weights[order(AICs)],\n  names.arg = names(models)[order(AICs)],\n  col = colors[names(models)[order(AICs)]], border = \"white\",\n  ylab = \"Akaike weight\", main = \"Model weights (aic_weights())\"\n)\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Key takeaways\n\n1. `gof_test()` and `gof_rmse()` give a fitted distribution the same KS/AD/RMSE ranking the C#\n   `GoodnessOfFit` class always offered, which is what example 21 sets aside.\n2. `aic_weights()` turns a table of AIC values into normalized weights -- useful directly, and\n   the same weights `fit_distributions()`'s composite-model machinery consumes internally.\n3. `goodness_of_fit()` is not distribution-specific: it scores any two equal-length numeric\n   series, so it works as well on a frequency curve as on a rainfall-runoff hydrograph.\n4. `classification_metrics()` fills out the C# `GoodnessOfFit` surface for binary comparisons,\n   even though flood-frequency analysis rarely needs one.\n\n## Reproduction check\n\nNo upstream literals exist for this example (it has no upstream counterpart), so every value\nbelow is an internal-consistency and cross-language check: the ranking is self-consistent (AIC\norder matches the KS order here, and matches the AD order everywhere except the top two, as\ndiscussed above), and the literals are the exact values the Python notebook prints, asserted at\n1e-15 relative tolerance (R's decimal parser can land one ulp away from the written literal; the\nseeded/deterministic values themselves are bit-exact across languages).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear <- \\(x, literal) abs(x / literal - 1) < 1e-15\n\nstopifnot(\n  # Ranking is self-consistent: AIC order (Weibull, GEV, Gumbel, LogNormal) matches the KS order\n  # over the same four models; AD agrees except it swaps the top two (see the prose above).\n  identical(order(AICs), order(ks)),\n  identical(order(AICs)[3:4], order(ad)[3:4]),\n  setequal(order(AICs)[1:2], order(ad)[1:2]),\n  ranking$Model[1] == \"Weibull\",\n  sum(weights) - 1 < 1e-12,\n\n  # Cross-language identity: the Python notebook asserts these same literals.\n  near(AICs[[\"LogNormal\"]], 958.30496639602507),\n  near(AICs[[\"GEV\"]], 952.44533103738274),\n  near(AICs[[\"Weibull\"]], 950.09168256535804),\n  near(AICs[[\"Gumbel\"]], 954.91458850922629),\n  near(ks[[\"Weibull\"]], 0.06638744856290868),\n  near(ad[[\"Weibull\"]], 0.2518324119771691),\n  near(rmse_v[[\"Weibull\"]], 547.45273890460226),\n  near(weights[3], 0.7070115798971689), # Weibull's own weight, position 3 in `models`\n  near(fit_scores[[\"nse\"]], 0.985895395879688),\n  near(fit_scores[[\"kge\"]], 0.93549912169381888),\n  near(fit_scores[[\"r_squared\"]], 0.98937885175430651),\n  near(fit_scores[[\"pearson\"]], 0.99467524939263796),\n  near(cls[[\"accuracy\"]], 95.833333333333329)\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}