{
  "hash": "4b5dcf91421095b4bf01d42289500270",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"27. Composite distributions\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\nMost of the distribution surface takes a family name and a parameter vector. Five families do\nnot, because they are built out of other distributions or out of the data itself: a truncated\ndistribution, a mixture, a competing-risks system, an empirical curve, and a kernel density.\n`corehydror` calls them composite, and each has its own constructor: `dist_truncated()`,\n`dist_mixture()`, `dist_competing_risks()`, `dist_empirical()`, and `dist_kde()`. What comes back\nis an ordinary `corehydro_dist`: the density, distribution, quantile, random-draw, moment,\nparameter, and log-likelihood verbs all take one.\n\nThis example uses three of them on one record: a mixture for a basin with two flood-generating\nmechanisms, a kernel density as a nonparametric reference, and a truncated distribution for a\nphysical lower bound.\n\n## What you'll learn\n\n- Fit a two-component mixture with `model_mixture()` and `fit_mle()`, then rebuild the fit as a\n  standalone `dist_mixture()` distribution.\n- See where a second component changes the frequency curve, and where it does not.\n- Build a kernel density, reproduce its default bandwidth, and understand what\n  `bounded_by_data` does and does not restrict.\n- Renormalize a distribution onto a physical range with `dist_truncated()`.\n- Know the two things composites cannot do.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## A mixed-population record\n\nSixty annual peak flows from a basin with two flood seasons: spring snowmelt produces a cluster\nof moderate peaks, and summer convective storms produce a smaller number of much larger ones. The\nrecord is written out here so the page is self-contained and both languages read the same\nnumbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeaks <- c(\n  1240, 8720, 2110, 1240, 11180, 1570, 11620, 4470, 6470, 1960,\n  1740, 3530, 7440, 9080, 1500, 5760, 7920, 2480, 1790, 2650,\n  1740, 1590, 2080, 2220, 1800, 2120, 11430, 8710, 19870, 1570,\n  1540, 5290, 1480, 7750, 1900, 5630, 1910, 20340, 1280, 9270,\n  5720, 1390, 14490, 2180, 1590, 1530, 6540, 2470, 2490, 7780,\n  13010, 2140, 1220, 11790, 2820, 2000, 2390, 1440, 8740, 2470\n)\nn <- length(peaks)\ncat(sprintf(\"n = %d, range %s to %s cfs\\n\", n,\n            format(min(peaks), big.mark = \",\"), format(max(peaks), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 60, range 1,220 to 20,340 cfs\n```\n\n\n:::\n:::\n\n\n## One distribution, or two?\n\n`model_mixture()` builds a weighted mixture model, and `fit_mle()` fits it the same way it fits\nany other model. The single-family fit is the comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsingle_fit <- fit_mle(model_univariate(\"LogNormal\", peaks))\nmix_fit <- fit_mle(model_mixture(c(\"LogNormal\", \"LogNormal\"), peaks))\n\nround(coef(mix_fit), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWeight (w₁) Weight (w₂)          D1          D1          D2          D2 \n     0.4129      0.5871      3.9323      0.1814      3.2639      0.1046 \n```\n\n\n:::\n:::\n\n\nThe parameter vector is the mixture weights first, then each component's own parameters in order,\nwhich is exactly how the core lays a mixture's parameters out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- unname(coef(mix_fit))\ncomponents <- list(distribution(\"LogNormal\", p[3:4]), distribution(\"LogNormal\", p[5:6]))\n\nfor (i in 1:2) {\n  cat(sprintf(\"component %d: weight %.4f, median %s cfs\\n\", i, p[i],\n              format(round(dist_quantile(components[[i]], 0.5)), big.mark = \",\")))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomponent 1: weight 0.4129, median 8,557 cfs\ncomponent 2: weight 0.5871, median 1,836 cfs\n```\n\n\n:::\n:::\n\n\nTwo seasons, recovered from the record alone: a wide component centered near 8,557 cfs carrying\nweight 0.4129, and a narrow one centered near 1,836 cfs carrying the rest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngof <- data.frame(\n  parameters = c(length(coef(single_fit)), length(coef(mix_fit))),\n  log_likelihood = c(logLik(single_fit), logLik(mix_fit)),\n  aic = c(single_fit$aic, mix_fit$aic),\n  bic = c(single_fit$bic, mix_fit$bic),\n  row.names = c(\"LogNormal\", \"Two-component mixture\")\n)\nround(gof, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      parameters log_likelihood      aic      bic\nLogNormal                      2       -562.620 1129.239 1133.428\nTwo-component mixture          6       -541.624 1095.249 1107.815\n```\n\n\n:::\n:::\n\n\nThe mixture costs four extra parameters, and both criteria still prefer it: its AIC and its BIC\nare lower than the single fit's. A single lognormal cannot be both narrow enough for the snowmelt\ncluster and wide enough for the storm peaks.\n\n## Rebuilding the fit as a distribution\n\n`fit_mle()` returns a fit, not a distribution. `dist_mixture()` turns the fitted numbers back\ninto a `corehydro_dist` the `dist_*()` verbs accept, and the log-likelihood of that composite\nover the same record reproduces the fit's own value exactly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmixture <- dist_mixture(components = components, weights = p[1:2])\nsingle <- distribution(\"LogNormal\", unname(coef(single_fit)))\n\nmixture\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<corehydro_dist> Mixture (composite)\n  {\"family\":\"Mixture\",\"components\":[{\"family\":\"LogNormal\",\"parameters\":[3.93234...\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"log-likelihood: %.10f from dist_mixture(), %.10f from the fit\\n\",\n            dist_log_likelihood(mixture, peaks), logLik(mix_fit)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog-likelihood: -541.6244186353 from dist_mixture(), -541.6244186353 from the fit\n```\n\n\n:::\n:::\n\n\n## Where the second component changes the answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\naeps <- c(0.5, 0.1, 0.01, 0.002)\nquantiles <- data.frame(\n  single = dist_quantile(single, 1 - aeps),\n  mixture = dist_quantile(mixture, 1 - aeps),\n  row.names = paste0(100 * aeps, \"% AEP\")\n)\nquantiles$ratio <- quantiles$mixture / quantiles$single\nround(quantiles, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            single   mixture ratio\n50% AEP   3465.790  2359.245 0.681\n10% AEP   9974.785 11461.031 1.149\n1% AEP   23615.112 19517.846 0.826\n0.2% AEP 37228.118 25218.021 0.677\n```\n\n\n:::\n:::\n\n\nThe mixture is not uniformly heavier. It raises the 10% quantile from 9,975 to 11,461 cfs,\nbecause the storm component puts real probability where a single lognormal had a thin shoulder.\nIt then *lowers* the 1% and 0.2% quantiles, because each component has its own scale and neither\nis as diffuse as the single fit forced to straddle both clusters. Splitting a bimodal record into\ntwo components is not the same as making its tail heavier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(rbind(single = dist_moments(single), mixture = dist_moments(mixture)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            mean   median     mode       sd skewness kurtosis minimum maximum\nsingle  4870.273 3465.790 3465.790 4808.281    3.924   39.305       0     Inf\nmixture 4965.313 2359.245 7186.722 4520.883    1.574    5.837       0     Inf\n```\n\n\n:::\n:::\n\n\nThe moments say the same thing. The two distributions have nearly the same mean, but the\nmixture's standard deviation, skewness, and kurtosis are all smaller and its median is far lower.\nRead the mixture's reported mode with care: the core finds it by maximizing the density with a\nBrent search over the interval between the 0.1% and 99.9% quantiles, which on a two-humped\ndensity converges to whichever hump the search lands in.\n\n## A kernel density as a nonparametric reference\n\n`dist_kde()` builds a density by summing a kernel centered at each observation. With no bandwidth\nsupplied it uses the rule `h = s * (4 / (3n))^(1/5)`, where `s` is the sample standard deviation.\nPassing that value explicitly reproduces the default exactly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh <- sd(peaks) * (4 / (3 * n))^(1 / 5)\nkde <- dist_kde(peaks)\ncat(sprintf(\"bandwidth %.6f; explicit bandwidth reproduces the default: %s\\n\",\n            h, identical(dist_quantile(kde, 0.9), dist_quantile(dist_kde(peaks, bandwidth = h), 0.9))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbandwidth 2143.864822; explicit bandwidth reproduces the default: TRUE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- seq(500, 24000, length.out = 400)\nhist(peaks,\n  breaks = 20, freq = FALSE, border = \"white\", col = \"#d9d2c5\",\n  xlab = \"Annual peak flow (cfs)\", main = \"Three densities over the same record\"\n)\nlines(grid, dist_pdf(single, grid), lwd = 2, col = \"#4d6b8a\")\nlines(grid, dist_pdf(mixture, grid), lwd = 2, col = \"#8c5a3b\")\nlines(grid, dist_pdf(kde, grid), lwd = 2, lty = 2, col = \"#6b7f3f\")\nlegend(\"topright\",\n  legend = c(\"LogNormal\", \"Two-component mixture\", \"Kernel density\"),\n  col = c(\"#4d6b8a\", \"#8c5a3b\", \"#6b7f3f\"), lwd = 2, lty = c(1, 1, 2), bty = \"n\"\n)\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-10-1.png){fig-alt='Histogram of the annual peak record with the single lognormal density, the two-component mixture density, and the kernel density overlaid.' width=672}\n:::\n:::\n\n\n`bounded_by_data`, on by default, sets the distribution's reported minimum and maximum to the\nsmallest and largest observation instead of extending three bandwidths past each. That gates the\nCDF and the quantile function, which cannot then return a value outside the observed range. It\ndoes not gate the density: the kernel sum is evaluated wherever you ask.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_open <- dist_kde(peaks, bounded_by_data = FALSE)\ncat(sprintf(\"largest observation           %s\\n\", format(max(peaks), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlargest observation           20,340\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"0.2%% AEP quantile, bounded     %.1f\\n\", dist_quantile(kde, 0.998)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.2% AEP quantile, bounded     20088.4\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"0.2%% AEP quantile, unbounded   %.1f\\n\", dist_quantile(kde_open, 0.998)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.2% AEP quantile, unbounded   23424.8\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"density at 30,000 cfs identical either way: %s\\n\",\n            dist_pdf(kde, 30000) == dist_pdf(kde_open, 30000)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndensity at 30,000 cfs identical either way: TRUE\n```\n\n\n:::\n:::\n\n\nThat is the honest limit of a kernel density for design work. It describes the record it was\nbuilt from and will not extrapolate past it, which is exactly why the parametric fits above still\nhave a job.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(data.frame(\n  single = dist_quantile(single, 1 - aeps),\n  mixture = dist_quantile(mixture, 1 - aeps),\n  kde = dist_quantile(kde, 1 - aeps),\n  row.names = paste0(100 * aeps, \"% AEP\")\n), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          single mixture     kde\n50% AEP   3465.8  2359.2  5011.0\n10% AEP   9974.8 11461.0 12151.2\n1% AEP   23615.1 19517.8 19109.9\n0.2% AEP 37228.1 25218.0 20088.4\n```\n\n\n:::\n:::\n\n\n## A physical lower bound\n\nSuppose a downstream diversion guarantees that at least 1,000 cfs passes the gauge in any year,\nso an annual maximum below that is impossible. The fitted lognormal does not know this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(sprintf(\"P(annual peak < 1,000 cfs) under the fitted LogNormal: %.4f\\n\",\n            dist_cdf(single, 1000)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(annual peak < 1,000 cfs) under the fitted LogNormal: 0.0659\n```\n\n\n:::\n:::\n\n\n`dist_truncated()` restricts a distribution to `[min, max]` and renormalizes: the density becomes\nthe base density divided by `F(max) - F(min)`, zero outside the bounds, and the CDF becomes\n`(F(x) - F(min)) / (F(max) - F(min))`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntruncated <- dist_truncated(single, min = 1000, max = 1e6)\n\ncat(sprintf(\"CDF at the lower bound: %.1f\\n\", dist_cdf(truncated, 1000)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCDF at the lower bound: 0.0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"density ratio at 5,000 cfs: %.10f\\n\",\n            dist_pdf(truncated, 5000) / dist_pdf(single, 5000)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndensity ratio at 5,000 cfs: 1.0705813468\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"1 / (F(max) - F(min)):       %.10f\\n\",\n            1 / (dist_cdf(single, 1e6) - dist_cdf(single, 1000))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 / (F(max) - F(min)):       1.0705813468\n```\n\n\n:::\n:::\n\n\nRemoving the impossible lower tail pushes every quantile up, proportionally most at the median\nand least in the tail that mattered anyway.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshifted <- data.frame(\n  base = dist_quantile(single, 1 - aeps),\n  truncated = dist_quantile(truncated, 1 - aeps),\n  row.names = paste0(100 * aeps, \"% AEP\")\n)\nshifted$ratio <- shifted$truncated / shifted$base\nround(shifted, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              base truncated  ratio\n50% AEP   3465.789  3710.536 1.0706\n10% AEP   9974.785 10296.732 1.0323\n1% AEP   23615.112 24116.694 1.0212\n0.2% AEP 37228.118 37892.583 1.0178\n```\n\n\n:::\n:::\n\n\n## What composites cannot do\n\nTwo things. First, none of the five implements linear moments upstream, so `dist_lmoments()`\ndeclines rather than approximating.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(tryCatch(dist_lmoments(mixture), error = conditionMessage), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlinear moments are not available for 'Mixture'; no composite distribution implements ILinearMomentEstimation upstream \n```\n\n\n:::\n:::\n\n\nSecond, a composite has no flat parameter vector, so `distribution()` will not build one and\nthere is no `dist_fit()` path to a composite family. Mixtures are fitted through\n`model_mixture()` and an estimator, as above; competing-risks systems through\n`model_competing_risks()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(tryCatch(distribution(\"Mixture\", c(0.5, 0.5)), error = conditionMessage), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'Mixture' has no flat parameter vector; use dist_mixture() instead \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(tryCatch(distribution(\"KernelDensity\", 1), error = conditionMessage), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'KernelDensity' has no flat parameter vector; use dist_kde() instead \n```\n\n\n:::\n\n```{.r .cell-code}\ndistribution_names(\"structured\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"TruncatedDistribution\" \"Mixture\"               \"CompetingRisks\"       \n[4] \"Empirical\"             \"KernelDensity\"        \n```\n\n\n:::\n:::\n\n\n## Reproduction check\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Every fit on this page is deterministic (maximum likelihood by a deterministic optimizer; the\n# kernel density and the truncation are closed-form), so these literals are what this port\n# computes and what the Python notebook asserts -- which is what proves the cross-language\n# identity. The comparisons carry a 1e-15 relative tolerance only because R's decimal parser can\n# land one ulp away from the written literal; the fixture suite is what enforces bit-exactness.\nnear <- \\(x, literal) abs(x / literal - 1) < 1e-15\nstopifnot(\n  # The two maximum-likelihood fits.\n  near(coef(single_fit)[1], 3.5398021872265386),\n  near(coef(single_fit)[2], 0.35823869011128351),\n  near(logLik(single_fit), -562.61957474501503),\n  near(coef(mix_fit)[1], 0.41289769144404032),\n  near(coef(mix_fit)[2], 0.58710230855595968),\n  near(coef(mix_fit)[3], 3.9323412160584628),\n  near(coef(mix_fit)[4], 0.18144915787795951),\n  near(coef(mix_fit)[5], 3.2639016318942939),\n  near(coef(mix_fit)[6], 0.10464430806060765),\n  near(logLik(mix_fit), -541.62441863534707),\n  near(gof[\"LogNormal\", \"aic\"], 1129.2391494900301),\n  near(gof[\"Two-component mixture\", \"aic\"], 1095.2488372706941),\n  near(gof[\"LogNormal\", \"bic\"], 1133.4278386144742),\n  near(gof[\"Two-component mixture\", \"bic\"], 1107.8149046440267),\n\n  # The composite rebuilt from the fitted values.\n  dist_log_likelihood(mixture, peaks) == logLik(mix_fit),\n\n  # Quantiles: the mixture is higher at 10% and lower at 1% and 0.2%.\n  near(quantiles$single[2], 9974.7849506787734),\n  near(quantiles$mixture[2], 11461.031257850214),\n  near(quantiles$single[3], 23615.111603538928),\n  near(quantiles$mixture[3], 19517.845994674906),\n  near(quantiles$single[4], 37228.117722712399),\n  near(quantiles$mixture[4], 25218.020604342844),\n  near(dist_moments(mixture)[[\"skewness\"]], 1.5738083017829989),\n  near(dist_moments(single)[[\"skewness\"]], 3.9241120906543738),\n\n  # The kernel density.\n  near(h, 2143.864821560871),\n  identical(dist_quantile(kde, 0.9), dist_quantile(dist_kde(peaks, bandwidth = h), 0.9)),\n  near(dist_quantile(kde, 0.9), 12151.217810408163),\n  near(dist_quantile(kde, 0.998), 20088.429334855526),\n  near(dist_quantile(kde_open, 0.998), 23424.805148963263),\n  dist_pdf(kde, 30000) == dist_pdf(kde_open, 30000),\n\n  # The truncated distribution.\n  near(dist_cdf(single, 1000), 0.065928055787046747),\n  dist_cdf(truncated, 1000) == 0,\n  near(dist_quantile(truncated, 0.5), 3710.536428782953),\n  near(dist_quantile(truncated, 0.99), 24116.69387849512),\n  near(dist_pdf(truncated, 5000) / dist_pdf(single, 5000), 1.0705813467570697)\n)\n\n# Internal consistency: the truncation identities the core documents, the bounded kernel density\n# refusing to leave the observed range, and the mixture beating the single fit on both criteria.\nstopifnot(\n  abs(dist_pdf(truncated, 5000) / dist_pdf(single, 5000) -\n        1 / (dist_cdf(single, 1e6) - dist_cdf(single, 1000))) < 1e-12,\n  dist_pdf(truncated, 500) == 0,\n  dist_quantile(kde, 0.998) < max(peaks),\n  dist_quantile(kde_open, 0.998) > max(peaks),\n  mix_fit$aic < single_fit$aic, mix_fit$bic < single_fit$bic,\n  all(shifted$ratio > 1), all(diff(shifted$ratio) < 0),\n  abs(sum(p[1:2]) - 1) < 1e-12\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}