{
  "hash": "7a0c7435dcdaa196d33d2362004720c9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"17. A pivotal bootstrap\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\nExample 15 built a bootstrap out of four functions you write. This page is about the other run type\nthe ported Numerics `Bootstrap` class has, reached with `run_type = \"pivotal\"`. It replaces the\nresampled fit with a pivot of that fit around the original one, standardized through the resample's\nown covariance and reinflated through the original's, so a replicate fitted on an unusually flat\nlikelihood contributes an appropriately smaller step. It therefore needs a covariance with every\nfit, which is why it fits through a fifth function, `fit_with_covariance`, instead of `fit`.\n\nLike examples 13 and 15, it has no upstream counterpart.\n\n## What you'll learn\n\n- What the pivotal transform does to a replicate, in one line of algebra.\n- The signature of `fit_with_covariance`, the one function this run type adds.\n- Both interval blocks a pivotal run reports, and why it reports two.\n- `pivotal_diagnostics`: six counts that say what happened to the replicates you asked for.\n- Standardizing in link space, and which links change the answer.\n- Where the cross-language guarantee stops on the callback path, and how to stay inside it.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n```\n:::\n\n\n## The transform\n\nWrite $\\theta$ for a parameter vector and $\\Sigma$ for its covariance. The parent fit is\n$(\\hat{\\theta}, \\hat{\\Sigma})$, from the whole sample; a replicate gives $(\\theta^*, \\Sigma^*)$.\nWith $L$ for the lower Cholesky factor of each covariance, the pivotal draw is\n\n$$\nz = (L^*)^{-1}(\\hat{\\theta} - \\theta^*), \\qquad\n\\theta^{\\text{piv}} = \\hat{\\theta} + \\hat{L} z\n$$\n\nTwo things follow from the sign. The difference is taken parent minus replicate, so a replicate that\nlanded BELOW the parent produces a draw ABOVE it. The ensemble is reflected through the parent\nrather than centered on the replicates, which is the same idea as the basic bootstrap's\n$2\\hat{\\theta} - \\theta^*$, generalized to a correlated parameter vector. And the step is measured\nin units of the replicate's own standard error and re-expressed in units of the parent's, so a\nreplicate whose fit was poorly determined contributes a shorter step than one whose fit was sharp.\n\n## The record and the model\n\nForty years of $\\log_{10}$ annual peak discharge, drawn from a Normal population through the seeded\ncore so the Python twin has the identical record. Working in $\\log_{10}$ keeps the model a plain\nlocation-scale Normal, whose maximum likelihood estimate and covariance are both closed form. That\nmatters here for a reason beyond convenience, taken up at the end of the page: it makes the callback\npure arithmetic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_peaks <- dist_random(distribution(\"Normal\", c(4.60, 0.22)), 40, seed = 2027)\n\ncat(sprintf(\"n = %d, mean = %.4f (%.0f cfs), sd = %.4f\\n\",\n            length(log_peaks), mean(log_peaks), 10^mean(log_peaks),\n            sqrt(mean((log_peaks - mean(log_peaks))^2))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 40, mean = 4.6550 (45183 cfs), sd = 0.2067\n```\n\n\n:::\n:::\n\n\nThe three functions the run needs. `resample` is the ordinary iid one from example 15, drawing its\nindices from the generator the replicate hands it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresample_iid <- function(data, parameters, rng) {\n  data[rng_integers(rng, length(data), 0, length(data)) + 1L]\n}\n```\n:::\n\n\n`fit_with_covariance(data)` is the one signature this run type adds. It returns a list with\n`parameters` and `covariance`: the fitted vector, and its covariance as a matrix with one row and\none column per parameter. For the Normal MLE both are textbook,\n$\\operatorname{Var}(\\hat\\mu) = \\sigma^2/n$ and $\\operatorname{Var}(\\hat\\sigma) = \\sigma^2/2n$, with\nno covariance between them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormal_mle <- function(data) {\n  n <- length(data)\n  acc <- 0\n  for (x in data) acc <- acc + x\n  mu <- acc / n\n  ss <- 0\n  for (x in data) ss <- ss + (x - mu) * (x - mu)\n  list(mu = mu, s2 = ss / n, n = n)\n}\n\nfit_with_cov <- function(data) {\n  f <- normal_mle(data)\n  list(parameters = c(f$mu, sqrt(f$s2)),\n       covariance = matrix(c(f$s2 / f$n, 0,\n                             0, f$s2 / (2 * f$n)), nrow = 2L, ncol = 2L))\n}\n\nfit_only <- function(data) {\n  f <- normal_mle(data)\n  c(f$mu, sqrt(f$s2))\n}\n```\n:::\n\n\n`statistic(parameters)` turns a parameter vector into the numbers to be given intervals. Here it\nreturns the two parameters and the design quantity built from them, the 1% annual chance\n$\\log_{10}$ peak, $\\mu + z_{0.99}\\sigma$. The standard normal deviate is computed once, outside the\ncallback, so the callback itself does nothing but multiply and add.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz99 <- dist_quantile(distribution(\"Normal\", c(0, 1)), 0.99)\n\ndesign_statistic <- function(parameters) {\n  c(parameters[1], parameters[2], parameters[1] + z99 * parameters[2])\n}\n```\n:::\n\n\n## The regular run, for comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregular <- bootstrap_custom(\n  data = log_peaks, resample = resample_iid, fit = fit_only,\n  statistic = design_statistic, replicates = 400, alpha = 0.1, seed = 2027\n)\n\nshow_block <- function(estimate, lower, upper) {\n  data.frame(statistic = c(\"mean\", \"sd\", \"1% AEP\"),\n             estimate = estimate, lower = lower, upper = upper,\n             width = upper - lower)\n}\nprint(show_block(regular$estimate, regular$lower, regular$upper), row.names = FALSE, digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n statistic estimate    lower   upper    width\n      mean 4.654973 4.602628 4.70326 0.100632\n        sd 0.206669 0.154681 0.25583 0.101149\n    1% AEP 5.135757 5.026432 5.23459 0.208163\n```\n\n\n:::\n:::\n\n\n## The pivotal run\n\nThe same data, the same seed, the same statistic. `fit` is replaced by `fit_with_covariance`, and\npassing both is an error rather than a silent preference for one of them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npiv <- bootstrap_custom(\n  data = log_peaks, resample = resample_iid, statistic = design_statistic,\n  fit_with_covariance = fit_with_cov, run_type = \"pivotal\",\n  replicates = 400, alpha = 0.1, seed = 2027\n)\n\ncat(\"pivotal ensemble:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npivotal ensemble:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(show_block(piv$estimate, piv$lower, piv$upper), row.names = FALSE, digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n statistic estimate    lower   upper    width\n      mean 4.654973 4.600234 4.70390 0.103668\n        sd 0.206669 0.166954 0.27613 0.109175\n    1% AEP 5.135757 5.051078 5.27766 0.226584\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nraw covariance-aware fits:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nraw covariance-aware fits:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(show_block(piv$raw_estimate, piv$raw_lower, piv$raw_upper), row.names = FALSE, digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n statistic estimate    lower   upper    width\n      mean 4.654973 4.602628 4.70326 0.100632\n        sd 0.206669 0.154681 0.25583 0.101149\n    1% AEP 5.135757 5.026432 5.23459 0.208163\n```\n\n\n:::\n:::\n\n\nA pivotal run reports two interval blocks, and comparing them is the point of reporting both. The\nraw block is the plain percentile interval of the covariance-aware fits, before the transform. It is\nthe answer the regular run gives, and here it is that answer to the last bit, because the two runs\nresampled the same observations in the same order from the same seed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(identical(regular$lower, piv$raw_lower), identical(regular$upper, piv$raw_upper))\ncat(\"raw block and regular run agree exactly.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nraw block and regular run agree exactly.\n```\n\n\n:::\n:::\n\n\nThe pivotal block is different, and on this sample it is wider on the two quantities that matter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison <- data.frame(\n  statistic = c(\"mean\", \"sd\", \"1% AEP\"),\n  raw_width = piv$raw_upper - piv$raw_lower,\n  pivotal_width = piv$upper - piv$lower\n)\ncomparison$ratio <- comparison$pivotal_width / comparison$raw_width\nprint(comparison, row.names = FALSE, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n statistic raw_width pivotal_width ratio\n      mean    0.1006        0.1037 1.030\n        sd    0.1011        0.1092 1.079\n    1% AEP    0.2082        0.2266 1.088\n```\n\n\n:::\n:::\n\n\nThe mean's interval barely moves, the scale parameter's grows by 8% and the design quantile's, which\nis built from both, by 9%. That is the reflection at work: the percentile interval of the replicates\nunderstates a skewed sampling distribution on the side the replicates cluster away from, and\npivoting through the parent puts the width back on the other side. Read as discharge rather than as\nits logarithm, the 1% annual chance peak moves from a 90% interval of 106,000 to 172,000 cfs to one\nof 112,000 to 190,000 cfs. The upper end, which is the end a design decision turns on, moves by\n10%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(sprintf(\"raw:     %6.0f to %6.0f cfs\\n\", 10^piv$raw_lower[3], 10^piv$raw_upper[3]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nraw:     106275 to 171631 cfs\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"pivotal: %6.0f to %6.0f cfs\\n\", 10^piv$lower[3], 10^piv$upper[3]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npivotal: 112481 to 189523 cfs\n```\n\n\n:::\n:::\n\n\n## The diagnostics\n\nA pivotal replicate can be lost at three separate places, so the run reports six counts rather than\nthe single `failed_replicates` a regular run has.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(unlist(piv$pivotal_diagnostics))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       requested_replicates     rejected_raw_replicates \n                        400                           0 \n      failed_raw_replicates     accepted_raw_replicates \n                          0                         400 \n invalid_pivotal_replicates retained_pivotal_replicates \n                          0                         400 \n```\n\n\n:::\n:::\n\n\n`requested_replicates` is what you asked for. `failed_raw_replicates` counts the resample-and-fit\npairs that never produced a fit, after their retries, and `rejected_raw_replicates` counts fits a\nfilter discarded. `accepted_raw_replicates` is what reached the transform, and it is the raw block's\nsample size. Of those, `invalid_pivotal_replicates` could not be transformed and\n`retained_pivotal_replicates` is what the pivotal block was computed from; those two always add up\nto `accepted_raw_replicates`. Nothing went wrong here, so all 400 survive. The next section makes\nthem fail on purpose.\n\n## Standardizing in link space\n\n`pivotal_links` gives one link function per parameter, and the standardization happens in link\nspace: $\\eta = g(\\theta)$ is what gets differenced and reinflated, and $g^{-1}$ brings the draw\nback. A `\"Log\"` link on a positive parameter is the usual reason to do this, because it keeps every\nreinflated draw positive no matter how far the step reaches. `NULL` in a slot is the identity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinked <- bootstrap_custom(\n  data = log_peaks, resample = resample_iid, statistic = design_statistic,\n  fit_with_covariance = fit_with_cov, run_type = \"pivotal\",\n  pivotal_links = list(\"Log\", NULL),\n  replicates = 400, alpha = 0.1, seed = 2027\n)\n\nprint(data.frame(statistic = c(\"mean\", \"sd\", \"1% AEP\"),\n                 identity_lower = piv$lower, log_lower = linked$lower,\n                 identity_upper = piv$upper, log_upper = linked$upper),\n      row.names = FALSE, digits = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n statistic identity_lower    log_lower identity_upper    log_upper\n      mean   4.6002343748 4.6002794039   4.7039019442 4.7038451938\n        sd   0.1669544489 0.1669544489   0.2761295383 0.2761295383\n    1% AEP   5.0510777890 5.0510747437   5.2776613148 5.2776620830\n```\n\n\n:::\n:::\n\n\nThe link is on the mean here, the first parameter, and it moves the interval in the fifth decimal.\nSmall, but it is a real difference and not a rounding artifact: the difference and the reinflation\nare being taken on $\\log \\mu$ rather than on $\\mu$, and the two disagree because the transform is\nnot linear.\n\nA link on the scale parameter would be the more natural choice, and it is worth knowing that on\nTHIS model it does nothing measurable. For a Normal MLE the two Cholesky factors of the\n$\\hat\\sigma$ variance are in the ratio $\\hat\\sigma / \\sigma^*$, so the identity draw works out to\n$\\hat\\sigma^2/\\sigma^*$, and so does the log draw,\n$\\exp(2\\log\\hat\\sigma - \\log\\sigma^*)$. They agree to about 1e-11, which is Cholesky and `log`\nrounding rather than a difference in the answer. That invariance is a property of this covariance,\nnot of log links, and it is the reason this page links the mean when it wants to show a link\nworking.\n\n## Draws the transform cannot make\n\n`pivotal_z_limit` bounds every component of the standardized vector $z$, and a draw outside it is\ninvalid. `pivotal_invalid_draw_policy` decides what happens to an invalid draw: `\"drop\"` leaves it\nout of the ensemble, `\"use_raw\"` keeps the untransformed fit, `\"use_parent\"` substitutes the parent.\nA limit of 1.5 standard units is aggressive enough to reject a third of the draws here, which is\nwhat makes the three policies visibly different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicies <- do.call(rbind, lapply(c(\"drop\", \"use_raw\", \"use_parent\"), function(policy) {\n  r <- bootstrap_custom(\n    data = log_peaks, resample = resample_iid, statistic = design_statistic,\n    fit_with_covariance = fit_with_cov, run_type = \"pivotal\",\n    pivotal_z_limit = 1.5, pivotal_invalid_draw_policy = policy,\n    replicates = 400, alpha = 0.1, seed = 2027\n  )\n  data.frame(policy = policy,\n             retained = r$pivotal_diagnostics$retained_pivotal_replicates,\n             invalid = r$pivotal_diagnostics$invalid_pivotal_replicates,\n             lower = r$lower[3], upper = r$upper[3], width = r$upper[3] - r$lower[3])\n}))\nprint(policies, row.names = FALSE, digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     policy retained invalid   lower   upper    width\n       drop      267     133 5.06217 5.20510 0.142932\n    use_raw      400     133 5.02643 5.23023 0.203795\n use_parent      400     133 5.07169 5.19715 0.125459\n```\n\n\n:::\n:::\n\n\nAll three see the same 133 invalid draws, which is a property of the limit and not of the policy.\nWhat they do about them differs, and so does the interval. `\"drop\"`, the default, computes the\npercentile from the 267 survivors, and because a limit on $z$ removes the largest steps first, those\nsurvivors are the central ones and the interval is narrow. `\"use_raw\"` fills the gaps with the\nuntransformed fits, which reach further out than the surviving pivotal draws in both directions, so\nit gives the widest interval of the three. `\"use_parent\"` fills them with the parent, 133 copies of\none point in the middle, and gives the narrowest by construction.\n\nNone of the three is a repair. A limit tight enough to reject a third of the draws is telling you\nthe parametrization needs a link, not that the draws need a policy, and `\"use_parent\"` in particular\nreports a confidence interval computed partly from the estimate it is supposed to be uncertain\nabout.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrows <- rbind(\n  data.frame(label = \"regular\", lower = regular$lower[3], upper = regular$upper[3]),\n  data.frame(label = \"raw block\", lower = piv$raw_lower[3], upper = piv$raw_upper[3]),\n  data.frame(label = \"pivotal\", lower = piv$lower[3], upper = piv$upper[3]),\n  data.frame(label = \"pivotal, log link\", lower = linked$lower[3], upper = linked$upper[3]),\n  data.frame(label = paste0(\"z<1.5, \", policies$policy), lower = policies$lower,\n             upper = policies$upper)\n)\n\nop <- par(mar = c(4.5, 9, 3, 1))\ny <- rev(seq_len(nrow(rows)))\nplot(NA, xlim = range(c(rows$lower, rows$upper)), ylim = c(0.5, nrow(rows) + 0.5),\n     yaxt = \"n\", ylab = \"\", xlab = expression(log[10] ~ \"of the 1% annual chance peak\"),\n     main = \"90% intervals for one design statistic\")\naxis(2, at = y, labels = rows$label, las = 1, cex.axis = 0.85)\nabline(v = piv$estimate[3], col = \"#6b7f3f\", lty = 2, lwd = 2)\nsegments(rows$lower, y, rows$upper, y, col = \"#5b7a8c\", lwd = 4)\npoints(rep(piv$estimate[3], nrow(rows)), y, pch = 19, col = \"#b06a3b\")\nlegend(\"bottomright\", c(\"Interval\", \"Point estimate\"), lty = c(1, 2), lwd = c(4, 2),\n       col = c(\"#5b7a8c\", \"#6b7f3f\"), bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(op)\n```\n:::\n\n\n## What reproduces across languages, and what does not\n\nMost pages on this site can promise that a seeded run gives bit-identical numbers in R and Python,\nbecause every operation on them happens inside the shared C++ core and the two packages call the\nsame compiled code. The callback path is where that promise needs a condition attached, and it is\nbetter stated plainly than buried. It applies here, to example 13's custom objective, to example\n14's custom posterior and to example 15's custom bootstrap alike.\n\nThe resampled INDICES still come from the core generator, so a given seed selects the identical\nobservations in the identical order in both languages, replicate for replicate. That half is\nunconditional. The other half is not: `fit_with_covariance` and `statistic` are your own R or Python\ncode, and the two languages do not guarantee identical rounding for the same formula. A run\nreproduces across languages if and only if your functions return bit-identical values.\n\nThe functions on this page do, and by construction rather than by luck. They add, subtract, multiply\nand divide, and they take one square root. Arithmetic is IEEE-deterministic, and `sqrt` is the one\nlibrary function IEEE 754 requires to be correctly rounded, so both languages must return the same\nbits for it. That is why the model here is a location-scale Normal in $\\log_{10}$ space instead of\nsomething fitted numerically: it keeps `log` and `exp` out of the callback, where they would put the\nlast bit at the mercy of two different math libraries. Every number this page prints is identical in\nthe Python twin.\n\nThe package's own cross-language fixture pins the same construct.\n`fixtures/callback/callback_cross_language.json` runs this exact model, on eight observations at\nseed 12345, and asserts the pivotal and raw endpoints at ZERO tolerance, meaning bit equality rather\nthan a tolerance, across all four runners: the C++ fixture harness, R, Python, and the dotnet oracle\nemitter driving the real C# `Bootstrap` class. The reproduction check below is that construct.\n\n## Key takeaways\n\n1. `run_type = \"pivotal\"` reflects each replicate through the parent fit, standardized by the\n   replicate's own covariance and reinflated by the parent's.\n2. It fits through `fit_with_covariance(data)`, returning `parameters` and `covariance`. Passing\n   `fit` as well is an error, not a preference.\n3. Every pivotal run reports two interval blocks. The raw one is what a regular run would have said;\n   the difference between them is the transform's contribution.\n4. Read `pivotal_diagnostics` before reading the interval. `retained_pivotal_replicates` is the\n   sample size the interval was actually computed from.\n5. Standardize in link space when a parameter is constrained. Whether a given link changes the\n   answer depends on the covariance, so check rather than assume.\n6. Only `ci_method = \"Percentile\"` exists after a pivotal run, and asking for another is refused\n   before the first replicate rather than after all of them.\n\n## Reproduction check\n\nTwo halves, carrying different weight.\n\nThe first pins this page's own numbers. Nothing upstream computes them, so they are a regression on\nthis file: they check that the page still produces what it produced when it was written. Because the\ncallbacks are arithmetic and `sqrt`, they are also the numbers the Python twin prints.\n\nThe second is the construct the package's cross-language fixture pins, at zero tolerance, in all\nfour runners. Eight observations, the same Normal MLE with its analytic covariance, 200 replicates\nat seed 12345. The literals were read from the real C# `Bootstrap` class by the dotnet oracle\nemitter. They are checked here at 1e-15 relative, since R's decimal parser can land one ulp off a\nwritten literal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear <- \\(x, literal, tol = 1e-15) abs(x / literal - 1) < tol\n\nx <- c(4.1, 5.2, 4.8, 5.5, 4.9, 5.1, 5.3, 4.7)\ncheck <- bootstrap_custom(\n  data = x, resample = resample_iid, statistic = function(parameters) parameters,\n  fit_with_covariance = fit_with_cov, run_type = \"pivotal\",\n  replicates = 200, alpha = 0.1, seed = 12345\n)\n\nstopifnot(\n  # This page's own run: a within-R regression, not an upstream literal (see above).\n  near(piv$estimate[3], 5.1357565099517092),\n  near(piv$lower[1], 4.6002343747987944),\n  near(piv$upper[1], 4.7039019441786021),\n  near(piv$lower[2], 0.16695444885212568),\n  near(piv$upper[2], 0.27612953833178760),\n  near(piv$lower[3], 5.0510777889516243),\n  near(piv$upper[3], 5.2776613147818380),\n  near(piv$raw_lower[3], 5.0264321098309954),\n  near(piv$raw_upper[3], 5.2345946299122988),\n  identical(regular$lower, piv$raw_lower),\n  piv$pivotal_diagnostics$retained_pivotal_replicates == 400L,\n  piv$pivotal_diagnostics$invalid_pivotal_replicates == 0L,\n  near(linked$lower[1], 4.6002794038957076),\n  near(linked$upper[3], 5.2776620830082027),\n  policies$retained == c(267L, 400L, 400L),\n  policies$invalid == c(133L, 133L, 133L),\n\n  # The cross-language construct, read from the real C# Bootstrap class and pinned at zero\n  # tolerance in fixtures/callback/callback_cross_language.json.\n  near(check$lower[1], 4.5677601616611),\n  near(check$upper[1], 5.140545071728662),\n  near(check$lower[2], 0.3182992562465546),\n  near(check$upper[2], 0.9257315366348623),\n  near(check$standard_error[1], 0.22495884650687556),\n  near(check$raw_lower[1], 4.750000000000001),\n  near(check$raw_upper[2], 0.5183806274882354),\n  check$pivotal_diagnostics$retained_pivotal_replicates == 200L,\n  length(check$estimate) == 2L\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}