# Generated by cpp11: do not edit by hand

ch_analysis_univariate_run_ <- function(model_json, dataset, sampler, iterations, output_length, credible_level, seed, exceedance_probabilities, thinning_interval) {
  .Call(`_corehydror_ch_analysis_univariate_run_`, model_json, dataset, sampler, iterations, output_length, credible_level, seed, exceedance_probabilities, thinning_interval)
}

ch_analysis_fit_distributions_ <- function(dataset) {
  .Call(`_corehydror_ch_analysis_fit_distributions_`, dataset)
}

ch_analysis_b17c_run_ <- function(model_json, dataset, uncertainty_method, output_length, seed, confidence_level, exceedance_probabilities) {
  .Call(`_corehydror_ch_analysis_b17c_run_`, model_json, dataset, uncertainty_method, output_length, seed, confidence_level, exceedance_probabilities)
}

ch_analysis_family_run_ <- function(analysis_type, model_json, dataset, sampler, iterations, output_length, credible_level, seed, exceedance_probabilities, thinning_interval, training_time_steps, forecasting_time_steps) {
  .Call(`_corehydror_ch_analysis_family_run_`, analysis_type, model_json, dataset, sampler, iterations, output_length, credible_level, seed, exceedance_probabilities, thinning_interval, training_time_steps, forecasting_time_steps)
}

ch_analysis_diagnostics_run_ <- function(model_json, dataset, sampler, iterations, output_length, seed, thinning_interval, thin_every) {
  .Call(`_corehydror_ch_analysis_diagnostics_run_`, model_json, dataset, sampler, iterations, output_length, seed, thinning_interval, thin_every)
}

ch_analysis_extended_run_ <- function(target, construct_json, datasets_json) {
  .Call(`_corehydror_ch_analysis_extended_run_`, target, construct_json, datasets_json)
}

ch_bootstrap_run_ <- function(model, mu, sigma, sample_size, probabilities, dataset, replicates, seed, max_retries, run, ci_method, alpha) {
  .Call(`_corehydror_ch_bootstrap_run_`, model, mu, sigma, sample_size, probabilities, dataset, replicates, seed, max_retries, run, ci_method, alpha)
}

ch_cop_val_ <- function(type, params, method, args, marg_x_target, marg_x_params, marg_y_target, marg_y_params) {
  .Call(`_corehydror_ch_cop_val_`, type, params, method, args, marg_x_target, marg_x_params, marg_y_target, marg_y_params)
}

ch_cop_fit_ <- function(type, x, y, method, marg_x, marg_y) {
  .Call(`_corehydror_ch_cop_fit_`, type, x, y, method, marg_x, marg_y)
}

ch_data_frame_summary_ <- function(data_frame_json, plotting_parameter) {
  .Call(`_corehydror_ch_data_frame_summary_`, data_frame_json, plotting_parameter)
}

ch_model_log_likelihood_ <- function(model_json, dataset, params) {
  .Call(`_corehydror_ch_model_log_likelihood_`, model_json, dataset, params)
}

ch_threshold_diagnostics_ <- function(data, method, u_min, u_max, n_thresholds, confidence_level) {
  .Call(`_corehydror_ch_threshold_diagnostics_`, data, method, u_min, u_max, n_thresholds, confidence_level)
}

ch_dist_moments_ <- function(target, params) {
  .Call(`_corehydror_ch_dist_moments_`, target, params)
}

ch_dist_pdf_ <- function(target, params, x) {
  .Call(`_corehydror_ch_dist_pdf_`, target, params, x)
}

ch_dist_cdf_ <- function(target, params, x) {
  .Call(`_corehydror_ch_dist_cdf_`, target, params, x)
}

ch_dist_quantile_ <- function(target, params, p) {
  .Call(`_corehydror_ch_dist_quantile_`, target, params, p)
}

ch_dist_valid_ <- function(target, params) {
  .Call(`_corehydror_ch_dist_valid_`, target, params)
}

ch_dist_fit_ <- function(target, data, method) {
  .Call(`_corehydror_ch_dist_fit_`, target, data, method)
}

ch_dist_linear_moments_ <- function(target, params) {
  .Call(`_corehydror_ch_dist_linear_moments_`, target, params)
}

ch_dist_gamma_partial_kp_ <- function(skewness, probability) {
  .Call(`_corehydror_ch_dist_gamma_partial_kp_`, skewness, probability)
}

ch_dist_random_ <- function(target, params, sample_size, seed) {
  .Call(`_corehydror_ch_dist_random_`, target, params, sample_size, seed)
}

ch_dist_pdf_v_ <- function(target, params, xs) {
  .Call(`_corehydror_ch_dist_pdf_v_`, target, params, xs)
}

ch_dist_cdf_v_ <- function(target, params, xs) {
  .Call(`_corehydror_ch_dist_cdf_v_`, target, params, xs)
}

ch_dist_quantile_v_ <- function(target, params, probs) {
  .Call(`_corehydror_ch_dist_quantile_v_`, target, params, probs)
}

ch_dist_log_pdf_v_ <- function(target, params, xs) {
  .Call(`_corehydror_ch_dist_log_pdf_v_`, target, params, xs)
}

ch_dist_log_likelihood_ <- function(target, params, data) {
  .Call(`_corehydror_ch_dist_log_likelihood_`, target, params, data)
}

ch_dist_parameter_names_ <- function(target) {
  .Call(`_corehydror_ch_dist_parameter_names_`, target)
}

ch_dist_names_ <- function() {
  .Call(`_corehydror_ch_dist_names_`)
}

ch_trunc_moments_ <- function(base_target, base_params, lo, hi) {
  .Call(`_corehydror_ch_trunc_moments_`, base_target, base_params, lo, hi)
}

ch_trunc_pdf_ <- function(base_target, base_params, lo, hi, x) {
  .Call(`_corehydror_ch_trunc_pdf_`, base_target, base_params, lo, hi, x)
}

ch_trunc_cdf_ <- function(base_target, base_params, lo, hi, x) {
  .Call(`_corehydror_ch_trunc_cdf_`, base_target, base_params, lo, hi, x)
}

ch_trunc_quantile_ <- function(base_target, base_params, lo, hi, p) {
  .Call(`_corehydror_ch_trunc_quantile_`, base_target, base_params, lo, hi, p)
}

ch_trunc_valid_ <- function(base_target, base_params, lo, hi) {
  .Call(`_corehydror_ch_trunc_valid_`, base_target, base_params, lo, hi)
}

ch_emp_moments_ <- function(x_vals, p_vals, p_transform, p_descending) {
  .Call(`_corehydror_ch_emp_moments_`, x_vals, p_vals, p_transform, p_descending)
}

ch_emp_pdf_ <- function(x_vals, p_vals, p_transform, p_descending, x) {
  .Call(`_corehydror_ch_emp_pdf_`, x_vals, p_vals, p_transform, p_descending, x)
}

ch_emp_cdf_ <- function(x_vals, p_vals, p_transform, p_descending, x) {
  .Call(`_corehydror_ch_emp_cdf_`, x_vals, p_vals, p_transform, p_descending, x)
}

ch_emp_quantile_ <- function(x_vals, p_vals, p_transform, p_descending, prob) {
  .Call(`_corehydror_ch_emp_quantile_`, x_vals, p_vals, p_transform, p_descending, prob)
}

ch_emp_valid_ <- function(x_vals, p_vals, p_transform, p_descending) {
  .Call(`_corehydror_ch_emp_valid_`, x_vals, p_vals, p_transform, p_descending)
}

ch_kde_moments_ <- function(data, kernel, bandwidth, bounded_by_data) {
  .Call(`_corehydror_ch_kde_moments_`, data, kernel, bandwidth, bounded_by_data)
}

ch_kde_pdf_ <- function(data, kernel, bandwidth, bounded_by_data, x) {
  .Call(`_corehydror_ch_kde_pdf_`, data, kernel, bandwidth, bounded_by_data, x)
}

ch_kde_cdf_ <- function(data, kernel, bandwidth, bounded_by_data, x) {
  .Call(`_corehydror_ch_kde_cdf_`, data, kernel, bandwidth, bounded_by_data, x)
}

ch_kde_quantile_ <- function(data, kernel, bandwidth, bounded_by_data, prob) {
  .Call(`_corehydror_ch_kde_quantile_`, data, kernel, bandwidth, bounded_by_data, prob)
}

ch_kde_valid_ <- function(data, kernel, bandwidth, bounded_by_data) {
  .Call(`_corehydror_ch_kde_valid_`, data, kernel, bandwidth, bounded_by_data)
}

ch_mix_moments_ <- function(comp_targets, comp_params_list, weights, zero_inflated, zero_weight) {
  .Call(`_corehydror_ch_mix_moments_`, comp_targets, comp_params_list, weights, zero_inflated, zero_weight)
}

ch_mix_pdf_ <- function(comp_targets, comp_params_list, weights, zero_inflated, zero_weight, x) {
  .Call(`_corehydror_ch_mix_pdf_`, comp_targets, comp_params_list, weights, zero_inflated, zero_weight, x)
}

ch_mix_cdf_ <- function(comp_targets, comp_params_list, weights, zero_inflated, zero_weight, x) {
  .Call(`_corehydror_ch_mix_cdf_`, comp_targets, comp_params_list, weights, zero_inflated, zero_weight, x)
}

ch_mix_quantile_ <- function(comp_targets, comp_params_list, weights, zero_inflated, zero_weight, prob) {
  .Call(`_corehydror_ch_mix_quantile_`, comp_targets, comp_params_list, weights, zero_inflated, zero_weight, prob)
}

ch_mix_valid_ <- function(comp_targets, comp_params_list, weights, zero_inflated, zero_weight) {
  .Call(`_corehydror_ch_mix_valid_`, comp_targets, comp_params_list, weights, zero_inflated, zero_weight)
}

ch_mix_params_ <- function(comp_targets, comp_params_list, weights, zero_inflated, zero_weight) {
  .Call(`_corehydror_ch_mix_params_`, comp_targets, comp_params_list, weights, zero_inflated, zero_weight)
}

ch_cr_moments_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation) {
  .Call(`_corehydror_ch_cr_moments_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation)
}

ch_cr_pdf_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x) {
  .Call(`_corehydror_ch_cr_pdf_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x)
}

ch_cr_log_pdf_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x) {
  .Call(`_corehydror_ch_cr_log_pdf_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x)
}

ch_cr_cdf_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x) {
  .Call(`_corehydror_ch_cr_cdf_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x)
}

ch_cr_quantile_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, prob) {
  .Call(`_corehydror_ch_cr_quantile_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, prob)
}

ch_cr_valid_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation) {
  .Call(`_corehydror_ch_cr_valid_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation)
}

ch_cr_dependency_change_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, dependency2, correlation, x, field, i, j) {
  .Call(`_corehydror_ch_cr_dependency_change_`, comp_targets, comp_params_list, minimum_of_rv, dependency, dependency2, correlation, x, field, i, j)
}

ch_dist_spec_run_ <- function(spec_json, method, args_json) {
  .Call(`_corehydror_ch_dist_spec_run_`, spec_json, method, args_json)
}

ch_copula_run_ <- function(spec_json, method, args_json) {
  .Call(`_corehydror_ch_copula_run_`, spec_json, method, args_json)
}

ch_mvdist_run_ <- function(spec_json, method, args_json) {
  .Call(`_corehydror_ch_mvdist_run_`, spec_json, method, args_json)
}

ch_estimation_run_ <- function(target, model_json, dataset, optimizer, sample_size, seed) {
  .Call(`_corehydror_ch_estimation_run_`, target, model_json, dataset, optimizer, sample_size, seed)
}

ch_estimation_bic_ <- function(target, model_json, dataset, optimizer, n) {
  .Call(`_corehydror_ch_estimation_bic_`, target, model_json, dataset, optimizer, n)
}

ch_estimation_bayes_run_ <- function(model_json, dataset, sampler, seed, iterations, warmup_iterations, number_of_chains, thinning_interval, initial_iterations, output_length) {
  .Call(`_corehydror_ch_estimation_bayes_run_`, model_json, dataset, sampler, seed, iterations, warmup_iterations, number_of_chains, thinning_interval, initial_iterations, output_length)
}

ch_model_data_frame_ <- function(model_json, dataset) {
  .Call(`_corehydror_ch_model_data_frame_`, model_json, dataset)
}

ch_model_validate_ <- function(model_json, dataset) {
  .Call(`_corehydror_ch_model_validate_`, model_json, dataset)
}

ch_model_simulate_ <- function(model_json, dataset, sample_size, seed) {
  .Call(`_corehydror_ch_model_simulate_`, model_json, dataset, sample_size, seed)
}

ch_estimation_gmm_run_ <- function(model_json, dataset, strategy, optimizer, max_gmm_iterations, sample_size, seed) {
  .Call(`_corehydror_ch_estimation_gmm_run_`, model_json, dataset, strategy, optimizer, max_gmm_iterations, sample_size, seed)
}

ch_estimation_gmm_qvar_ <- function(model_json, dataset, strategy, optimizer, max_gmm_iterations, aep) {
  .Call(`_corehydror_ch_estimation_gmm_qvar_`, model_json, dataset, strategy, optimizer, max_gmm_iterations, aep)
}

ch_fit_run_ <- function(target, construct_json, dataset) {
  .Call(`_corehydror_ch_fit_run_`, target, construct_json, dataset)
}

ch_fit_diagnostics_ <- function(target, construct_json, dataset) {
  .Call(`_corehydror_ch_fit_diagnostics_`, target, construct_json, dataset)
}

ch_fit_quantile_variance_ <- function(construct_json, dataset, aep) {
  .Call(`_corehydror_ch_fit_quantile_variance_`, construct_json, dataset, aep)
}

ch_gev_pdf_ <- function(x, location, scale, shape) {
  .Call(`_corehydror_ch_gev_pdf_`, x, location, scale, shape)
}

ch_gev_cdf_ <- function(x, location, scale, shape) {
  .Call(`_corehydror_ch_gev_cdf_`, x, location, scale, shape)
}

ch_gev_quantile_ <- function(p, location, scale, shape) {
  .Call(`_corehydror_ch_gev_quantile_`, p, location, scale, shape)
}

ch_gev_moments_ <- function(location, scale, shape) {
  .Call(`_corehydror_ch_gev_moments_`, location, scale, shape)
}

ch_gev_valid_ <- function(location, scale, shape) {
  .Call(`_corehydror_ch_gev_valid_`, location, scale, shape)
}

ch_gev_fit_ <- function(data, method) {
  .Call(`_corehydror_ch_gev_fit_`, data, method)
}

ch_gev_quantile_variance_ <- function(p, location, scale, shape, sample_size) {
  .Call(`_corehydror_ch_gev_quantile_variance_`, p, location, scale, shape, sample_size)
}

ch_gev_linear_moments_ <- function(location, scale, shape) {
  .Call(`_corehydror_ch_gev_linear_moments_`, location, scale, shape)
}

ch_gev_quantile_gradient_ <- function(p, location, scale, shape) {
  .Call(`_corehydror_ch_gev_quantile_gradient_`, p, location, scale, shape)
}

ch_gev_parameter_covariance_ <- function(location, scale, shape, sample_size) {
  .Call(`_corehydror_ch_gev_parameter_covariance_`, location, scale, shape, sample_size)
}

ch_mcmc_run_ <- function(sampler_type, model_name, family, dataset, settings) {
  .Call(`_corehydror_ch_mcmc_run_`, sampler_type, model_name, family, dataset, settings)
}

ch_dirichlet_val_ <- function(method, alpha, args) {
  .Call(`_corehydror_ch_dirichlet_val_`, method, alpha, args)
}

ch_multinomial_val_ <- function(method, n, p, args) {
  .Call(`_corehydror_ch_multinomial_val_`, method, n, p, args)
}

ch_bve_cdf_ <- function(method, x1, x2, p_flat, nrow, transforms, args) {
  .Call(`_corehydror_ch_bve_cdf_`, method, x1, x2, p_flat, nrow, transforms, args)
}

ch_bve_cdf_after_set_parameters_ <- function(x1, x2, p_flat, nrow, transforms, x1_new, x2_new, p_new_flat, nrow_new, x1_eval, x2_eval) {
  .Call(`_corehydror_ch_bve_cdf_after_set_parameters_`, x1, x2, p_flat, nrow, transforms, x1_new, x2_new, p_new_flat, nrow_new, x1_eval, x2_eval)
}

ch_mvn_val_ <- function(method, mean, cov_flat, args) {
  .Call(`_corehydror_ch_mvn_val_`, method, mean, cov_flat, args)
}

ch_mvn_marginal_mean_ <- function(mean, cov_flat, indices, idx) {
  .Call(`_corehydror_ch_mvn_marginal_mean_`, mean, cov_flat, indices, idx)
}

ch_mvn_marginal_covariance_ <- function(mean, cov_flat, indices, i, j) {
  .Call(`_corehydror_ch_mvn_marginal_covariance_`, mean, cov_flat, indices, i, j)
}

ch_mvn_marginal_log_pdf_ <- function(mean, cov_flat, indices, point) {
  .Call(`_corehydror_ch_mvn_marginal_log_pdf_`, mean, cov_flat, indices, point)
}

ch_mvn_marginal_dimension_ <- function(mean, cov_flat, indices) {
  .Call(`_corehydror_ch_mvn_marginal_dimension_`, mean, cov_flat, indices)
}

ch_mvn_conditional_mean_ <- function(mean, cov_flat, obs_indices, obs_values, idx) {
  .Call(`_corehydror_ch_mvn_conditional_mean_`, mean, cov_flat, obs_indices, obs_values, idx)
}

ch_mvn_conditional_covariance_ <- function(mean, cov_flat, obs_indices, obs_values, i, j) {
  .Call(`_corehydror_ch_mvn_conditional_covariance_`, mean, cov_flat, obs_indices, obs_values, i, j)
}

ch_mvn_conditional_dimension_ <- function(mean, cov_flat, obs_indices, obs_values) {
  .Call(`_corehydror_ch_mvn_conditional_dimension_`, mean, cov_flat, obs_indices, obs_values)
}

ch_mvn_cdf_seq_ <- function(mean, cov_flat, seed, xs_flat, k) {
  .Call(`_corehydror_ch_mvn_cdf_seq_`, mean, cov_flat, seed, xs_flat, k)
}

ch_mvn_interval_seq_ <- function(mean, cov_flat, seed, lowers_flat, uppers_flat, k) {
  .Call(`_corehydror_ch_mvn_interval_seq_`, mean, cov_flat, seed, lowers_flat, uppers_flat, k)
}

ch_mvn_mvndst_seq_ <- function(n_dim, seed, lower_flat, upper_flat, infin_flat, correl_flat, maxpts_v, abseps_v, releps_v, k) {
  .Call(`_corehydror_ch_mvn_mvndst_seq_`, n_dim, seed, lower_flat, upper_flat, infin_flat, correl_flat, maxpts_v, abseps_v, releps_v, k)
}

ch_mvt_val_ <- function(method, df, location, scale_flat, args) {
  .Call(`_corehydror_ch_mvt_val_`, method, df, location, scale_flat, args)
}

ch_sobol_generate_ <- function(dimension, n_steps, path) {
  .Call(`_corehydror_ch_sobol_generate_`, dimension, n_steps, path)
}

ch_sobol_skip_to_ <- function(dimension, index, path) {
  .Call(`_corehydror_ch_sobol_skip_to_`, dimension, index, path)
}

ch_mgbt_test_ <- function(x) {
  .Call(`_corehydror_ch_mgbt_test_`, x)
}

ch_box_cox_lambda_ <- function(values) {
  .Call(`_corehydror_ch_box_cox_lambda_`, values)
}

ch_box_cox_ <- function(values, lambda) {
  .Call(`_corehydror_ch_box_cox_`, values, lambda)
}

ch_box_cox_inverse_ <- function(values, lambda) {
  .Call(`_corehydror_ch_box_cox_inverse_`, values, lambda)
}

ch_yeo_johnson_lambda_ <- function(values) {
  .Call(`_corehydror_ch_yeo_johnson_lambda_`, values)
}

ch_yeo_johnson_ <- function(values, lambda) {
  .Call(`_corehydror_ch_yeo_johnson_`, values, lambda)
}

ch_yeo_johnson_inverse_ <- function(values, lambda) {
  .Call(`_corehydror_ch_yeo_johnson_inverse_`, values, lambda)
}

ch_plotting_positions_ <- function(n, method) {
  .Call(`_corehydror_ch_plotting_positions_`, n, method)
}

ch_plotting_positions_alpha_ <- function(n, alpha) {
  .Call(`_corehydror_ch_plotting_positions_alpha_`, n, alpha)
}

ch_latin_hypercube_ <- function(sample_size, dimension, seed, median) {
  .Call(`_corehydror_ch_latin_hypercube_`, sample_size, dimension, seed, median)
}
